sudo: false
language: cpp
os:
- linux
compiler:
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-multilib
    - g++-multilib
    - zlib1g-dev:i386
    - libmysqlclient-dev:i386
    - libpq-dev:i386
    - libssl-dev:i386
    - gperf
    - openjdk-8-jre-headless:i386
    - openjdk-8-jre:i386
    - openjdk-8-jdk:i386
    - libsctp1:i386
    - ant
script:
- CC='gcc -m32' CXX='g++ -m32' cmake . -DNWNX_EXCLUDE_PLUGINS='ruby'
- make all
after_failure:
- cat CMakeFiles/CMakeError.log
env:
  global:
  - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-i386"