
/***************************************************************************
    CombatTables.h - NWN Combat Tables
    Copyright (C) 2007 Doug Swarin (zac@intertex.net)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 ***************************************************************************/

#include "NWNXWeapons.h"

uint16_t Table_WeaponSpecialization[NWNX_WEAPONS_BASE_ITEM_TABLE_SIZE] = {
    [BASE_ITEM_BASTARDSWORD]            = FEAT_WEAPON_SPECIALIZATION_BASTARD_SWORD,
    [BASE_ITEM_BATTLEAXE]               = FEAT_WEAPON_SPECIALIZATION_BATTLE_AXE,
    [BASE_ITEM_BRACER]                  = FEAT_WEAPON_SPECIALIZATION_UNARMED_STRIKE,
    [BASE_ITEM_CBLUDGWEAPON]            = FEAT_WEAPON_SPECIALIZATION_CREATURE,
    [BASE_ITEM_CLUB]                    = FEAT_WEAPON_SPECIALIZATION_CLUB,
    [BASE_ITEM_CPIERCWEAPON]            = FEAT_WEAPON_SPECIALIZATION_CREATURE,
    [BASE_ITEM_CSLASHWEAPON]            = FEAT_WEAPON_SPECIALIZATION_CREATURE,
    [BASE_ITEM_CSLSHPRCWEAP]            = FEAT_WEAPON_SPECIALIZATION_CREATURE,
    [BASE_ITEM_DAGGER]                  = FEAT_WEAPON_SPECIALIZATION_DAGGER,
    [BASE_ITEM_DART]                    = FEAT_WEAPON_SPECIALIZATION_DART,
    [BASE_ITEM_DIREMACE]                = FEAT_WEAPON_SPECIALIZATION_DIRE_MACE,
    [BASE_ITEM_DOUBLEAXE]               = FEAT_WEAPON_SPECIALIZATION_DOUBLE_AXE,
    [BASE_ITEM_DWARVENWARAXE]           = FEAT_WEAPON_SPECIALIZATION_DWAXE,
    [BASE_ITEM_GLOVES]                  = FEAT_WEAPON_SPECIALIZATION_UNARMED_STRIKE,
    [BASE_ITEM_GREATAXE]                = FEAT_WEAPON_SPECIALIZATION_GREAT_AXE,
    [BASE_ITEM_GREATSWORD]              = FEAT_WEAPON_SPECIALIZATION_GREAT_SWORD,
    [BASE_ITEM_HALBERD]                 = FEAT_WEAPON_SPECIALIZATION_HALBERD,
    [BASE_ITEM_HANDAXE]                 = FEAT_WEAPON_SPECIALIZATION_HAND_AXE,
    [BASE_ITEM_HEAVYCROSSBOW]           = FEAT_WEAPON_SPECIALIZATION_HEAVY_CROSSBOW,
    [BASE_ITEM_HEAVYFLAIL]              = FEAT_WEAPON_SPECIALIZATION_HEAVY_FLAIL,
    [BASE_ITEM_KAMA]                    = FEAT_WEAPON_SPECIALIZATION_KAMA,
    [BASE_ITEM_KATANA]                  = FEAT_WEAPON_SPECIALIZATION_KATANA,
    [BASE_ITEM_KUKRI]                   = FEAT_WEAPON_SPECIALIZATION_KUKRI,
    [BASE_ITEM_LIGHTCROSSBOW]           = FEAT_WEAPON_SPECIALIZATION_LIGHT_CROSSBOW,
    [BASE_ITEM_LIGHTFLAIL]              = FEAT_WEAPON_SPECIALIZATION_LIGHT_FLAIL,
    [BASE_ITEM_LIGHTHAMMER]             = FEAT_WEAPON_SPECIALIZATION_LIGHT_HAMMER,
    [BASE_ITEM_LIGHTMACE]               = FEAT_WEAPON_SPECIALIZATION_LIGHT_MACE,
    [BASE_ITEM_LONGBOW]                 = FEAT_WEAPON_SPECIALIZATION_LONGBOW,
    [BASE_ITEM_LONGSWORD]               = FEAT_WEAPON_SPECIALIZATION_LONG_SWORD,
    [BASE_ITEM_MORNINGSTAR]             = FEAT_WEAPON_SPECIALIZATION_MORNING_STAR,
    [BASE_ITEM_QUARTERSTAFF]            = FEAT_WEAPON_SPECIALIZATION_STAFF,
    [BASE_ITEM_RAPIER]                  = FEAT_WEAPON_SPECIALIZATION_RAPIER,
    [BASE_ITEM_SCIMITAR]                = FEAT_WEAPON_SPECIALIZATION_SCIMITAR,
    [BASE_ITEM_SCYTHE]                  = FEAT_WEAPON_SPECIALIZATION_SCYTHE,
    [BASE_ITEM_SHORTBOW]                = FEAT_WEAPON_SPECIALIZATION_SHORTBOW,
    [BASE_ITEM_SHORTSPEAR]              = FEAT_WEAPON_SPECIALIZATION_SPEAR,
    [BASE_ITEM_SHORTSWORD]              = FEAT_WEAPON_SPECIALIZATION_SHORT_SWORD,
    [BASE_ITEM_SHURIKEN]                = FEAT_WEAPON_SPECIALIZATION_SHURIKEN,
    [BASE_ITEM_SICKLE]                  = FEAT_WEAPON_SPECIALIZATION_SICKLE,
    [BASE_ITEM_SLING]                   = FEAT_WEAPON_SPECIALIZATION_SLING,
    [BASE_ITEM_THROWINGAXE]             = FEAT_WEAPON_SPECIALIZATION_THROWING_AXE,
    [BASE_ITEM_TRIDENT]                 = FEAT_WEAPON_SPECIALIZATION_TRIDENT,
    [BASE_ITEM_TWOBLADEDSWORD]          = FEAT_WEAPON_SPECIALIZATION_TWO_BLADED_SWORD,
    [BASE_ITEM_WARHAMMER]               = FEAT_WEAPON_SPECIALIZATION_WAR_HAMMER,
    [BASE_ITEM_WHIP]                    = FEAT_WEAPON_SPECIALIZATION_WHIP,
};

/* vim: set sw=4: */
