
/***************************************************************************
    CombatTables.h - NWN Combat Tables
    Copyright (C) 2007 Doug Swarin (zac@intertex.net)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 ***************************************************************************/

#include "NWNXWeapons.h"

uint16_t Table_WeaponEpicSpecialization[NWNX_WEAPONS_BASE_ITEM_TABLE_SIZE] = {
    [BASE_ITEM_BASTARDSWORD]            = FEAT_EPIC_WEAPON_SPECIALIZATION_BASTARDSWORD,
    [BASE_ITEM_BATTLEAXE]               = FEAT_EPIC_WEAPON_SPECIALIZATION_BATTLEAXE,
    [BASE_ITEM_BRACER]                  = FEAT_EPIC_WEAPON_SPECIALIZATION_UNARMED,
    [BASE_ITEM_CBLUDGWEAPON]            = FEAT_EPIC_WEAPON_SPECIALIZATION_CREATURE,
    [BASE_ITEM_CLUB]                    = FEAT_EPIC_WEAPON_SPECIALIZATION_CLUB,
    [BASE_ITEM_CPIERCWEAPON]            = FEAT_EPIC_WEAPON_SPECIALIZATION_CREATURE,
    [BASE_ITEM_CSLASHWEAPON]            = FEAT_EPIC_WEAPON_SPECIALIZATION_CREATURE,
    [BASE_ITEM_CSLSHPRCWEAP]            = FEAT_EPIC_WEAPON_SPECIALIZATION_CREATURE,
    [BASE_ITEM_DAGGER]                  = FEAT_EPIC_WEAPON_SPECIALIZATION_DAGGER,
    [BASE_ITEM_DART]                    = FEAT_EPIC_WEAPON_SPECIALIZATION_DART,
    [BASE_ITEM_DIREMACE]                = FEAT_EPIC_WEAPON_SPECIALIZATION_DIREMACE,
    [BASE_ITEM_DOUBLEAXE]               = FEAT_EPIC_WEAPON_SPECIALIZATION_DOUBLEAXE,
    [BASE_ITEM_DWARVENWARAXE]           = FEAT_EPIC_WEAPON_SPECIALIZATION_DWAXE,
    [BASE_ITEM_GLOVES]                  = FEAT_EPIC_WEAPON_SPECIALIZATION_UNARMED,
    [BASE_ITEM_GREATAXE]                = FEAT_EPIC_WEAPON_SPECIALIZATION_GREATAXE,
    [BASE_ITEM_GREATSWORD]              = FEAT_EPIC_WEAPON_SPECIALIZATION_GREATSWORD,
    [BASE_ITEM_HALBERD]                 = FEAT_EPIC_WEAPON_SPECIALIZATION_HALBERD,
    [BASE_ITEM_HANDAXE]                 = FEAT_EPIC_WEAPON_SPECIALIZATION_HANDAXE,
    [BASE_ITEM_HEAVYCROSSBOW]           = FEAT_EPIC_WEAPON_SPECIALIZATION_HEAVYCROSSBOW,
    [BASE_ITEM_HEAVYFLAIL]              = FEAT_EPIC_WEAPON_SPECIALIZATION_HEAVYFLAIL,
    [BASE_ITEM_KAMA]                    = FEAT_EPIC_WEAPON_SPECIALIZATION_KAMA,
    [BASE_ITEM_KATANA]                  = FEAT_EPIC_WEAPON_SPECIALIZATION_KATANA,
    [BASE_ITEM_KUKRI]                   = FEAT_EPIC_WEAPON_SPECIALIZATION_KUKRI,
    [BASE_ITEM_LIGHTCROSSBOW]           = FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHTCROSSBOW,
    [BASE_ITEM_LIGHTFLAIL]              = FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHTFLAIL,
    [BASE_ITEM_LIGHTHAMMER]             = FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHTHAMMER,
    [BASE_ITEM_LIGHTMACE]               = FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHTMACE,
    [BASE_ITEM_LONGBOW]                 = FEAT_EPIC_WEAPON_SPECIALIZATION_LONGBOW,
    [BASE_ITEM_LONGSWORD]               = FEAT_EPIC_WEAPON_SPECIALIZATION_LONGSWORD,
    [BASE_ITEM_MORNINGSTAR]             = FEAT_EPIC_WEAPON_SPECIALIZATION_MORNINGSTAR,
    [BASE_ITEM_QUARTERSTAFF]            = FEAT_EPIC_WEAPON_SPECIALIZATION_QUARTERSTAFF,
    [BASE_ITEM_RAPIER]                  = FEAT_EPIC_WEAPON_SPECIALIZATION_RAPIER,
    [BASE_ITEM_SCIMITAR]                = FEAT_EPIC_WEAPON_SPECIALIZATION_SCIMITAR,
    [BASE_ITEM_SCYTHE]                  = FEAT_EPIC_WEAPON_SPECIALIZATION_SCYTHE,
    [BASE_ITEM_SHORTBOW]                = FEAT_EPIC_WEAPON_SPECIALIZATION_SHORTBOW,
    [BASE_ITEM_SHORTSPEAR]              = FEAT_EPIC_WEAPON_SPECIALIZATION_SHORTSPEAR,
    [BASE_ITEM_SHORTSWORD]              = FEAT_EPIC_WEAPON_SPECIALIZATION_SHORTSWORD,
    [BASE_ITEM_SHURIKEN]                = FEAT_EPIC_WEAPON_SPECIALIZATION_SHURIKEN,
    [BASE_ITEM_SICKLE]                  = FEAT_EPIC_WEAPON_SPECIALIZATION_SICKLE,
    [BASE_ITEM_SLING]                   = FEAT_EPIC_WEAPON_SPECIALIZATION_SLING,
    [BASE_ITEM_THROWINGAXE]             = FEAT_EPIC_WEAPON_SPECIALIZATION_THROWINGAXE,
    [BASE_ITEM_TRIDENT]                 = FEAT_EPIC_WEAPON_SPECIALIZATION_TRIDENT,
    [BASE_ITEM_TWOBLADEDSWORD]          = FEAT_EPIC_WEAPON_SPECIALIZATION_TWOBLADEDSWORD,
    [BASE_ITEM_WARHAMMER]               = FEAT_EPIC_WEAPON_SPECIALIZATION_WARHAMMER,
    [BASE_ITEM_WHIP]                    = FEAT_EPIC_WEAPON_SPECIALIZATION_WHIP,
};


/* vim: set sw=4: */
