/*
 *  NWNeXalt - Empty File
 *  (c) 2007 Doug Swarin (zac@#defineertex.net)
 *
 *  This program is free software you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *  $Id$
 *  $HeadURL$
 *
 */

#ifndef _NX_NWN_CONST_VFX_H_
#define _NX_NWN_CONST_VFX_H_

#define VFX_DUR_BLUR                       0
#define VFX_DUR_DARKNESS                   1
#define VFX_DUR_ENTANGLE                   2
#define VFX_DUR_FREEDOM_OF_MOVEMENT        3
#define VFX_DUR_GLOBE_INVULNERABILITY      4
#define VFX_DUR_BLACKOUT                   5
#define VFX_DUR_INVISIBILITY               6
#define VFX_DUR_MIND_AFFECTING_NEGATIVE    7
#define VFX_DUR_MIND_AFFECTING_POSITIVE    8
#define VFX_DUR_GHOSTLY_VISAGE             9
#define VFX_DUR_ETHEREAL_VISAGE            10
#define VFX_DUR_PROT_BARKSKIN              11
#define VFX_DUR_PROT_GREATER_STONESKIN     12
#define VFX_DUR_PROT_PREMONITION           13
#define VFX_DUR_PROT_SHADOW_ARMOR          14
#define VFX_DUR_PROT_STONESKIN             15
#define VFX_DUR_SANCTUARY                  16
#define VFX_DUR_WEB                        17
#define VFX_FNF_BLINDDEAF                  18
#define VFX_FNF_DISPEL                     19
#define VFX_FNF_DISPEL_DISJUNCTION         20
#define VFX_FNF_DISPEL_GREATER             21
#define VFX_FNF_FIREBALL                   22
#define VFX_FNF_FIRESTORM                  23
#define VFX_FNF_IMPLOSION                  24
#define VFX_FNF_MASS_HEAL                  26
#define VFX_FNF_MASS_MIND_AFFECTING        27
#define VFX_FNF_METEOR_SWARM               28
#define VFX_FNF_NATURES_BALANCE            29
#define VFX_FNF_PWKILL                     30
#define VFX_FNF_PWSTUN                     31
#define VFX_FNF_SUMMON_GATE                32
#define VFX_FNF_SUMMON_MONSTER_1           33
#define VFX_FNF_SUMMON_MONSTER_2           34
#define VFX_FNF_SUMMON_MONSTER_3           35
#define VFX_FNF_SUMMON_UNDEAD              36
#define VFX_FNF_SUNBEAM                    37
#define VFX_FNF_TIME_STOP                  38
#define VFX_FNF_WAIL_O_BANSHEES            39
#define VFX_FNF_WEIRD                      40
#define VFX_FNF_WORD                       41
#define VFX_IMP_AC_BONUS                   42
#define VFX_IMP_ACID_L                     43
#define VFX_IMP_ACID_S                     44
#define VFX_IMP_BLIND_DEAF_M               46
#define VFX_IMP_BREACH                     47
#define VFX_IMP_CONFUSION_S                48
#define VFX_IMP_DAZED_S                    49
#define VFX_IMP_DEATH                      50
#define VFX_IMP_DISEASE_S                  51
#define VFX_IMP_DISPEL                     52
#define VFX_IMP_DISPEL_DISJUNCTION         53
#define VFX_IMP_DIVINE_STRIKE_FIRE         54
#define VFX_IMP_DIVINE_STRIKE_HOLY         55
#define VFX_IMP_DOMINATE_S                 56
#define VFX_IMP_DOOM                       57
#define VFX_IMP_FEAR_S                     58
#define VFX_IMP_FLAME_M                    60
#define VFX_IMP_FLAME_S                    61
#define VFX_IMP_FROST_L                    62
#define VFX_IMP_FROST_S                    63
#define VFX_IMP_GREASE                     64
#define VFX_IMP_HASTE                      65
#define VFX_IMP_HEALING_G                  66
#define VFX_IMP_HEALING_L                  67
#define VFX_IMP_HEALING_M                  68
#define VFX_IMP_HEALING_S                  69
#define VFX_IMP_HEALING_X                  70
#define VFX_IMP_HOLY_AID                   71
#define VFX_IMP_KNOCK                      72
#define VFX_BEAM_LIGHTNING                 73
#define VFX_IMP_LIGHTNING_M                74
#define VFX_IMP_LIGHTNING_S                75
#define VFX_IMP_MAGBLUE                    76
#define VFX_IMP_NEGATIVE_ENERGY            81
#define VFX_DUR_PARALYZE_HOLD              82
#define VFX_IMP_POISON_L                   83
#define VFX_IMP_POISON_S                   84
#define VFX_IMP_POLYMORPH                  85
#define VFX_IMP_PULSE_COLD                 86
#define VFX_IMP_PULSE_FIRE                 87
#define VFX_IMP_PULSE_HOLY                 88
#define VFX_IMP_PULSE_NEGATIVE             89
#define VFX_IMP_RAISE_DEAD                 90
#define VFX_IMP_REDUCE_ABILITY_SCORE       91
#define VFX_IMP_REMOVE_CONDITION           92
#define VFX_IMP_SILENCE                    93
#define VFX_IMP_SLEEP                      94
#define VFX_IMP_SLOW                       95
#define VFX_IMP_SONIC                      96
#define VFX_IMP_STUN                       97
#define VFX_IMP_SUNSTRIKE                  98
#define VFX_IMP_UNSUMMON                   99
#define VFX_COM_SPECIAL_BLUE_RED           100
#define VFX_COM_SPECIAL_PINK_ORANGE        101
#define VFX_COM_SPECIAL_RED_WHITE          102
#define VFX_COM_SPECIAL_RED_ORANGE         103
#define VFX_COM_SPECIAL_WHITE_BLUE         104
#define VFX_COM_SPECIAL_WHITE_ORANGE       105
#define VFX_COM_BLOOD_REG_WIMP             106
#define VFX_COM_BLOOD_LRG_WIMP             107
#define VFX_COM_BLOOD_CRT_WIMP             108
#define VFX_COM_BLOOD_REG_RED              109
#define VFX_COM_BLOOD_REG_GREEN            110
#define VFX_COM_BLOOD_REG_YELLOW           111
#define VFX_COM_BLOOD_LRG_RED              112
#define VFX_COM_BLOOD_LRG_GREEN            113
#define VFX_COM_BLOOD_LRG_YELLOW           114
#define VFX_COM_BLOOD_CRT_RED              115
#define VFX_COM_BLOOD_CRT_GREEN            116
#define VFX_COM_BLOOD_CRT_YELLOW           117
#define VFX_COM_SPARKS_PARRY               118
#define VFX_COM_UNLOAD_MODEL               120
#define VFX_COM_CHUNK_RED_SMALL            121
#define VFX_COM_CHUNK_RED_MEDIUM           122
#define VFX_COM_CHUNK_GREEN_SMALL          123
#define VFX_COM_CHUNK_GREEN_MEDIUM         124
#define VFX_COM_CHUNK_YELLOW_SMALL         125
#define VFX_COM_CHUNK_YELLOW_MEDIUM        126
#define VFX_IMP_LEAF                       132
#define VFX_IMP_CLOUD                      133
#define VFX_IMP_WIND                       134
#define VFX_IMP_ROCKEXPLODE                135
#define VFX_IMP_ROCKEXPLODE2               136
#define VFX_IMP_SMOKING                    137
#define VFX_DUR_SPELLTURNING               138
#define VFX_IMP_IMPROVE_ABILITY_SCORE      139
#define VFX_IMP_CHARM                      140
#define VFX_IMP_MAGICAL_VISION             141
#define VFX_IMP_EVIL_HELP                  144
#define VFX_IMP_GOOD_HELP                  145
#define VFX_IMP_DEATH_WARD                 146
#define VFX_DUR_ELEMENTAL_SHIELD           147
#define VFX_DUR_LIGHT                      148
#define VFX_IMP_MAGIC_PROTECTION           149
#define VFX_IMP_SUPER_HEROISM              150
#define VFX_FNF_STORM                      151
#define VFX_IMP_ELEMENTAL_PROTECTION       152
#define VFX_DUR_LIGHT_BLUE_5               153
#define VFX_DUR_LIGHT_BLUE_10              154
#define VFX_DUR_LIGHT_BLUE_15              155
#define VFX_DUR_LIGHT_BLUE_20              156
#define VFX_DUR_LIGHT_YELLOW_5             157
#define VFX_DUR_LIGHT_YELLOW_10            158
#define VFX_DUR_LIGHT_YELLOW_15            159
#define VFX_DUR_LIGHT_YELLOW_20            160
#define VFX_DUR_LIGHT_PURPLE_5             161
#define VFX_DUR_LIGHT_PURPLE_10            162
#define VFX_DUR_LIGHT_PURPLE_15            163
#define VFX_DUR_LIGHT_PURPLE_20            164
#define VFX_DUR_LIGHT_RED_5                165
#define VFX_DUR_LIGHT_RED_10               166
#define VFX_DUR_LIGHT_RED_15               167
#define VFX_DUR_LIGHT_RED_20               168
#define VFX_DUR_LIGHT_ORANGE_5             169
#define VFX_DUR_LIGHT_ORANGE_10            170
#define VFX_DUR_LIGHT_ORANGE_15            171
#define VFX_DUR_LIGHT_ORANGE_20            172
#define VFX_DUR_LIGHT_WHITE_5              173
#define VFX_DUR_LIGHT_WHITE_10             174
#define VFX_DUR_LIGHT_WHITE_15             175
#define VFX_DUR_LIGHT_WHITE_20             176
#define VFX_DUR_LIGHT_GREY_5               177
#define VFX_DUR_LIGHT_GREY_10              178
#define VFX_DUR_LIGHT_GREY_15              179
#define VFX_DUR_LIGHT_GREY_20              180
#define VFX_IMP_MIRV                       181
#define VFX_DUR_DARKVISION                 182
#define VFX_FNF_SOUND_BURST                183
#define VFX_FNF_STRIKE_HOLY                184
#define VFX_FNF_LOS_EVIL_10                185
#define VFX_FNF_LOS_EVIL_20                186
#define VFX_FNF_LOS_EVIL_30                187
#define VFX_FNF_LOS_HOLY_10                188
#define VFX_FNF_LOS_HOLY_20                189
#define VFX_FNF_LOS_HOLY_30                190
#define VFX_FNF_LOS_NORMAL_10              191
#define VFX_FNF_LOS_NORMAL_20              192
#define VFX_FNF_LOS_NORMAL_30              193
#define VFX_IMP_HEAD_ACID                  194
#define VFX_IMP_HEAD_FIRE                  195
#define VFX_IMP_HEAD_SONIC                 196
#define VFX_IMP_HEAD_ELECTRICITY           197
#define VFX_IMP_HEAD_COLD                  198
#define VFX_IMP_HEAD_HOLY                  199
#define VFX_IMP_HEAD_NATURE                200
#define VFX_IMP_HEAD_HEAL                  201
#define VFX_IMP_HEAD_MIND                  202
#define VFX_IMP_HEAD_EVIL                  203
#define VFX_IMP_HEAD_ODD                   204
#define VFX_DUR_CESSATE_NEUTRAL            205
#define VFX_DUR_CESSATE_POSITIVE           206
#define VFX_DUR_CESSATE_NEGATIVE           207
#define VFX_DUR_MIND_AFFECTING_DISABLED    208
#define VFX_DUR_MIND_AFFECTING_DOMINATED   209
#define VFX_BEAM_FIRE                      210
#define VFX_BEAM_COLD                      211
#define VFX_BEAM_HOLY                      212
#define VFX_BEAM_MIND                      213
#define VFX_BEAM_EVIL                      214
#define VFX_BEAM_ODD                       215
#define VFX_BEAM_FIRE_LASH                 216
#define VFX_IMP_DEATH_L                    217
#define VFX_DUR_MIND_AFFECTING_FEAR        218
#define VFX_FNF_SUMMON_CELESTIAL           219
#define VFX_DUR_GLOBE_MINOR                220
#define VFX_IMP_RESTORATION_LESSER         221
#define VFX_IMP_RESTORATION                222
#define VFX_IMP_RESTORATION_GREATER        223
#define VFX_DUR_PROTECTION_ELEMENTS        224
#define VFX_DUR_PROTECTION_GOOD_MINOR      225
#define VFX_DUR_PROTECTION_GOOD_MAJOR      226
#define VFX_DUR_PROTECTION_EVIL_MINOR      227
#define VFX_DUR_PROTECTION_EVIL_MAJOR      228
#define VFX_DUR_MAGICAL_SIGHT              229
#define VFX_DUR_WEB_MASS                   230
#define VFX_FNF_ICESTORM                   231
#define VFX_DUR_PARALYZED                  232
#define VFX_IMP_MIRV_FLAME                 233
#define VFX_IMP_DESTRUCTION                234
#define VFX_COM_CHUNK_RED_LARGE            235
#define VFX_COM_CHUNK_BONE_MEDIUM          236
#define VFX_COM_BLOOD_SPARK_SMALL          237
#define VFX_COM_BLOOD_SPARK_MEDIUM         238
#define VFX_COM_BLOOD_SPARK_LARGE          239
#define VFX_DUR_GHOSTLY_PULSE              240
#define VFX_FNF_HORRID_WILTING             241
#define VFX_DUR_BLINDVISION                242
#define VFX_DUR_LOWLIGHTVISION             243
#define VFX_DUR_ULTRAVISION                244
#define VFX_DUR_MIRV_ACID                  245
#define VFX_IMP_HARM                       246
#define VFX_DUR_BLIND                      247
#define VFX_DUR_ANTI_LIGHT_10              248
#define VFX_DUR_MAGIC_RESISTANCE           249
#define VFX_IMP_MAGIC_RESISTANCE_USE       250
#define VFX_IMP_GLOBE_USE                  251
#define VFX_IMP_WILL_SAVING_THROW_USE      252
#define VFX_IMP_SPIKE_TRAP                 253
#define VFX_IMP_SPELL_MANTLE_USE           254
#define VFX_IMP_FORTITUDE_SAVING_THROW_USE 255
#define VFX_IMP_REFLEX_SAVE_THROW_USE      256
#define VFX_FNF_GAS_EXPLOSION_ACID         257
#define VFX_FNF_GAS_EXPLOSION_EVIL         258
#define VFX_FNF_GAS_EXPLOSION_NATURE       259
#define VFX_FNF_GAS_EXPLOSION_FIRE         260
#define VFX_FNF_GAS_EXPLOSION_GREASE       261
#define VFX_FNF_GAS_EXPLOSION_MIND         262
#define VFX_FNF_SMOKE_PUFF                 263
#define VFX_IMP_PULSE_WATER                264
#define VFX_IMP_PULSE_WIND                 265
#define VFX_IMP_PULSE_NATURE               266
#define VFX_DUR_AURA_COLD                  267
#define VFX_DUR_AURA_FIRE                  268
#define VFX_DUR_AURA_POISON                269
#define VFX_DUR_AURA_DISEASE               270
#define VFX_DUR_AURA_ODD                   271
#define VFX_DUR_AURA_SILENCE               272
#define VFX_DUR_AURA_HOLY                  273
#define VFX_IMP_AURA_HOLY                  273
#define VFX_DUR_AURA_UNEARTHLY             274
#define VFX_IMP_AURA_UNEARTHLY             274
#define VFX_DUR_AURA_FEAR                  275
#define VFX_IMP_AURA_FEAR                  275
#define VFX_DUR_AURA_NEGATIVE_ENERGY       276
#define VFX_IMP_AURA_NEGATIVE_ENERGY       276
#define VFX_DUR_BARD_SONG                  277
#define VFX_FNF_HOWL_MIND                  278
#define VFX_FNF_HOWL_ODD                   279
#define VFX_COM_HIT_FIRE                   280
#define VFX_COM_HIT_FROST                  281
#define VFX_COM_HIT_ELECTRICAL             282
#define VFX_COM_HIT_ACID                   283
#define VFX_COM_HIT_SONIC                  284
#define VFX_FNF_HOWL_WAR_CRY               285
#define VFX_FNF_SCREEN_SHAKE               286
#define VFX_FNF_SCREEN_BUMP                287
#define VFX_COM_HIT_NEGATIVE               288
#define VFX_COM_HIT_DIVINE                 289
#define VFX_FNF_HOWL_WAR_CRY_FEMALE        290
#define VFX_DUR_AURA_DRAGON_FEAR           291
#define VFX_FNF_SPELL_FAIL_HEAD            292
#define VFX_FNF_SPELL_FAIL_HAND            293
#define VFX_IMP_DESTRUCTION_LOW            302
#define VFX_DUR_FLAG_RED                   303
#define VFX_DUR_FLAG_BLUE                  304
#define VFX_DUR_FLAG_GOLD                  305
#define VFX_DUR_FLAG_PURPLE                306
#define VFX_BEAM_SILENT_LIGHTNING          307
#define VFX_BEAM_SILENT_FIRE               308
#define VFX_BEAM_SILENT_COLD               309
#define VFX_BEAM_SILENT_HOLY               310
#define VFX_BEAM_SILENT_MIND               311
#define VFX_BEAM_SILENT_EVIL               312
#define VFX_BEAM_SILENT_ODD                313
#define VFX_DUR_BIGBYS_INTERPOSING_HAND    314
#define VFX_IMP_BIGBYS_FORCEFUL_HAND       315
#define VFX_DUR_BIGBYS_CLENCHED_FIST       316
#define VFX_DUR_BIGBYS_CRUSHING_HAND       317
#define VFX_DUR_BIGBYS_GRASPING_HAND       318
#define VFX_DUR_CALTROPS                   319
#define VFX_DUR_SMOKE                      320
#define VFX_DUR_PIXIEDUST                  321
#define VFX_FNF_DECK                       322
#define VFX_DUR_TENTACLE                   346
#define VFX_DUR_PETRIFY                    351
#define VFX_DUR_FREEZE_ANIMATION           352
#define VFX_COM_CHUNK_STONE_SMALL          353
#define VFX_COM_CHUNK_STONE_MEDIUM         354
#define VFX_DUR_CUTSCENE_INVISIBILITY      355
#define VFX_FNF_SCREEN_SHAKE2              356
#define VFX_IMP_MIRV_ARROW                 357
#define VFX_IMP_MIRV_DART                  359
#define VFX_DUR_IOUNSTONE                  403
#define VFX_IMP_TORNADO                    407
#define VFX_DUR_GLOW_LIGHT_BLUE            408
#define VFX_DUR_GLOW_PURPLE                409
#define VFX_DUR_GLOW_BLUE                  410
#define VFX_DUR_GLOW_RED                   411
#define VFX_DUR_GLOW_LIGHT_RED             412
#define VFX_DUR_GLOW_YELLOW                413
#define VFX_DUR_GLOW_LIGHT_YELLOW          414
#define VFX_DUR_GLOW_GREEN                 415
#define VFX_DUR_GLOW_LIGHT_GREEN           416
#define VFX_DUR_GLOW_ORANGE                417
#define VFX_DUR_GLOW_LIGHT_ORANGE          418
#define VFX_DUR_GLOW_BROWN                 419
#define VFX_DUR_GLOW_LIGHT_BROWN           420
#define VFX_DUR_GLOW_GREY                  421
#define VFX_DUR_GLOW_WHITE                 422
#define VFX_DUR_GLOW_LIGHT_PURPLE          423
#define VFX_DUR_GHOST_TRANSPARENT          424
#define VFX_DUR_GHOST_SMOKE                425
#define VFX_BEAM_FLAME                     444
#define VFX_DUR_GLYPH_OF_WARDING           445
#define VFX_FNF_SOUND_BURST_SILENT         446
#define VFX_BEAM_DISINTEGRATE              447
#define VFX_DUR_ACID_SHEATH                448
#define VFX_FNF_ELECTRIC_EXPLOSION         459
#define VFX_IMP_DUST_EXPLOSION             460
#define VFX_IMP_PULSE_HOLY_SILENT          461
#define VFX_DUR_DEATH_ARMOR                463
#define VFX_FNF_HELLBALL                   464
#define VFX_DUR_ICESKIN                    465
#define VFX_CONJ_MIND                      466
#define VFX_CONJ_FIRE                      467
#define VFX_DUR_BARD_SONG_SILENT           468
#define VFX_IMP_PULSE_BOMB                 469
#define VFX_FNF_SWINGING_BLADE             473
#define VFX_DUR_INFERNO                    474
#define VFX_FNF_DEMON_HAND                 475
#define VFX_DUR_STONEHOLD                  476
#define VFX_FNF_MYSTICAL_EXPLOSION         477
#define VFX_DUR_GHOSTLY_VISAGE_NO_SOUND    478
#define VFX_DUR_GHOST_SMOKE_2              479
#define VFX_DUR_FLIES                      480
#define VFX_FNF_SUMMONDRAGON               481
#define VFX_BEAM_FIRE_W                    482
#define VFX_BEAM_FIRE_W_SILENT             483
#define VFX_BEAM_CHAIN                     484
#define VFX_BEAM_BLACK                     485
#define VFX_IMP_WALLSPIKE                  486
#define VFX_FNF_GREATER_RUIN               487
#define VFX_FNF_UNDEAD_DRAGON              488
#define VFX_DUR_CONECOLD_HEAD              490
#define VFX_COM_BLOOD_CRT_RED_HEAD         491
#define VFX_COM_BLOOD_CRT_GREEN_HEAD       492
#define VFX_COM_BLOOD_CRT_YELLOW_HEAD      493
#define VFX_FNF_DRAGBREATHGROUND           494
#define VFX_DUR_PROT_EPIC_ARMOR            495
#define VFX_FNF_SUMMON_EPIC_UNDEAD         496
#define VFX_DUR_PROT_EPIC_ARMOR_2          497
#define VFX_DUR_INFERNO_CHEST              498
#define VFX_DUR_IOUNSTONE_RED              499
#define VFX_DUR_IOUNSTONE_BLUE             500
#define VFX_DUR_IOUNSTONE_YELLOW           501
#define VFX_DUR_IOUNSTONE_GREEN            502
#define VFX_IMP_MIRV_ELECTRIC              503
#define VFX_COM_CHUNK_RED_BALLISTA         504
#define VFX_DUR_INFERNO_NO_SOUND           505
#define VFX_DUR_BARD_SONG_EVIL             507
#define VFX_DUR_AURA_PULSE_RED_WHITE       512
#define VFX_DUR_AURA_PULSE_BLUE_WHITE      513
#define VFX_DUR_AURA_PULSE_GREEN_WHITE     514
#define VFX_DUR_AURA_PULSE_YELLOW_WHITE    515
#define VFX_DUR_AURA_PULSE_MAGENTA_WHITE   516
#define VFX_DUR_AURA_PULSE_CYAN_WHITE      517
#define VFX_DUR_AURA_PULSE_ORANGE_WHITE    518
#define VFX_DUR_AURA_PULSE_BROWN_WHITE     519
#define VFX_DUR_AURA_PULSE_PURPLE_WHITE    520
#define VFX_DUR_AURA_PULSE_GREY_WHITE      521
#define VFX_DUR_AURA_PULSE_GREY_BLACK      522
#define VFX_DUR_AURA_PULSE_BLUE_GREEN      523
#define VFX_DUR_AURA_PULSE_RED_BLUE        524
#define VFX_DUR_AURA_PULSE_RED_YELLOW      525
#define VFX_DUR_AURA_PULSE_GREEN_YELLOW    526
#define VFX_DUR_AURA_PULSE_RED_GREEN       527
#define VFX_DUR_AURA_PULSE_BLUE_YELLOW     528
#define VFX_DUR_AURA_PULSE_BLUE_BLACK      529
#define VFX_DUR_AURA_PULSE_RED_BLACK       530
#define VFX_DUR_AURA_PULSE_GREEN_BLACK     531
#define VFX_DUR_AURA_PULSE_YELLOW_BLACK    532
#define VFX_DUR_AURA_PULSE_MAGENTA_BLACK   533
#define VFX_DUR_AURA_PULSE_CYAN_BLACK      534
#define VFX_DUR_AURA_PULSE_ORANGE_BLACK    535
#define VFX_DUR_AURA_PULSE_BROWN_BLACK     536
#define VFX_DUR_AURA_PULSE_PURPLE_BLACK    537
#define VFX_DUR_AURA_PULSE_CYAN_GREEN      538
#define VFX_DUR_AURA_PULSE_CYAN_BLUE       539
#define VFX_DUR_AURA_PULSE_CYAN_RED        540
#define VFX_DUR_AURA_PULSE_CYAN_YELLOW     541
#define VFX_DUR_AURA_PULSE_MAGENTA_BLUE    542
#define VFX_DUR_AURA_PULSE_MAGENTA_RED     543
#define VFX_DUR_AURA_PULSE_MAGENTA_GREEN   544
#define VFX_DUR_AURA_PULSE_MAGENTA_YELLOW  545
#define VFX_DUR_AURA_PULSE_RED_ORANGE      546
#define VFX_DUR_AURA_PULSE_YELLOW_ORANGE   547
#define VFX_DUR_AURA_RED                   548
#define VFX_DUR_AURA_GREEN                 549
#define VFX_DUR_AURA_BLUE                  550
#define VFX_DUR_AURA_MAGENTA               551
#define VFX_DUR_AURA_YELLOW                552
#define VFX_DUR_AURA_WHITE                 553
#define VFX_DUR_AURA_ORANGE                554
#define VFX_DUR_AURA_BROWN                 555
#define VFX_DUR_AURA_PURPLE                556
#define VFX_DUR_AURA_CYAN                  557
#define VFX_DUR_AURA_GREEN_DARK            558
#define VFX_DUR_AURA_GREEN_LIGHT           559
#define VFX_DUR_AURA_RED_DARK              560
#define VFX_DUR_AURA_RED_LIGHT             561
#define VFX_DUR_AURA_BLUE_DARK             562
#define VFX_DUR_AURA_BLUE_LIGHT            563
#define VFX_DUR_AURA_YELLOW_DARK           564
#define VFX_DUR_AURA_YELLOW_LIGHT          565
#define VFX_DUR_BUBBLES                    566
#define VFX_EYES_GREEN_HUMAN_MALE          567
#define VFX_EYES_GREEN_HUMAN_FEMALE        568
#define VFX_EYES_GREEN_DWARF_MALE          569
#define VFX_EYES_GREEN_DWARF_FEMALE        570
#define VFX_EYES_GREEN_ELF_MALE            571
#define VFX_EYES_GREEN_ELF_FEMALE          572
#define VFX_EYES_GREEN_GNOME_MALE          573
#define VFX_EYES_GREEN_GNOME_FEMALE        574
#define VFX_EYES_GREEN_HALFLING_MALE       575
#define VFX_EYES_GREEN_HALFLING_FEMALE     576
#define VFX_EYES_GREEN_HALFORC_MALE        577
#define VFX_EYES_GREEN_HALFORC_FEMALE      578
#define VFX_EYES_GREEN_TROGLODYTE          579

#endif /* _NX_NWN_CONST_VFX_H_ */

/* vim: set sw=4: */
