/*
 *  NWNeXalt - Empty File
 *  (c) 2007 Doug Swarin (zac@#defineertex.net)
 *
 *  This program is free software you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *  $Id$
 *  $HeadURL$
 *
 */

#ifndef _NX_NWN_CONST_FEATS_H_
#define _NX_NWN_CONST_FEATS_H_

#define FEAT_ALERTNESS                                     0    /* FEAT_0000 */
#define FEAT_AMBIDEXTERITY                                 1    /* FEAT_0001 */
#define FEAT_ARMOR_PROFICIENCY_HEAVY                       2    /* FEAT_0002 */
#define FEAT_ARMOR_PROFICIENCY_LIGHT                       3    /* FEAT_0003 */
#define FEAT_ARMOR_PROFICIENCY_MEDIUM                      4    /* FEAT_0004 */
#define FEAT_CALLED_SHOT                                   5    /* FEAT_0005 */
#define FEAT_CLEAVE                                        6    /* FEAT_0006 */
#define FEAT_COMBAT_CASTING                                7    /* FEAT_0007 */
#define FEAT_DEFLECT_ARROWS                                8    /* FEAT_0008 */
#define FEAT_DISARM                                        9    /* FEAT_0009 */
#define FEAT_DODGE                                        10    /* FEAT_000A */
#define FEAT_EMPOWER_SPELL                                11    /* FEAT_000B */
#define FEAT_EXTEND_SPELL                                 12    /* FEAT_000C */
#define FEAT_EXTRA_TURNING                                13    /* FEAT_000D */
#define FEAT_GREAT_FORTITUDE                              14    /* FEAT_000E */
#define FEAT_IMPROVED_CRITICAL_CLUB                       15    /* FEAT_000F */
#define FEAT_IMPROVED_DISARM                              16    /* FEAT_0010 */
#define FEAT_IMPROVED_KNOCKDOWN                           17    /* FEAT_0011 */
#define FEAT_IMPROVED_PARRY                               18    /* FEAT_0012 */
#define FEAT_IMPROVED_POWER_ATTACK                        19    /* FEAT_0013 */
#define FEAT_IMPROVED_TWO_WEAPON_FIGHTING                 20    /* FEAT_0014 */
#define FEAT_IMPROVED_UNARMED_STRIKE                      21    /* FEAT_0015 */
#define FEAT_IRON_WILL                                    22    /* FEAT_0016 */
#define FEAT_KNOCKDOWN                                    23    /* FEAT_0017 */
#define FEAT_LIGHTNING_REFLEXES                           24    /* FEAT_0018 */
#define FEAT_MAXIMIZE_SPELL                               25    /* FEAT_0019 */
#define FEAT_MOBILITY                                     26    /* FEAT_001A */
#define FEAT_POINT_BLANK_SHOT                             27    /* FEAT_001B */
#define FEAT_POWER_ATTACK                                 28    /* FEAT_001C */
#define FEAT_QUICKEN_SPELL                                29    /* FEAT_001D */
#define FEAT_RAPID_SHOT                                   30    /* FEAT_001E */
#define FEAT_SAP                                          31    /* FEAT_001F */
#define FEAT_SHIELD_PROFICIENCY                           32    /* FEAT_0020 */
#define FEAT_SILENCE_SPELL                                33    /* FEAT_0021 */
#define FEAT_SKILL_FOCUS_ANIMAL_EMPATHY                   34    /* FEAT_0022 */
#define FEAT_SPELL_FOCUS_ABJURATION                       35    /* FEAT_0023 */
#define FEAT_SPELL_PENETRATION                            36    /* FEAT_0024 */
#define FEAT_STILL_SPELL                                  37    /* FEAT_0025 */
#define FEAT_STUNNING_FIST                                39    /* FEAT_0027 */
#define FEAT_TOUGHNESS                                    40    /* FEAT_0028 */
#define FEAT_TWO_WEAPON_FIGHTING                          41    /* FEAT_0029 */
#define FEAT_WEAPON_FINESSE                               42    /* FEAT_002A */
#define FEAT_WEAPON_FOCUS_CLUB                            43    /* FEAT_002B */
#define FEAT_WEAPON_PROFICIENCY_EXOTIC                    44    /* FEAT_002C */
#define FEAT_WEAPON_PROFICIENCY_MARTIAL                   45    /* FEAT_002D */
#define FEAT_WEAPON_PROFICIENCY_SIMPLE                    46    /* FEAT_002E */
#define FEAT_WEAPON_SPECIALIZATION_CLUB                   47    /* FEAT_002F */
#define FEAT_WEAPON_PROFICIENCY_DRUID                     48    /* FEAT_0030 */
#define FEAT_WEAPON_PROFICIENCY_MONK                      49    /* FEAT_0031 */
#define FEAT_WEAPON_PROFICIENCY_ROGUE                     50    /* FEAT_0032 */
#define FEAT_WEAPON_PROFICIENCY_WIZARD                    51    /* FEAT_0033 */
#define FEAT_IMPROVED_CRITICAL_DAGGER                     52    /* FEAT_0034 */
#define FEAT_IMPROVED_CRITICAL_DART                       53    /* FEAT_0035 */
#define FEAT_IMPROVED_CRITICAL_HEAVY_CROSSBOW             54    /* FEAT_0036 */
#define FEAT_IMPROVED_CRITICAL_LIGHT_CROSSBOW             55    /* FEAT_0037 */
#define FEAT_IMPROVED_CRITICAL_LIGHT_MACE                 56    /* FEAT_0038 */
#define FEAT_IMPROVED_CRITICAL_MORNING_STAR               57    /* FEAT_0039 */
#define FEAT_IMPROVED_CRITICAL_STAFF                      58    /* FEAT_003A */
#define FEAT_IMPROVED_CRITICAL_SPEAR                      59    /* FEAT_003B */
#define FEAT_IMPROVED_CRITICAL_SICKLE                     60    /* FEAT_003C */
#define FEAT_IMPROVED_CRITICAL_SLING                      61    /* FEAT_003D */
#define FEAT_IMPROVED_CRITICAL_UNARMED_STRIKE             62    /* FEAT_003E */
#define FEAT_IMPROVED_CRITICAL_LONGBOW                    63    /* FEAT_003F */
#define FEAT_IMPROVED_CRITICAL_SHORTBOW                   64    /* FEAT_0040 */
#define FEAT_IMPROVED_CRITICAL_SHORT_SWORD                65    /* FEAT_0041 */
#define FEAT_IMPROVED_CRITICAL_RAPIER                     66    /* FEAT_0042 */
#define FEAT_IMPROVED_CRITICAL_SCIMITAR                   67    /* FEAT_0043 */
#define FEAT_IMPROVED_CRITICAL_LONG_SWORD                 68    /* FEAT_0044 */
#define FEAT_IMPROVED_CRITICAL_GREAT_SWORD                69    /* FEAT_0045 */
#define FEAT_IMPROVED_CRITICAL_HAND_AXE                   70    /* FEAT_0046 */
#define FEAT_IMPROVED_CRITICAL_THROWING_AXE               71    /* FEAT_0047 */
#define FEAT_IMPROVED_CRITICAL_BATTLE_AXE                 72    /* FEAT_0048 */
#define FEAT_IMPROVED_CRITICAL_GREAT_AXE                  73    /* FEAT_0049 */
#define FEAT_IMPROVED_CRITICAL_HALBERD                    74    /* FEAT_004A */
#define FEAT_IMPROVED_CRITICAL_LIGHT_HAMMER               75    /* FEAT_004B */
#define FEAT_IMPROVED_CRITICAL_LIGHT_FLAIL                76    /* FEAT_004C */
#define FEAT_IMPROVED_CRITICAL_WAR_HAMMER                 77    /* FEAT_004D */
#define FEAT_IMPROVED_CRITICAL_HEAVY_FLAIL                78    /* FEAT_004E */
#define FEAT_IMPROVED_CRITICAL_KAMA                       79    /* FEAT_004F */
#define FEAT_IMPROVED_CRITICAL_KUKRI                      80    /* FEAT_0050 */
#define FEAT_IMPROVED_CRITICAL_SHURIKEN                   82    /* FEAT_0052 */
#define FEAT_IMPROVED_CRITICAL_SCYTHE                     83    /* FEAT_0053 */
#define FEAT_IMPROVED_CRITICAL_KATANA                     84    /* FEAT_0054 */
#define FEAT_IMPROVED_CRITICAL_BASTARD_SWORD              85    /* FEAT_0055 */
#define FEAT_IMPROVED_CRITICAL_DIRE_MACE                  87    /* FEAT_0057 */
#define FEAT_IMPROVED_CRITICAL_DOUBLE_AXE                 88    /* FEAT_0058 */
#define FEAT_IMPROVED_CRITICAL_TWO_BLADED_SWORD           89    /* FEAT_0059 */
#define FEAT_WEAPON_FOCUS_DAGGER                          90    /* FEAT_005A */
#define FEAT_WEAPON_FOCUS_DART                            91    /* FEAT_005B */
#define FEAT_WEAPON_FOCUS_HEAVY_CROSSBOW                  92    /* FEAT_005C */
#define FEAT_WEAPON_FOCUS_LIGHT_CROSSBOW                  93    /* FEAT_005D */
#define FEAT_WEAPON_FOCUS_LIGHT_MACE                      94    /* FEAT_005E */
#define FEAT_WEAPON_FOCUS_MORNING_STAR                    95    /* FEAT_005F */
#define FEAT_WEAPON_FOCUS_STAFF                           96    /* FEAT_0060 */
#define FEAT_WEAPON_FOCUS_SPEAR                           97    /* FEAT_0061 */
#define FEAT_WEAPON_FOCUS_SICKLE                          98    /* FEAT_0062 */
#define FEAT_WEAPON_FOCUS_SLING                           99    /* FEAT_0063 */
#define FEAT_WEAPON_FOCUS_UNARMED_STRIKE                 100    /* FEAT_0064 */
#define FEAT_WEAPON_FOCUS_LONGBOW                        101    /* FEAT_0065 */
#define FEAT_WEAPON_FOCUS_SHORTBOW                       102    /* FEAT_0066 */
#define FEAT_WEAPON_FOCUS_SHORT_SWORD                    103    /* FEAT_0067 */
#define FEAT_WEAPON_FOCUS_RAPIER                         104    /* FEAT_0068 */
#define FEAT_WEAPON_FOCUS_SCIMITAR                       105    /* FEAT_0069 */
#define FEAT_WEAPON_FOCUS_LONG_SWORD                     106    /* FEAT_006A */
#define FEAT_WEAPON_FOCUS_GREAT_SWORD                    107    /* FEAT_006B */
#define FEAT_WEAPON_FOCUS_HAND_AXE                       108    /* FEAT_006C */
#define FEAT_WEAPON_FOCUS_THROWING_AXE                   109    /* FEAT_006D */
#define FEAT_WEAPON_FOCUS_BATTLE_AXE                     110    /* FEAT_006E */
#define FEAT_WEAPON_FOCUS_GREAT_AXE                      111    /* FEAT_006F */
#define FEAT_WEAPON_FOCUS_HALBERD                        112    /* FEAT_0070 */
#define FEAT_WEAPON_FOCUS_LIGHT_HAMMER                   113    /* FEAT_0071 */
#define FEAT_WEAPON_FOCUS_LIGHT_FLAIL                    114    /* FEAT_0072 */
#define FEAT_WEAPON_FOCUS_WAR_HAMMER                     115    /* FEAT_0073 */
#define FEAT_WEAPON_FOCUS_HEAVY_FLAIL                    116    /* FEAT_0074 */
#define FEAT_WEAPON_FOCUS_KAMA                           117    /* FEAT_0075 */
#define FEAT_WEAPON_FOCUS_KUKRI                          118    /* FEAT_0076 */
#define FEAT_WEAPON_FOCUS_SHURIKEN                       120    /* FEAT_0078 */
#define FEAT_WEAPON_FOCUS_SCYTHE                         121    /* FEAT_0079 */
#define FEAT_WEAPON_FOCUS_KATANA                         122    /* FEAT_007A */
#define FEAT_WEAPON_FOCUS_BASTARD_SWORD                  123    /* FEAT_007B */
#define FEAT_WEAPON_FOCUS_DIRE_MACE                      125    /* FEAT_007D */
#define FEAT_WEAPON_FOCUS_DOUBLE_AXE                     126    /* FEAT_007E */
#define FEAT_WEAPON_FOCUS_TWO_BLADED_SWORD               127    /* FEAT_007F */
#define FEAT_WEAPON_SPECIALIZATION_DAGGER                128    /* FEAT_0080 */
#define FEAT_WEAPON_SPECIALIZATION_DART                  129    /* FEAT_0081 */
#define FEAT_WEAPON_SPECIALIZATION_HEAVY_CROSSBOW        130    /* FEAT_0082 */
#define FEAT_WEAPON_SPECIALIZATION_LIGHT_CROSSBOW        131    /* FEAT_0083 */
#define FEAT_WEAPON_SPECIALIZATION_LIGHT_MACE            132    /* FEAT_0084 */
#define FEAT_WEAPON_SPECIALIZATION_MORNING_STAR          133    /* FEAT_0085 */
#define FEAT_WEAPON_SPECIALIZATION_STAFF                 134    /* FEAT_0086 */
#define FEAT_WEAPON_SPECIALIZATION_SPEAR                 135    /* FEAT_0087 */
#define FEAT_WEAPON_SPECIALIZATION_SICKLE                136    /* FEAT_0088 */
#define FEAT_WEAPON_SPECIALIZATION_SLING                 137    /* FEAT_0089 */
#define FEAT_WEAPON_SPECIALIZATION_UNARMED_STRIKE        138    /* FEAT_008A */
#define FEAT_WEAPON_SPECIALIZATION_LONGBOW               139    /* FEAT_008B */
#define FEAT_WEAPON_SPECIALIZATION_SHORTBOW              140    /* FEAT_008C */
#define FEAT_WEAPON_SPECIALIZATION_SHORT_SWORD           141    /* FEAT_008D */
#define FEAT_WEAPON_SPECIALIZATION_RAPIER                142    /* FEAT_008E */
#define FEAT_WEAPON_SPECIALIZATION_SCIMITAR              143    /* FEAT_008F */
#define FEAT_WEAPON_SPECIALIZATION_LONG_SWORD            144    /* FEAT_0090 */
#define FEAT_WEAPON_SPECIALIZATION_GREAT_SWORD           145    /* FEAT_0091 */
#define FEAT_WEAPON_SPECIALIZATION_HAND_AXE              146    /* FEAT_0092 */
#define FEAT_WEAPON_SPECIALIZATION_THROWING_AXE          147    /* FEAT_0093 */
#define FEAT_WEAPON_SPECIALIZATION_BATTLE_AXE            148    /* FEAT_0094 */
#define FEAT_WEAPON_SPECIALIZATION_GREAT_AXE             149    /* FEAT_0095 */
#define FEAT_WEAPON_SPECIALIZATION_HALBERD               150    /* FEAT_0096 */
#define FEAT_WEAPON_SPECIALIZATION_LIGHT_HAMMER          151    /* FEAT_0097 */
#define FEAT_WEAPON_SPECIALIZATION_LIGHT_FLAIL           152    /* FEAT_0098 */
#define FEAT_WEAPON_SPECIALIZATION_WAR_HAMMER            153    /* FEAT_0099 */
#define FEAT_WEAPON_SPECIALIZATION_HEAVY_FLAIL           154    /* FEAT_009A */
#define FEAT_WEAPON_SPECIALIZATION_KAMA                  155    /* FEAT_009B */
#define FEAT_WEAPON_SPECIALIZATION_KUKRI                 156    /* FEAT_009C */
#define FEAT_WEAPON_SPECIALIZATION_SHURIKEN              158    /* FEAT_009E */
#define FEAT_WEAPON_SPECIALIZATION_SCYTHE                159    /* FEAT_009F */
#define FEAT_WEAPON_SPECIALIZATION_KATANA                160    /* FEAT_00A0 */
#define FEAT_WEAPON_SPECIALIZATION_BASTARD_SWORD         161    /* FEAT_00A1 */
#define FEAT_WEAPON_SPECIALIZATION_DIRE_MACE             163    /* FEAT_00A3 */
#define FEAT_WEAPON_SPECIALIZATION_DOUBLE_AXE            164    /* FEAT_00A4 */
#define FEAT_WEAPON_SPECIALIZATION_TWO_BLADED_SWORD      165    /* FEAT_00A5 */
#define FEAT_SPELL_FOCUS_CONJURATION                     166    /* FEAT_00A6 */
#define FEAT_SPELL_FOCUS_DIVINATION                      167    /* FEAT_00A7 */
#define FEAT_SPELL_FOCUS_ENCHANTMENT                     168    /* FEAT_00A8 */
#define FEAT_SPELL_FOCUS_EVOCATION                       169    /* FEAT_00A9 */
#define FEAT_SPELL_FOCUS_ILLUSION                        170    /* FEAT_00AA */
#define FEAT_SPELL_FOCUS_NECROMANCY                      171    /* FEAT_00AB */
#define FEAT_SPELL_FOCUS_TRANSMUTATION                   172    /* FEAT_00AC */
#define FEAT_SKILL_FOCUS_CONCENTRATION                   173    /* FEAT_00AD */
#define FEAT_SKILL_FOCUS_DISABLE_TRAP                    174    /* FEAT_00AE */
#define FEAT_SKILL_FOCUS_DISCIPLINE                      175    /* FEAT_00AF */
#define FEAT_SKILL_FOCUS_HEAL                            177    /* FEAT_00B1 */
#define FEAT_SKILL_FOCUS_HIDE                            178    /* FEAT_00B2 */
#define FEAT_SKILL_FOCUS_LISTEN                          179    /* FEAT_00B3 */
#define FEAT_SKILL_FOCUS_LORE                            180    /* FEAT_00B4 */
#define FEAT_SKILL_FOCUS_MOVE_SILENTLY                   181    /* FEAT_00B5 */
#define FEAT_SKILL_FOCUS_OPEN_LOCK                       182    /* FEAT_00B6 */
#define FEAT_SKILL_FOCUS_PARRY                           183    /* FEAT_00B7 */
#define FEAT_SKILL_FOCUS_PERFORM                         184    /* FEAT_00B8 */
#define FEAT_SKILL_FOCUS_PERSUADE                        185    /* FEAT_00B9 */
#define FEAT_SKILL_FOCUS_PICK_POCKET                     186    /* FEAT_00BA */
#define FEAT_SKILL_FOCUS_SEARCH                          187    /* FEAT_00BB */
#define FEAT_SKILL_FOCUS_SET_TRAP                        188    /* FEAT_00BC */
#define FEAT_SKILL_FOCUS_SPELLCRAFT                      189    /* FEAT_00BD */
#define FEAT_SKILL_FOCUS_SPOT                            190    /* FEAT_00BE */
#define FEAT_SKILL_FOCUS_TAUNT                           192    /* FEAT_00C0 */
#define FEAT_SKILL_FOCUS_USE_MAGIC_DEVICE                193    /* FEAT_00C1 */
#define FEAT_BARBARIAN_ENDURANCE                         194    /* FEAT_00C2 */
#define FEAT_UNCANNY_DODGE_1                             195    /* FEAT_00C3 */
#define FEAT_DAMAGE_REDUCTION                            196    /* FEAT_00C4 */
#define FEAT_BARDIC_KNOWLEDGE                            197    /* FEAT_00C5 */
#define FEAT_NATURE_SENSE                                198    /* FEAT_00C6 */
#define FEAT_ANIMAL_COMPANION                            199    /* FEAT_00C7 */
#define FEAT_WOODLAND_STRIDE                             200    /* FEAT_00C8 */
#define FEAT_TRACKLESS_STEP                              201    /* FEAT_00C9 */
#define FEAT_RESIST_NATURES_LURE                         202    /* FEAT_00CA */
#define FEAT_VENOM_IMMUNITY                              203    /* FEAT_00CB */
#define FEAT_FLURRY_OF_BLOWS                             204    /* FEAT_00CC */
#define FEAT_EVASION                                     206    /* FEAT_00CE */
#define FEAT_MONK_ENDURANCE                              207    /* FEAT_00CF */
#define FEAT_STILL_MIND                                  208    /* FEAT_00D0 */
#define FEAT_PURITY_OF_BODY                              209    /* FEAT_00D1 */
#define FEAT_WHOLENESS_OF_BODY                           211    /* FEAT_00D3 */
#define FEAT_IMPROVED_EVASION                            212    /* FEAT_00D4 */
#define FEAT_KI_STRIKE                                   213    /* FEAT_00D5 */
#define FEAT_DIAMOND_BODY                                214    /* FEAT_00D6 */
#define FEAT_DIAMOND_SOUL                                215    /* FEAT_00D7 */
#define FEAT_PERFECT_SELF                                216    /* FEAT_00D8 */
#define FEAT_DIVINE_GRACE                                217    /* FEAT_00D9 */
#define FEAT_DIVINE_HEALTH                               219    /* FEAT_00DB */
#define FEAT_SNEAK_ATTACK                                221    /* FEAT_00DD */
#define FEAT_CRIPPLING_STRIKE                            222    /* FEAT_00DE */
#define FEAT_DEFENSIVE_ROLL                              223    /* FEAT_00DF */
#define FEAT_OPPORTUNIST                                 224    /* FEAT_00E0 */
#define FEAT_SKILL_MASTERY                               225    /* FEAT_00E1 */
#define FEAT_UNCANNY_REFLEX                              226    /* FEAT_00E2 */
#define FEAT_STONECUNNING                                227    /* FEAT_00E3 */
#define FEAT_DARKVISION                                  228    /* FEAT_00E4 */
#define FEAT_HARDINESS_VERSUS_POISONS                    229    /* FEAT_00E5 */
#define FEAT_HARDINESS_VERSUS_SPELLS                     230    /* FEAT_00E6 */
#define FEAT_BATTLE_TRAINING_VERSUS_ORCS                 231    /* FEAT_00E7 */
#define FEAT_BATTLE_TRAINING_VERSUS_GOBLINS              232    /* FEAT_00E8 */
#define FEAT_BATTLE_TRAINING_VERSUS_GIANTS               233    /* FEAT_00E9 */
#define FEAT_SKILL_AFFINITY_LORE                         234    /* FEAT_00EA */
#define FEAT_IMMUNITY_TO_SLEEP                           235    /* FEAT_00EB */
#define FEAT_HARDINESS_VERSUS_ENCHANTMENTS               236    /* FEAT_00EC */
#define FEAT_SKILL_AFFINITY_LISTEN                       237    /* FEAT_00ED */
#define FEAT_SKILL_AFFINITY_SEARCH                       238    /* FEAT_00EE */
#define FEAT_SKILL_AFFINITY_SPOT                         239    /* FEAT_00EF */
#define FEAT_KEEN_SENSE                                  240    /* FEAT_00F0 */
#define FEAT_HARDINESS_VERSUS_ILLUSIONS                  241    /* FEAT_00F1 */
#define FEAT_BATTLE_TRAINING_VERSUS_REPTILIANS           242    /* FEAT_00F2 */
#define FEAT_SKILL_AFFINITY_CONCENTRATION                243    /* FEAT_00F3 */
#define FEAT_PARTIAL_SKILL_AFFINITY_LISTEN               244    /* FEAT_00F4 */
#define FEAT_PARTIAL_SKILL_AFFINITY_SEARCH               245    /* FEAT_00F5 */
#define FEAT_PARTIAL_SKILL_AFFINITY_SPOT                 246    /* FEAT_00F6 */
#define FEAT_SKILL_AFFINITY_MOVE_SILENTLY                247    /* FEAT_00F7 */
#define FEAT_LUCKY                                       248    /* FEAT_00F8 */
#define FEAT_FEARLESS                                    249    /* FEAT_00F9 */
#define FEAT_GOOD_AIM                                    250    /* FEAT_00FA */
#define FEAT_UNCANNY_DODGE_2                             251    /* FEAT_00FB */
#define FEAT_UNCANNY_DODGE_3                             252    /* FEAT_00FC */
#define FEAT_UNCANNY_DODGE_4                             253    /* FEAT_00FD */
#define FEAT_UNCANNY_DODGE_5                             254    /* FEAT_00FE */
#define FEAT_UNCANNY_DODGE_6                             255    /* FEAT_00FF */
#define FEAT_WEAPON_PROFICIENCY_ELF                      256    /* FEAT_0100 */
#define FEAT_BARD_SONGS                                  257    /* FEAT_0101 */
#define FEAT_QUICK_TO_MASTER                             258    /* FEAT_0102 */
#define FEAT_SLIPPERY_MIND                               259    /* FEAT_0103 */
#define FEAT_MONK_AC_BONUS                               260    /* FEAT_0104 */
#define FEAT_FAVORED_ENEMY_DWARF                         261    /* FEAT_0105 */
#define FEAT_FAVORED_ENEMY_ELF                           262    /* FEAT_0106 */
#define FEAT_FAVORED_ENEMY_GNOME                         263    /* FEAT_0107 */
#define FEAT_FAVORED_ENEMY_HALFLING                      264    /* FEAT_0108 */
#define FEAT_FAVORED_ENEMY_HALFELF                       265    /* FEAT_0109 */
#define FEAT_FAVORED_ENEMY_HALFORC                       266    /* FEAT_010A */
#define FEAT_FAVORED_ENEMY_HUMAN                         267    /* FEAT_010B */
#define FEAT_FAVORED_ENEMY_ABERRATION                    268    /* FEAT_010C */
#define FEAT_FAVORED_ENEMY_ANIMAL                        269    /* FEAT_010D */
#define FEAT_FAVORED_ENEMY_BEAST                         270    /* FEAT_010E */
#define FEAT_FAVORED_ENEMY_CONSTRUCT                     271    /* FEAT_010F */
#define FEAT_FAVORED_ENEMY_DRAGON                        272    /* FEAT_0110 */
#define FEAT_FAVORED_ENEMY_GOBLINOID                     273    /* FEAT_0111 */
#define FEAT_FAVORED_ENEMY_MONSTROUS                     274    /* FEAT_0112 */
#define FEAT_FAVORED_ENEMY_ORC                           275    /* FEAT_0113 */
#define FEAT_FAVORED_ENEMY_REPTILIAN                     276    /* FEAT_0114 */
#define FEAT_FAVORED_ENEMY_ELEMENTAL                     277    /* FEAT_0115 */
#define FEAT_FAVORED_ENEMY_FEY                           278    /* FEAT_0116 */
#define FEAT_FAVORED_ENEMY_GIANT                         279    /* FEAT_0117 */
#define FEAT_FAVORED_ENEMY_MAGICAL_BEAST                 280    /* FEAT_0118 */
#define FEAT_FAVORED_ENEMY_OUTSIDER                      281    /* FEAT_0119 */
#define FEAT_FAVORED_ENEMY_SHAPECHANGER                  284    /* FEAT_011C */
#define FEAT_FAVORED_ENEMY_UNDEAD                        285    /* FEAT_011D */
#define FEAT_FAVORED_ENEMY_VERMIN                        286    /* FEAT_011E */
#define FEAT_WEAPON_PROFICIENCY_CREATURE                 289    /* FEAT_0121 */
#define FEAT_WEAPON_SPECIALIZATION_CREATURE              290    /* FEAT_0122 */
#define FEAT_WEAPON_FOCUS_CREATURE                       291    /* FEAT_0123 */
#define FEAT_IMPROVED_CRITICAL_CREATURE                  292    /* FEAT_0124 */
#define FEAT_BARBARIAN_RAGE                              293    /* FEAT_0125 */
#define FEAT_TURN_UNDEAD                                 294    /* FEAT_0126 */
#define FEAT_QUIVERING_PALM                              296    /* FEAT_0128 */
#define FEAT_EMPTY_BODY                                  297    /* FEAT_0129 */
#define FEAT_LAY_ON_HANDS                                299    /* FEAT_012B */
#define FEAT_AURA_OF_COURAGE                             300    /* FEAT_012C */
#define FEAT_SMITE_EVIL                                  301    /* FEAT_012D */
#define FEAT_REMOVE_DISEASE                              302    /* FEAT_012E */
#define FEAT_SUMMON_FAMILIAR                             303    /* FEAT_012F */
#define FEAT_ELEMENTAL_SHAPE                             304    /* FEAT_0130 */
#define FEAT_WILD_SHAPE                                  305    /* FEAT_0131 */
#define FEAT_WAR_DOMAIN_POWER                            306    /* FEAT_0132 */
#define FEAT_STRENGTH_DOMAIN_POWER                       307    /* FEAT_0133 */
#define FEAT_PROTECTION_DOMAIN_POWER                     308    /* FEAT_0134 */
#define FEAT_LUCK_DOMAIN_POWER                           309    /* FEAT_0135 */
#define FEAT_DEATH_DOMAIN_POWER                          310    /* FEAT_0136 */
#define FEAT_AIR_DOMAIN_POWER                            311    /* FEAT_0137 */
#define FEAT_ANIMAL_DOMAIN_POWER                         312    /* FEAT_0138 */
#define FEAT_DESTRUCTION_DOMAIN_POWER                    313    /* FEAT_0139 */
#define FEAT_EARTH_DOMAIN_POWER                          314    /* FEAT_013A */
#define FEAT_EVIL_DOMAIN_POWER                           315    /* FEAT_013B */
#define FEAT_FIRE_DOMAIN_POWER                           316    /* FEAT_013C */
#define FEAT_GOOD_DOMAIN_POWER                           317    /* FEAT_013D */
#define FEAT_HEALING_DOMAIN_POWER                        318    /* FEAT_013E */
#define FEAT_KNOWLEDGE_DOMAIN_POWER                      319    /* FEAT_013F */
#define FEAT_MAGIC_DOMAIN_POWER                          320    /* FEAT_0140 */
#define FEAT_PLANT_DOMAIN_POWER                          321    /* FEAT_0141 */
#define FEAT_SUN_DOMAIN_POWER                            322    /* FEAT_0142 */
#define FEAT_TRAVEL_DOMAIN_POWER                         323    /* FEAT_0143 */
#define FEAT_TRICKERY_DOMAIN_POWER                       324    /* FEAT_0144 */
#define FEAT_WATER_DOMAIN_POWER                          325    /* FEAT_0145 */
#define FEAT_BARBARIAN_RAGE_2                            326    /* FEAT_0146 */
#define FEAT_BARBARIAN_RAGE_3                            327    /* FEAT_0147 */
#define FEAT_BARBARIAN_RAGE_4                            328    /* FEAT_0148 */
#define FEAT_BARBARIAN_RAGE_5                            329    /* FEAT_0149 */
#define FEAT_BARBARIAN_RAGE_6                            330    /* FEAT_014A */
#define FEAT_BARBARIAN_RAGE_7                            331    /* FEAT_014B */
#define FEAT_DAMAGE_REDUCTION_2                          332    /* FEAT_014C */
#define FEAT_DAMAGE_REDUCTION_3                          333    /* FEAT_014D */
#define FEAT_DAMAGE_REDUCTION_4                          334    /* FEAT_014E */
#define FEAT_WILD_SHAPE_2                                335    /* FEAT_014F */
#define FEAT_WILD_SHAPE_3                                336    /* FEAT_0150 */
#define FEAT_WILD_SHAPE_4                                337    /* FEAT_0151 */
#define FEAT_WILD_SHAPE_5                                338    /* FEAT_0152 */
#define FEAT_WILD_SHAPE_6                                339    /* FEAT_0153 */
#define FEAT_ELEMENTAL_SHAPE_2                           340    /* FEAT_0154 */
#define FEAT_ELEMENTAL_SHAPE_3                           341    /* FEAT_0155 */
#define FEAT_ELEMENTAL_SHAPE_4                           342    /* FEAT_0156 */
#define FEAT_KI_STRIKE_2                                 343    /* FEAT_0157 */
#define FEAT_KI_STRIKE_3                                 344    /* FEAT_0158 */
#define FEAT_SNEAK_ATTACK_2                              345    /* FEAT_0159 */
#define FEAT_SNEAK_ATTACK_3                              346    /* FEAT_015A */
#define FEAT_SNEAK_ATTACK_4                              347    /* FEAT_015B */
#define FEAT_SNEAK_ATTACK_5                              348    /* FEAT_015C */
#define FEAT_SNEAK_ATTACK_6                              349    /* FEAT_015D */
#define FEAT_SNEAK_ATTACK_7                              350    /* FEAT_015E */
#define FEAT_SNEAK_ATTACK_8                              351    /* FEAT_015F */
#define FEAT_SNEAK_ATTACK_9                              352    /* FEAT_0160 */
#define FEAT_SNEAK_ATTACK_10                             353    /* FEAT_0161 */
#define FEAT_LOWLIGHTVISION                              354    /* FEAT_0162 */
#define FEAT_BARD_SONGS_2                                355    /* FEAT_0163 */
#define FEAT_BARD_SONGS_3                                356    /* FEAT_0164 */
#define FEAT_BARD_SONGS_4                                357    /* FEAT_0165 */
#define FEAT_BARD_SONGS_5                                358    /* FEAT_0166 */
#define FEAT_BARD_SONGS_6                                359    /* FEAT_0167 */
#define FEAT_BARD_SONGS_7                                360    /* FEAT_0168 */
#define FEAT_BARD_SONGS_8                                361    /* FEAT_0169 */
#define FEAT_BARD_SONGS_9                                362    /* FEAT_016A */
#define FEAT_BARD_SONGS_10                               363    /* FEAT_016B */
#define FEAT_BARD_SONGS_11                               364    /* FEAT_016C */
#define FEAT_BARD_SONGS_12                               365    /* FEAT_016D */
#define FEAT_BARD_SONGS_13                               366    /* FEAT_016E */
#define FEAT_BARD_SONGS_14                               367    /* FEAT_016F */
#define FEAT_BARD_SONGS_15                               368    /* FEAT_0170 */
#define FEAT_BARD_SONGS_16                               369    /* FEAT_0171 */
#define FEAT_BARD_SONGS_17                               370    /* FEAT_0172 */
#define FEAT_BARD_SONGS_18                               371    /* FEAT_0173 */
#define FEAT_BARD_SONGS_19                               372    /* FEAT_0174 */
#define FEAT_BARD_SONGS_20                               373    /* FEAT_0175 */
#define FEAT_RANGER_DUAL_WIELD                           374    /* FEAT_0176 */
#define FEAT_SMALL_STATURE                               375    /* FEAT_0177 */
#define FEAT_IMPROVED_INITIATIVE                         377    /* FEAT_0179 */
#define FEAT_ARTIST                                      378    /* FEAT_017A */
#define FEAT_BLOODED                                     379    /* FEAT_017B */
#define FEAT_BULLHEADED                                  380    /* FEAT_017C */
#define FEAT_COURTEOUS_MAGOCRACY                         381    /* FEAT_017D */
#define FEAT_LUCK_OF_HEROES                              382    /* FEAT_017E */
#define FEAT_RESIST_POISON                               383    /* FEAT_017F */
#define FEAT_SILVER_PALM                                 384    /* FEAT_0180 */
#define FEAT_SMOOTH_TALK                                 385    /* FEAT_0181 */
#define FEAT_SNAKE_BLOOD                                 386    /* FEAT_0182 */
#define FEAT_STEALTHY                                    387    /* FEAT_0183 */
#define FEAT_STRONG_SOUL                                 388    /* FEAT_0184 */
#define FEAT_EXPERTISE                                   389    /* FEAT_0185 */
#define FEAT_IMPROVED_EXPERTISE                          390    /* FEAT_0186 */
#define FEAT_GREAT_CLEAVE                                391    /* FEAT_0187 */
#define FEAT_SPRING_ATTACK                               392    /* FEAT_0188 */
#define FEAT_GREATER_SPELL_FOCUS_ABJURATION              393    /* FEAT_0189 */
#define FEAT_GREATER_SPELL_FOCUS_CONJURATION             394    /* FEAT_018A */
#define FEAT_GREATER_SPELL_FOCUS_DIVINATION              395    /* FEAT_018B */
#define FEAT_GREATER_SPELL_FOCUS_ENCHANTMENT             396    /* FEAT_018C */
#define FEAT_GREATER_SPELL_FOCUS_EVOCATION               397    /* FEAT_018D */
#define FEAT_GREATER_SPELL_FOCUS_ILLUSION                398    /* FEAT_018E */
#define FEAT_GREATER_SPELL_FOCUS_NECROMANCY              399    /* FEAT_018F */
#define FEAT_GREATER_SPELL_FOCUS_TRANSMUTATION           400    /* FEAT_0190 */
#define FEAT_GREATER_SPELL_PENETRATION                   401    /* FEAT_0191 */
#define FEAT_THUG                                        402    /* FEAT_0192 */
#define FEAT_MERCANTILE_BACKGROUND                       403    /* FEAT_0193 */
#define FEAT_SKILL_FOCUS_APPRAISE                        404    /* FEAT_0194 */
#define FEAT_SKILL_FOCUS_TUMBLE                          406    /* FEAT_0196 */
#define FEAT_SKILL_FOCUS_CRAFT_TRAP                      407    /* FEAT_0197 */
#define FEAT_BLIND_FIGHT                                 408    /* FEAT_0198 */
#define FEAT_CIRCLE_KICK                                 409    /* FEAT_0199 */
#define FEAT_EXTRA_STUNNING_ATTACK                       410    /* FEAT_019A */
#define FEAT_RAPID_RELOAD                                411    /* FEAT_019B */
#define FEAT_ZEN_ARCHERY                                 412    /* FEAT_019C */
#define FEAT_DIVINE_MIGHT                                413    /* FEAT_019D */
#define FEAT_DIVINE_SHIELD                               414    /* FEAT_019E */
#define FEAT_ARCANE_DEFENSE_ABJURATION                   415    /* FEAT_019F */
#define FEAT_ARCANE_DEFENSE_CONJURATION                  416    /* FEAT_01A0 */
#define FEAT_ARCANE_DEFENSE_DIVINATION                   417    /* FEAT_01A1 */
#define FEAT_ARCANE_DEFENSE_ENCHATMENT                   418    /* FEAT_01A2 */
#define FEAT_ARCANE_DEFENSE_EVOCATION                    419    /* FEAT_01A3 */
#define FEAT_ARCANE_DEFENSE_ILLUSION                     420    /* FEAT_01A4 */
#define FEAT_ARCANE_DEFENSE_NECROMANCY                   421    /* FEAT_01A5 */
#define FEAT_ARCANE_DEFENSE_TRANSMUTATION                422    /* FEAT_01A6 */
#define FEAT_EXTRA_MUSIC                                 423    /* FEAT_01A7 */
#define FEAT_LINGERING_SONG                              424    /* FEAT_01A8 */
#define FEAT_DIRTY_FIGHTING                              425    /* FEAT_01A9 */
#define FEAT_RESIST_DISEASE                              426    /* FEAT_01AA */
#define FEAT_RESIST_ENERGY_COLD                          427    /* FEAT_01AB */
#define FEAT_RESIST_ENERGY_ACID                          428    /* FEAT_01AC */
#define FEAT_RESIST_ENERGY_FIRE                          429    /* FEAT_01AD */
#define FEAT_RESIST_ENERGY_ELECTRICAL                    430    /* FEAT_01AE */
#define FEAT_RESIST_ENERGY_SONIC                         431    /* FEAT_01AF */
#define FEAT_HIDE_IN_PLAIN_SIGHT                         433    /* FEAT_01B1 */
#define FEAT_SHADOW_DAZE                                 434    /* FEAT_01B2 */
#define FEAT_SUMMON_SHADOW                               435    /* FEAT_01B3 */
#define FEAT_SHADOW_EVADE                                436    /* FEAT_01B4 */
#define FEAT_DENEIRS_EYE                                 437    /* FEAT_01B5 */
#define FEAT_TYMORAS_SMILE                               438    /* FEAT_01B6 */
#define FEAT_LLIIRAS_HEART                               439    /* FEAT_01B7 */
#define FEAT_CRAFT_HARPER_ITEM                           440    /* FEAT_01B8 */
#define FEAT_HARPER_SLEEP                                441    /* FEAT_01B9 */
#define FEAT_HARPER_CATS_GRACE                           442    /* FEAT_01BA */
#define FEAT_HARPER_EAGLES_SPLENDOR                      443    /* FEAT_01BB */
#define FEAT_HARPER_INVISIBILITY                         444    /* FEAT_01BC */
#define FEAT_PRESTIGE_ENCHANT_ARROW_1                    445    /* FEAT_01BD */
#define FEAT_PRESTIGE_ENCHANT_ARROW_2                    446    /* FEAT_01BE */
#define FEAT_PRESTIGE_ENCHANT_ARROW_3                    447    /* FEAT_01BF */
#define FEAT_PRESTIGE_ENCHANT_ARROW_4                    448    /* FEAT_01C0 */
#define FEAT_PRESTIGE_ENCHANT_ARROW_5                    449    /* FEAT_01C1 */
#define FEAT_PRESTIGE_EMBUE_ARROW                        450    /* FEAT_01C2 */
#define FEAT_PRESTIGE_SEEKER_ARROW_1                     451    /* FEAT_01C3 */
#define FEAT_PRESTIGE_SEEKER_ARROW_2                     452    /* FEAT_01C4 */
#define FEAT_PRESTIGE_HAIL_OF_ARROWS                     453    /* FEAT_01C5 */
#define FEAT_PRESTIGE_ARROW_OF_DEATH                     454    /* FEAT_01C6 */
#define FEAT_PRESTIGE_DEATH_ATTACK_1                     455    /* FEAT_01C7 */
#define FEAT_PRESTIGE_DEATH_ATTACK_2                     456    /* FEAT_01C8 */
#define FEAT_PRESTIGE_DEATH_ATTACK_3                     457    /* FEAT_01C9 */
#define FEAT_PRESTIGE_DEATH_ATTACK_4                     458    /* FEAT_01CA */
#define FEAT_PRESTIGE_DEATH_ATTACK_5                     459    /* FEAT_01CB */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_1D6                 460    /* FEAT_01CC */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_2D6                 461    /* FEAT_01CD */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_3D6                 462    /* FEAT_01CE */
#define FEAT_PRESTIGE_POISON_SAVE_1                      463    /* FEAT_01CF */
#define FEAT_PRESTIGE_POISON_SAVE_2                      464    /* FEAT_01D0 */
#define FEAT_PRESTIGE_POISON_SAVE_3                      465    /* FEAT_01D1 */
#define FEAT_PRESTIGE_POISON_SAVE_4                      466    /* FEAT_01D2 */
#define FEAT_PRESTIGE_POISON_SAVE_5                      467    /* FEAT_01D3 */
#define FEAT_PRESTIGE_SPELL_GHOSTLY_VISAGE               468    /* FEAT_01D4 */
#define FEAT_PRESTIGE_DARKNESS                           469    /* FEAT_01D5 */
#define FEAT_PRESTIGE_INVISIBILITY_1                     470    /* FEAT_01D6 */
#define FEAT_PRESTIGE_INVISIBILITY_2                     471    /* FEAT_01D7 */
#define FEAT_SMITE_GOOD                                  472    /* FEAT_01D8 */
#define FEAT_PRESTIGE_DARK_BLESSING                      473    /* FEAT_01D9 */
#define FEAT_INFLICT_LIGHT_WOUNDS                        474    /* FEAT_01DA */
#define FEAT_INFLICT_MODERATE_WOUNDS                     475    /* FEAT_01DB */
#define FEAT_INFLICT_SERIOUS_WOUNDS                      476    /* FEAT_01DC */
#define FEAT_INFLICT_CRITICAL_WOUNDS                     477    /* FEAT_01DD */
#define FEAT_BULLS_STRENGTH                              478    /* FEAT_01DE */
#define FEAT_CONTAGION                                   479    /* FEAT_01DF */
#define FEAT_BLINDSIGHT_60_FEET                          488    /* FEAT_01E8 */
#define FEAT_EPIC_ARMOR_SKIN                             490    /* FEAT_01EA */
#define FEAT_EPIC_BLINDING_SPEED                         491    /* FEAT_01EB */
#define FEAT_EPIC_DAMAGE_REDUCTION_3                     492    /* FEAT_01EC */
#define FEAT_EPIC_DAMAGE_REDUCTION_6                     493    /* FEAT_01ED */
#define FEAT_EPIC_DAMAGE_REDUCTION_9                     494    /* FEAT_01EE */
#define FEAT_EPIC_DEVASTATING_CRITICAL_CLUB              495    /* FEAT_01EF */
#define FEAT_EPIC_DEVASTATING_CRITICAL_DAGGER            496    /* FEAT_01F0 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_DART              497    /* FEAT_01F1 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_HEAVYCROSSBOW     498    /* FEAT_01F2 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_LIGHTCROSSBOW     499    /* FEAT_01F3 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_LIGHTMACE         500    /* FEAT_01F4 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_MORNINGSTAR       501    /* FEAT_01F5 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_QUARTERSTAFF      502    /* FEAT_01F6 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_SHORTSPEAR        503    /* FEAT_01F7 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_SICKLE            504    /* FEAT_01F8 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_SLING             505    /* FEAT_01F9 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_UNARMED           506    /* FEAT_01FA */
#define FEAT_EPIC_DEVASTATING_CRITICAL_LONGBOW           507    /* FEAT_01FB */
#define FEAT_EPIC_DEVASTATING_CRITICAL_SHORTBOW          508    /* FEAT_01FC */
#define FEAT_EPIC_DEVASTATING_CRITICAL_SHORTSWORD        509    /* FEAT_01FD */
#define FEAT_EPIC_DEVASTATING_CRITICAL_RAPIER            510    /* FEAT_01FE */
#define FEAT_EPIC_DEVASTATING_CRITICAL_SCIMITAR          511    /* FEAT_01FF */
#define FEAT_EPIC_DEVASTATING_CRITICAL_LONGSWORD         512    /* FEAT_0200 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_GREATSWORD        513    /* FEAT_0201 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_HANDAXE           514    /* FEAT_0202 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_THROWINGAXE       515    /* FEAT_0203 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_BATTLEAXE         516    /* FEAT_0204 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_GREATAXE          517    /* FEAT_0205 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_HALBERD           518    /* FEAT_0206 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_LIGHTHAMMER       519    /* FEAT_0207 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_LIGHTFLAIL        520    /* FEAT_0208 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_WARHAMMER         521    /* FEAT_0209 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_HEAVYFLAIL        522    /* FEAT_020A */
#define FEAT_EPIC_DEVASTATING_CRITICAL_KAMA              523    /* FEAT_020B */
#define FEAT_EPIC_DEVASTATING_CRITICAL_KUKRI             524    /* FEAT_020C */
#define FEAT_EPIC_DEVASTATING_CRITICAL_SHURIKEN          525    /* FEAT_020D */
#define FEAT_EPIC_DEVASTATING_CRITICAL_SCYTHE            526    /* FEAT_020E */
#define FEAT_EPIC_DEVASTATING_CRITICAL_KATANA            527    /* FEAT_020F */
#define FEAT_EPIC_DEVASTATING_CRITICAL_BASTARDSWORD      528    /* FEAT_0210 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_DIREMACE          529    /* FEAT_0211 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_DOUBLEAXE         530    /* FEAT_0212 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_TWOBLADEDSWORD    531    /* FEAT_0213 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_CREATURE          532    /* FEAT_0214 */
#define FEAT_EPIC_ENERGY_RESISTANCE_COLD_1               533    /* FEAT_0215 */
#define FEAT_EPIC_ENERGY_RESISTANCE_COLD_2               534    /* FEAT_0216 */
#define FEAT_EPIC_ENERGY_RESISTANCE_COLD_3               535    /* FEAT_0217 */
#define FEAT_EPIC_ENERGY_RESISTANCE_COLD_4               536    /* FEAT_0218 */
#define FEAT_EPIC_ENERGY_RESISTANCE_COLD_5               537    /* FEAT_0219 */
#define FEAT_EPIC_ENERGY_RESISTANCE_COLD_6               538    /* FEAT_021A */
#define FEAT_EPIC_ENERGY_RESISTANCE_COLD_7               539    /* FEAT_021B */
#define FEAT_EPIC_ENERGY_RESISTANCE_COLD_8               540    /* FEAT_021C */
#define FEAT_EPIC_ENERGY_RESISTANCE_COLD_9               541    /* FEAT_021D */
#define FEAT_EPIC_ENERGY_RESISTANCE_COLD_10              542    /* FEAT_021E */
#define FEAT_EPIC_ENERGY_RESISTANCE_ACID_1               543    /* FEAT_021F */
#define FEAT_EPIC_ENERGY_RESISTANCE_ACID_2               544    /* FEAT_0220 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ACID_3               545    /* FEAT_0221 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ACID_4               546    /* FEAT_0222 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ACID_5               547    /* FEAT_0223 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ACID_6               548    /* FEAT_0224 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ACID_7               549    /* FEAT_0225 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ACID_8               550    /* FEAT_0226 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ACID_9               551    /* FEAT_0227 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ACID_10              552    /* FEAT_0228 */
#define FEAT_EPIC_ENERGY_RESISTANCE_FIRE_1               553    /* FEAT_0229 */
#define FEAT_EPIC_ENERGY_RESISTANCE_FIRE_2               554    /* FEAT_022A */
#define FEAT_EPIC_ENERGY_RESISTANCE_FIRE_3               555    /* FEAT_022B */
#define FEAT_EPIC_ENERGY_RESISTANCE_FIRE_4               556    /* FEAT_022C */
#define FEAT_EPIC_ENERGY_RESISTANCE_FIRE_5               557    /* FEAT_022D */
#define FEAT_EPIC_ENERGY_RESISTANCE_FIRE_6               558    /* FEAT_022E */
#define FEAT_EPIC_ENERGY_RESISTANCE_FIRE_7               559    /* FEAT_022F */
#define FEAT_EPIC_ENERGY_RESISTANCE_FIRE_8               560    /* FEAT_0230 */
#define FEAT_EPIC_ENERGY_RESISTANCE_FIRE_9               561    /* FEAT_0231 */
#define FEAT_EPIC_ENERGY_RESISTANCE_FIRE_10              562    /* FEAT_0232 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ELECTRICAL_1         563    /* FEAT_0233 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ELECTRICAL_2         564    /* FEAT_0234 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ELECTRICAL_3         565    /* FEAT_0235 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ELECTRICAL_4         566    /* FEAT_0236 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ELECTRICAL_5         567    /* FEAT_0237 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ELECTRICAL_6         568    /* FEAT_0238 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ELECTRICAL_7         569    /* FEAT_0239 */
#define FEAT_EPIC_ENERGY_RESISTANCE_ELECTRICAL_8         570    /* FEAT_023A */
#define FEAT_EPIC_ENERGY_RESISTANCE_ELECTRICAL_9         571    /* FEAT_023B */
#define FEAT_EPIC_ENERGY_RESISTANCE_ELECTRICAL_10        572    /* FEAT_023C */
#define FEAT_EPIC_ENERGY_RESISTANCE_SONIC_1              573    /* FEAT_023D */
#define FEAT_EPIC_ENERGY_RESISTANCE_SONIC_2              574    /* FEAT_023E */
#define FEAT_EPIC_ENERGY_RESISTANCE_SONIC_3              575    /* FEAT_023F */
#define FEAT_EPIC_ENERGY_RESISTANCE_SONIC_4              576    /* FEAT_0240 */
#define FEAT_EPIC_ENERGY_RESISTANCE_SONIC_5              577    /* FEAT_0241 */
#define FEAT_EPIC_ENERGY_RESISTANCE_SONIC_6              578    /* FEAT_0242 */
#define FEAT_EPIC_ENERGY_RESISTANCE_SONIC_7              579    /* FEAT_0243 */
#define FEAT_EPIC_ENERGY_RESISTANCE_SONIC_8              580    /* FEAT_0244 */
#define FEAT_EPIC_ENERGY_RESISTANCE_SONIC_9              581    /* FEAT_0245 */
#define FEAT_EPIC_ENERGY_RESISTANCE_SONIC_10             582    /* FEAT_0246 */
#define FEAT_EPIC_FORTITUDE                              583    /* FEAT_0247 */
#define FEAT_EPIC_PROWESS                                584    /* FEAT_0248 */
#define FEAT_EPIC_REFLEXES                               585    /* FEAT_0249 */
#define FEAT_EPIC_REPUTATION                             586    /* FEAT_024A */
#define FEAT_EPIC_SKILL_FOCUS_ANIMAL_EMPATHY             587    /* FEAT_024B */
#define FEAT_EPIC_SKILL_FOCUS_APPRAISE                   588    /* FEAT_024C */
#define FEAT_EPIC_SKILL_FOCUS_CONCENTRATION              589    /* FEAT_024D */
#define FEAT_EPIC_SKILL_FOCUS_CRAFT_TRAP                 590    /* FEAT_024E */
#define FEAT_EPIC_SKILL_FOCUS_DISABLETRAP                591    /* FEAT_024F */
#define FEAT_EPIC_SKILL_FOCUS_DISCIPLINE                 592    /* FEAT_0250 */
#define FEAT_EPIC_SKILL_FOCUS_HEAL                       593    /* FEAT_0251 */
#define FEAT_EPIC_SKILL_FOCUS_HIDE                       594    /* FEAT_0252 */
#define FEAT_EPIC_SKILL_FOCUS_LISTEN                     595    /* FEAT_0253 */
#define FEAT_EPIC_SKILL_FOCUS_LORE                       596    /* FEAT_0254 */
#define FEAT_EPIC_SKILL_FOCUS_MOVESILENTLY               597    /* FEAT_0255 */
#define FEAT_EPIC_SKILL_FOCUS_OPENLOCK                   598    /* FEAT_0256 */
#define FEAT_EPIC_SKILL_FOCUS_PARRY                      599    /* FEAT_0257 */
#define FEAT_EPIC_SKILL_FOCUS_PERFORM                    600    /* FEAT_0258 */
#define FEAT_EPIC_SKILL_FOCUS_PERSUADE                   601    /* FEAT_0259 */
#define FEAT_EPIC_SKILL_FOCUS_PICKPOCKET                 602    /* FEAT_025A */
#define FEAT_EPIC_SKILL_FOCUS_SEARCH                     603    /* FEAT_025B */
#define FEAT_EPIC_SKILL_FOCUS_SETTRAP                    604    /* FEAT_025C */
#define FEAT_EPIC_SKILL_FOCUS_SPELLCRAFT                 605    /* FEAT_025D */
#define FEAT_EPIC_SKILL_FOCUS_SPOT                       606    /* FEAT_025E */
#define FEAT_EPIC_SKILL_FOCUS_TAUNT                      607    /* FEAT_025F */
#define FEAT_EPIC_SKILL_FOCUS_TUMBLE                     608    /* FEAT_0260 */
#define FEAT_EPIC_SKILL_FOCUS_USEMAGICDEVICE             609    /* FEAT_0261 */
#define FEAT_EPIC_SPELL_FOCUS_ABJURATION                 610    /* FEAT_0262 */
#define FEAT_EPIC_SPELL_FOCUS_CONJURATION                611    /* FEAT_0263 */
#define FEAT_EPIC_SPELL_FOCUS_DIVINATION                 612    /* FEAT_0264 */
#define FEAT_EPIC_SPELL_FOCUS_ENCHANTMENT                613    /* FEAT_0265 */
#define FEAT_EPIC_SPELL_FOCUS_EVOCATION                  614    /* FEAT_0266 */
#define FEAT_EPIC_SPELL_FOCUS_ILLUSION                   615    /* FEAT_0267 */
#define FEAT_EPIC_SPELL_FOCUS_NECROMANCY                 616    /* FEAT_0268 */
#define FEAT_EPIC_SPELL_FOCUS_TRANSMUTATION              617    /* FEAT_0269 */
#define FEAT_EPIC_SPELL_PENETRATION                      618    /* FEAT_026A */
#define FEAT_EPIC_WEAPON_FOCUS_CLUB                      619    /* FEAT_026B */
#define FEAT_EPIC_WEAPON_FOCUS_DAGGER                    620    /* FEAT_026C */
#define FEAT_EPIC_WEAPON_FOCUS_DART                      621    /* FEAT_026D */
#define FEAT_EPIC_WEAPON_FOCUS_HEAVYCROSSBOW             622    /* FEAT_026E */
#define FEAT_EPIC_WEAPON_FOCUS_LIGHTCROSSBOW             623    /* FEAT_026F */
#define FEAT_EPIC_WEAPON_FOCUS_LIGHTMACE                 624    /* FEAT_0270 */
#define FEAT_EPIC_WEAPON_FOCUS_MORNINGSTAR               625    /* FEAT_0271 */
#define FEAT_EPIC_WEAPON_FOCUS_QUARTERSTAFF              626    /* FEAT_0272 */
#define FEAT_EPIC_WEAPON_FOCUS_SHORTSPEAR                627    /* FEAT_0273 */
#define FEAT_EPIC_WEAPON_FOCUS_SICKLE                    628    /* FEAT_0274 */
#define FEAT_EPIC_WEAPON_FOCUS_SLING                     629    /* FEAT_0275 */
#define FEAT_EPIC_WEAPON_FOCUS_UNARMED                   630    /* FEAT_0276 */
#define FEAT_EPIC_WEAPON_FOCUS_LONGBOW                   631    /* FEAT_0277 */
#define FEAT_EPIC_WEAPON_FOCUS_SHORTBOW                  632    /* FEAT_0278 */
#define FEAT_EPIC_WEAPON_FOCUS_SHORTSWORD                633    /* FEAT_0279 */
#define FEAT_EPIC_WEAPON_FOCUS_RAPIER                    634    /* FEAT_027A */
#define FEAT_EPIC_WEAPON_FOCUS_SCIMITAR                  635    /* FEAT_027B */
#define FEAT_EPIC_WEAPON_FOCUS_LONGSWORD                 636    /* FEAT_027C */
#define FEAT_EPIC_WEAPON_FOCUS_GREATSWORD                637    /* FEAT_027D */
#define FEAT_EPIC_WEAPON_FOCUS_HANDAXE                   638    /* FEAT_027E */
#define FEAT_EPIC_WEAPON_FOCUS_THROWINGAXE               639    /* FEAT_027F */
#define FEAT_EPIC_WEAPON_FOCUS_BATTLEAXE                 640    /* FEAT_0280 */
#define FEAT_EPIC_WEAPON_FOCUS_GREATAXE                  641    /* FEAT_0281 */
#define FEAT_EPIC_WEAPON_FOCUS_HALBERD                   642    /* FEAT_0282 */
#define FEAT_EPIC_WEAPON_FOCUS_LIGHTHAMMER               643    /* FEAT_0283 */
#define FEAT_EPIC_WEAPON_FOCUS_LIGHTFLAIL                644    /* FEAT_0284 */
#define FEAT_EPIC_WEAPON_FOCUS_WARHAMMER                 645    /* FEAT_0285 */
#define FEAT_EPIC_WEAPON_FOCUS_HEAVYFLAIL                646    /* FEAT_0286 */
#define FEAT_EPIC_WEAPON_FOCUS_KAMA                      647    /* FEAT_0287 */
#define FEAT_EPIC_WEAPON_FOCUS_KUKRI                     648    /* FEAT_0288 */
#define FEAT_EPIC_WEAPON_FOCUS_SHURIKEN                  649    /* FEAT_0289 */
#define FEAT_EPIC_WEAPON_FOCUS_SCYTHE                    650    /* FEAT_028A */
#define FEAT_EPIC_WEAPON_FOCUS_KATANA                    651    /* FEAT_028B */
#define FEAT_EPIC_WEAPON_FOCUS_BASTARDSWORD              652    /* FEAT_028C */
#define FEAT_EPIC_WEAPON_FOCUS_DIREMACE                  653    /* FEAT_028D */
#define FEAT_EPIC_WEAPON_FOCUS_DOUBLEAXE                 654    /* FEAT_028E */
#define FEAT_EPIC_WEAPON_FOCUS_TWOBLADEDSWORD            655    /* FEAT_028F */
#define FEAT_EPIC_WEAPON_FOCUS_CREATURE                  656    /* FEAT_0290 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_CLUB             657    /* FEAT_0291 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_DAGGER           658    /* FEAT_0292 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_DART             659    /* FEAT_0293 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_HEAVYCROSSBOW    660    /* FEAT_0294 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHTCROSSBOW    661    /* FEAT_0295 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHTMACE        662    /* FEAT_0296 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_MORNINGSTAR      663    /* FEAT_0297 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_QUARTERSTAFF     664    /* FEAT_0298 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_SHORTSPEAR       665    /* FEAT_0299 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_SICKLE           666    /* FEAT_029A */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_SLING            667    /* FEAT_029B */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_UNARMED          668    /* FEAT_029C */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_LONGBOW          669    /* FEAT_029D */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_SHORTBOW         670    /* FEAT_029E */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_SHORTSWORD       671    /* FEAT_029F */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_RAPIER           672    /* FEAT_02A0 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_SCIMITAR         673    /* FEAT_02A1 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_LONGSWORD        674    /* FEAT_02A2 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_GREATSWORD       675    /* FEAT_02A3 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_HANDAXE          676    /* FEAT_02A4 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_THROWINGAXE      677    /* FEAT_02A5 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_BATTLEAXE        678    /* FEAT_02A6 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_GREATAXE         679    /* FEAT_02A7 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_HALBERD          680    /* FEAT_02A8 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHTHAMMER      681    /* FEAT_02A9 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHTFLAIL       682    /* FEAT_02AA */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_WARHAMMER        683    /* FEAT_02AB */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_HEAVYFLAIL       684    /* FEAT_02AC */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_KAMA             685    /* FEAT_02AD */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_KUKRI            686    /* FEAT_02AE */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_SHURIKEN         687    /* FEAT_02AF */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_SCYTHE           688    /* FEAT_02B0 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_KATANA           689    /* FEAT_02B1 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_BASTARDSWORD     690    /* FEAT_02B2 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_DIREMACE         691    /* FEAT_02B3 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_DOUBLEAXE        692    /* FEAT_02B4 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_TWOBLADEDSWORD   693    /* FEAT_02B5 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_CREATURE         694    /* FEAT_02B6 */
#define FEAT_EPIC_WILL                                   695    /* FEAT_02B7 */
#define FEAT_EPIC_IMPROVED_COMBAT_CASTING                696    /* FEAT_02B8 */
#define FEAT_EPIC_IMPROVED_KI_STRIKE_4                   697    /* FEAT_02B9 */
#define FEAT_EPIC_IMPROVED_KI_STRIKE_5                   698    /* FEAT_02BA */
#define FEAT_EPIC_IMPROVED_SPELL_RESISTANCE_1            699    /* FEAT_02BB */
#define FEAT_EPIC_IMPROVED_SPELL_RESISTANCE_2            700    /* FEAT_02BC */
#define FEAT_EPIC_IMPROVED_SPELL_RESISTANCE_3            701    /* FEAT_02BD */
#define FEAT_EPIC_IMPROVED_SPELL_RESISTANCE_4            702    /* FEAT_02BE */
#define FEAT_EPIC_IMPROVED_SPELL_RESISTANCE_5            703    /* FEAT_02BF */
#define FEAT_EPIC_IMPROVED_SPELL_RESISTANCE_6            704    /* FEAT_02C0 */
#define FEAT_EPIC_IMPROVED_SPELL_RESISTANCE_7            705    /* FEAT_02C1 */
#define FEAT_EPIC_IMPROVED_SPELL_RESISTANCE_8            706    /* FEAT_02C2 */
#define FEAT_EPIC_IMPROVED_SPELL_RESISTANCE_9            707    /* FEAT_02C3 */
#define FEAT_EPIC_IMPROVED_SPELL_RESISTANCE_10           708    /* FEAT_02C4 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_CLUB             709    /* FEAT_02C5 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_DAGGER           710    /* FEAT_02C6 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_DART             711    /* FEAT_02C7 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_HEAVYCROSSBOW    712    /* FEAT_02C8 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_LIGHTCROSSBOW    713    /* FEAT_02C9 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_LIGHTMACE        714    /* FEAT_02CA */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_MORNINGSTAR      715    /* FEAT_02CB */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_QUARTERSTAFF     716    /* FEAT_02CC */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_SHORTSPEAR       717    /* FEAT_02CD */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_SICKLE           718    /* FEAT_02CE */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_SLING            719    /* FEAT_02CF */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_UNARMED          720    /* FEAT_02D0 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_LONGBOW          721    /* FEAT_02D1 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_SHORTBOW         722    /* FEAT_02D2 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_SHORTSWORD       723    /* FEAT_02D3 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_RAPIER           724    /* FEAT_02D4 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_SCIMITAR         725    /* FEAT_02D5 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_LONGSWORD        726    /* FEAT_02D6 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_GREATSWORD       727    /* FEAT_02D7 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_HANDAXE          728    /* FEAT_02D8 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_THROWINGAXE      729    /* FEAT_02D9 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_BATTLEAXE        730    /* FEAT_02DA */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_GREATAXE         731    /* FEAT_02DB */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_HALBERD          732    /* FEAT_02DC */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_LIGHTHAMMER      733    /* FEAT_02DD */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_LIGHTFLAIL       734    /* FEAT_02DE */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_WARHAMMER        735    /* FEAT_02DF */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_HEAVYFLAIL       736    /* FEAT_02E0 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_KAMA             737    /* FEAT_02E1 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_KUKRI            738    /* FEAT_02E2 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_SHURIKEN         739    /* FEAT_02E3 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_SCYTHE           740    /* FEAT_02E4 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_KATANA           741    /* FEAT_02E5 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_BASTARDSWORD     742    /* FEAT_02E6 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_DIREMACE         743    /* FEAT_02E7 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_DOUBLEAXE        744    /* FEAT_02E8 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_TWOBLADEDSWORD   745    /* FEAT_02E9 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_CREATURE         746    /* FEAT_02EA */
#define FEAT_EPIC_PERFECT_HEALTH                         747    /* FEAT_02EB */
#define FEAT_EPIC_SELF_CONCEALMENT_10                    748    /* FEAT_02EC */
#define FEAT_EPIC_SELF_CONCEALMENT_20                    749    /* FEAT_02ED */
#define FEAT_EPIC_SELF_CONCEALMENT_30                    750    /* FEAT_02EE */
#define FEAT_EPIC_SELF_CONCEALMENT_40                    751    /* FEAT_02EF */
#define FEAT_EPIC_SELF_CONCEALMENT_50                    752    /* FEAT_02F0 */
#define FEAT_EPIC_SUPERIOR_INITIATIVE                    753    /* FEAT_02F1 */
#define FEAT_EPIC_TOUGHNESS_1                            754    /* FEAT_02F2 */
#define FEAT_EPIC_TOUGHNESS_2                            755    /* FEAT_02F3 */
#define FEAT_EPIC_TOUGHNESS_3                            756    /* FEAT_02F4 */
#define FEAT_EPIC_TOUGHNESS_4                            757    /* FEAT_02F5 */
#define FEAT_EPIC_TOUGHNESS_5                            758    /* FEAT_02F6 */
#define FEAT_EPIC_TOUGHNESS_6                            759    /* FEAT_02F7 */
#define FEAT_EPIC_TOUGHNESS_7                            760    /* FEAT_02F8 */
#define FEAT_EPIC_TOUGHNESS_8                            761    /* FEAT_02F9 */
#define FEAT_EPIC_TOUGHNESS_9                            762    /* FEAT_02FA */
#define FEAT_EPIC_TOUGHNESS_10                           763    /* FEAT_02FB */
#define FEAT_EPIC_GREAT_CHARISMA_1                       764    /* FEAT_02FC */
#define FEAT_EPIC_GREAT_CHARISMA_2                       765    /* FEAT_02FD */
#define FEAT_EPIC_GREAT_CHARISMA_3                       766    /* FEAT_02FE */
#define FEAT_EPIC_GREAT_CHARISMA_4                       767    /* FEAT_02FF */
#define FEAT_EPIC_GREAT_CHARISMA_5                       768    /* FEAT_0300 */
#define FEAT_EPIC_GREAT_CHARISMA_6                       769    /* FEAT_0301 */
#define FEAT_EPIC_GREAT_CHARISMA_7                       770    /* FEAT_0302 */
#define FEAT_EPIC_GREAT_CHARISMA_8                       771    /* FEAT_0303 */
#define FEAT_EPIC_GREAT_CHARISMA_9                       772    /* FEAT_0304 */
#define FEAT_EPIC_GREAT_CHARISMA_10                      773    /* FEAT_0305 */
#define FEAT_EPIC_GREAT_CONSTITUTION_1                   774    /* FEAT_0306 */
#define FEAT_EPIC_GREAT_CONSTITUTION_2                   775    /* FEAT_0307 */
#define FEAT_EPIC_GREAT_CONSTITUTION_3                   776    /* FEAT_0308 */
#define FEAT_EPIC_GREAT_CONSTITUTION_4                   777    /* FEAT_0309 */
#define FEAT_EPIC_GREAT_CONSTITUTION_5                   778    /* FEAT_030A */
#define FEAT_EPIC_GREAT_CONSTITUTION_6                   779    /* FEAT_030B */
#define FEAT_EPIC_GREAT_CONSTITUTION_7                   780    /* FEAT_030C */
#define FEAT_EPIC_GREAT_CONSTITUTION_8                   781    /* FEAT_030D */
#define FEAT_EPIC_GREAT_CONSTITUTION_9                   782    /* FEAT_030E */
#define FEAT_EPIC_GREAT_CONSTITUTION_10                  783    /* FEAT_030F */
#define FEAT_EPIC_GREAT_DEXTERITY_1                      784    /* FEAT_0310 */
#define FEAT_EPIC_GREAT_DEXTERITY_2                      785    /* FEAT_0311 */
#define FEAT_EPIC_GREAT_DEXTERITY_3                      786    /* FEAT_0312 */
#define FEAT_EPIC_GREAT_DEXTERITY_4                      787    /* FEAT_0313 */
#define FEAT_EPIC_GREAT_DEXTERITY_5                      788    /* FEAT_0314 */
#define FEAT_EPIC_GREAT_DEXTERITY_6                      789    /* FEAT_0315 */
#define FEAT_EPIC_GREAT_DEXTERITY_7                      790    /* FEAT_0316 */
#define FEAT_EPIC_GREAT_DEXTERITY_8                      791    /* FEAT_0317 */
#define FEAT_EPIC_GREAT_DEXTERITY_9                      792    /* FEAT_0318 */
#define FEAT_EPIC_GREAT_DEXTERITY_10                     793    /* FEAT_0319 */
#define FEAT_EPIC_GREAT_INTELLIGENCE_1                   794    /* FEAT_031A */
#define FEAT_EPIC_GREAT_INTELLIGENCE_2                   795    /* FEAT_031B */
#define FEAT_EPIC_GREAT_INTELLIGENCE_3                   796    /* FEAT_031C */
#define FEAT_EPIC_GREAT_INTELLIGENCE_4                   797    /* FEAT_031D */
#define FEAT_EPIC_GREAT_INTELLIGENCE_5                   798    /* FEAT_031E */
#define FEAT_EPIC_GREAT_INTELLIGENCE_6                   799    /* FEAT_031F */
#define FEAT_EPIC_GREAT_INTELLIGENCE_7                   800    /* FEAT_0320 */
#define FEAT_EPIC_GREAT_INTELLIGENCE_8                   801    /* FEAT_0321 */
#define FEAT_EPIC_GREAT_INTELLIGENCE_9                   802    /* FEAT_0322 */
#define FEAT_EPIC_GREAT_INTELLIGENCE_10                  803    /* FEAT_0323 */
#define FEAT_EPIC_GREAT_WISDOM_1                         804    /* FEAT_0324 */
#define FEAT_EPIC_GREAT_WISDOM_2                         805    /* FEAT_0325 */
#define FEAT_EPIC_GREAT_WISDOM_3                         806    /* FEAT_0326 */
#define FEAT_EPIC_GREAT_WISDOM_4                         807    /* FEAT_0327 */
#define FEAT_EPIC_GREAT_WISDOM_5                         808    /* FEAT_0328 */
#define FEAT_EPIC_GREAT_WISDOM_6                         809    /* FEAT_0329 */
#define FEAT_EPIC_GREAT_WISDOM_7                         810    /* FEAT_032A */
#define FEAT_EPIC_GREAT_WISDOM_8                         811    /* FEAT_032B */
#define FEAT_EPIC_GREAT_WISDOM_9                         812    /* FEAT_032C */
#define FEAT_EPIC_GREAT_WISDOM_10                        813    /* FEAT_032D */
#define FEAT_EPIC_GREAT_STRENGTH_1                       814    /* FEAT_032E */
#define FEAT_EPIC_GREAT_STRENGTH_2                       815    /* FEAT_032F */
#define FEAT_EPIC_GREAT_STRENGTH_3                       816    /* FEAT_0330 */
#define FEAT_EPIC_GREAT_STRENGTH_4                       817    /* FEAT_0331 */
#define FEAT_EPIC_GREAT_STRENGTH_5                       818    /* FEAT_0332 */
#define FEAT_EPIC_GREAT_STRENGTH_6                       819    /* FEAT_0333 */
#define FEAT_EPIC_GREAT_STRENGTH_7                       820    /* FEAT_0334 */
#define FEAT_EPIC_GREAT_STRENGTH_8                       821    /* FEAT_0335 */
#define FEAT_EPIC_GREAT_STRENGTH_9                       822    /* FEAT_0336 */
#define FEAT_EPIC_GREAT_STRENGTH_10                      823    /* FEAT_0337 */
#define FEAT_EPIC_GREAT_SMITING_1                        824    /* FEAT_0338 */
#define FEAT_EPIC_GREAT_SMITING_2                        825    /* FEAT_0339 */
#define FEAT_EPIC_GREAT_SMITING_3                        826    /* FEAT_033A */
#define FEAT_EPIC_GREAT_SMITING_4                        827    /* FEAT_033B */
#define FEAT_EPIC_GREAT_SMITING_5                        828    /* FEAT_033C */
#define FEAT_EPIC_GREAT_SMITING_6                        829    /* FEAT_033D */
#define FEAT_EPIC_GREAT_SMITING_7                        830    /* FEAT_033E */
#define FEAT_EPIC_GREAT_SMITING_8                        831    /* FEAT_033F */
#define FEAT_EPIC_GREAT_SMITING_9                        832    /* FEAT_0340 */
#define FEAT_EPIC_GREAT_SMITING_10                       833    /* FEAT_0341 */
#define FEAT_EPIC_IMPROVED_SNEAK_ATTACK_1                834    /* FEAT_0342 */
#define FEAT_EPIC_IMPROVED_SNEAK_ATTACK_2                835    /* FEAT_0343 */
#define FEAT_EPIC_IMPROVED_SNEAK_ATTACK_3                836    /* FEAT_0344 */
#define FEAT_EPIC_IMPROVED_SNEAK_ATTACK_4                837    /* FEAT_0345 */
#define FEAT_EPIC_IMPROVED_SNEAK_ATTACK_5                838    /* FEAT_0346 */
#define FEAT_EPIC_IMPROVED_SNEAK_ATTACK_6                839    /* FEAT_0347 */
#define FEAT_EPIC_IMPROVED_SNEAK_ATTACK_7                840    /* FEAT_0348 */
#define FEAT_EPIC_IMPROVED_SNEAK_ATTACK_8                841    /* FEAT_0349 */
#define FEAT_EPIC_IMPROVED_SNEAK_ATTACK_9                842    /* FEAT_034A */
#define FEAT_EPIC_IMPROVED_SNEAK_ATTACK_10               843    /* FEAT_034B */
#define FEAT_EPIC_IMPROVED_STUNNING_FIST_1               844    /* FEAT_034C */
#define FEAT_EPIC_IMPROVED_STUNNING_FIST_2               845    /* FEAT_034D */
#define FEAT_EPIC_IMPROVED_STUNNING_FIST_3               846    /* FEAT_034E */
#define FEAT_EPIC_IMPROVED_STUNNING_FIST_4               847    /* FEAT_034F */
#define FEAT_EPIC_IMPROVED_STUNNING_FIST_5               848    /* FEAT_0350 */
#define FEAT_EPIC_IMPROVED_STUNNING_FIST_6               849    /* FEAT_0351 */
#define FEAT_EPIC_IMPROVED_STUNNING_FIST_7               850    /* FEAT_0352 */
#define FEAT_EPIC_IMPROVED_STUNNING_FIST_8               851    /* FEAT_0353 */
#define FEAT_EPIC_IMPROVED_STUNNING_FIST_9               852    /* FEAT_0354 */
#define FEAT_EPIC_IMPROVED_STUNNING_FIST_10              853    /* FEAT_0355 */
#define FEAT_EPIC_PLANAR_TURNING                         854    /* FEAT_0356 */
#define FEAT_EPIC_BANE_OF_ENEMIES                        855    /* FEAT_0357 */
#define FEAT_EPIC_DODGE                                  856    /* FEAT_0358 */
#define FEAT_EPIC_AUTOMATIC_QUICKEN_1                    857    /* FEAT_0359 */
#define FEAT_EPIC_AUTOMATIC_QUICKEN_2                    858    /* FEAT_035A */
#define FEAT_EPIC_AUTOMATIC_QUICKEN_3                    859    /* FEAT_035B */
#define FEAT_EPIC_AUTOMATIC_SILENT_SPELL_1               860    /* FEAT_035C */
#define FEAT_EPIC_AUTOMATIC_SILENT_SPELL_2               861    /* FEAT_035D */
#define FEAT_EPIC_AUTOMATIC_SILENT_SPELL_3               862    /* FEAT_035E */
#define FEAT_EPIC_AUTOMATIC_STILL_SPELL_1                863    /* FEAT_035F */
#define FEAT_EPIC_AUTOMATIC_STILL_SPELL_2                864    /* FEAT_0360 */
#define FEAT_EPIC_AUTOMATIC_STILL_SPELL_3                865    /* FEAT_0361 */
#define FEAT_MARTIAL_FLURRY_LIGHT                        866    /* FEAT_0362 */
#define FEAT_WHIRLWIND_ATTACK                            867    /* FEAT_0363 */
#define FEAT_IMPROVED_WHIRLWIND                          868    /* FEAT_0364 */
#define FEAT_MIGHTY_RAGE                                 869    /* FEAT_0365 */
#define FEAT_EPIC_LASTING_INSPIRATION                    870    /* FEAT_0366 */
#define FEAT_CURSE_SONG                                  871    /* FEAT_0367 */
#define FEAT_WILD_SHAPE_UNDEAD                           872    /* FEAT_0368 */
#define FEAT_WILD_SHAPE_DRAGON                           873    /* FEAT_0369 */
#define FEAT_EPIC_SPELL_MUMMY_DUST                       874    /* FEAT_036A */
#define FEAT_EPIC_SPELL_DRAGON_KNIGHT                    875    /* FEAT_036B */
#define FEAT_EPIC_SPELL_HELLBALL                         876    /* FEAT_036C */
#define FEAT_EPIC_SPELL_MAGE_ARMOUR                      877    /* FEAT_036D */
#define FEAT_EPIC_SPELL_RUIN                             878    /* FEAT_036E */
#define FEAT_WEAPON_OF_CHOICE_SICKLE                     879    /* FEAT_036F */
#define FEAT_WEAPON_OF_CHOICE_KAMA                       880    /* FEAT_0370 */
#define FEAT_WEAPON_OF_CHOICE_KUKRI                      881    /* FEAT_0371 */
#define FEAT_KI_DAMAGE                                   882    /* FEAT_0372 */
#define FEAT_INCREASE_MULTIPLIER                         883    /* FEAT_0373 */
#define FEAT_SUPERIOR_WEAPON_FOCUS                       884    /* FEAT_0374 */
#define FEAT_KI_CRITICAL                                 885    /* FEAT_0375 */
#define FEAT_BONE_SKIN_2                                 886    /* FEAT_0376 */
#define FEAT_ANIMATE_DEAD                                889    /* FEAT_0379 */
#define FEAT_SUMMON_UNDEAD                               890    /* FEAT_037A */
#define FEAT_DEATHLESS_VIGOR                             891    /* FEAT_037B */
#define FEAT_UNDEAD_GRAFT_1                              892    /* FEAT_037C */
#define FEAT_UNDEAD_GRAFT_2                              893    /* FEAT_037D */
#define FEAT_TOUGH_AS_BONE                               894    /* FEAT_037E */
#define FEAT_SUMMON_GREATER_UNDEAD                       895    /* FEAT_037F */
#define FEAT_DEATHLESS_MASTERY                           896    /* FEAT_0380 */
#define FEAT_DEATHLESS_MASTER_TOUCH                      897    /* FEAT_0381 */
#define FEAT_GREATER_WILDSHAPE_1                         898    /* FEAT_0382 */
#define FEAT_MARTIAL_FLURRY_ANY                          899    /* FEAT_0383 */
#define FEAT_GREATER_WILDSHAPE_2                         900    /* FEAT_0384 */
#define FEAT_GREATER_WILDSHAPE_3                         901    /* FEAT_0385 */
#define FEAT_HUMANOID_SHAPE                              902    /* FEAT_0386 */
#define FEAT_GREATER_WILDSHAPE_4                         903    /* FEAT_0387 */
#define FEAT_SACRED_DEFENSE_1                            904    /* FEAT_0388 */
#define FEAT_SACRED_DEFENSE_2                            905    /* FEAT_0389 */
#define FEAT_SACRED_DEFENSE_3                            906    /* FEAT_038A */
#define FEAT_SACRED_DEFENSE_4                            907    /* FEAT_038B */
#define FEAT_SACRED_DEFENSE_5                            908    /* FEAT_038C */
#define FEAT_DIVINE_WRATH                                909    /* FEAT_038D */
#define FEAT_EXTRA_SMITING                               910    /* FEAT_038E */
#define FEAT_SKILL_FOCUS_CRAFT_ARMOR                     911    /* FEAT_038F */
#define FEAT_SKILL_FOCUS_CRAFT_WEAPON                    912    /* FEAT_0390 */
#define FEAT_EPIC_SKILL_FOCUS_CRAFT_ARMOR                913    /* FEAT_0391 */
#define FEAT_EPIC_SKILL_FOCUS_CRAFT_WEAPON               914    /* FEAT_0392 */
#define FEAT_SKILL_FOCUS_BLUFF                           915    /* FEAT_0393 */
#define FEAT_SKILL_FOCUS_INTIMIDATE                      916    /* FEAT_0394 */
#define FEAT_EPIC_SKILL_FOCUS_BLUFF                      917    /* FEAT_0395 */
#define FEAT_EPIC_SKILL_FOCUS_INTIMIDATE                 918    /* FEAT_0396 */
#define FEAT_WEAPON_OF_CHOICE_CLUB                       919    /* FEAT_0397 */
#define FEAT_WEAPON_OF_CHOICE_DAGGER                     920    /* FEAT_0398 */
#define FEAT_WEAPON_OF_CHOICE_LIGHTMACE                  921    /* FEAT_0399 */
#define FEAT_WEAPON_OF_CHOICE_MORNINGSTAR                922    /* FEAT_039A */
#define FEAT_WEAPON_OF_CHOICE_QUARTERSTAFF               923    /* FEAT_039B */
#define FEAT_WEAPON_OF_CHOICE_SHORTSPEAR                 924    /* FEAT_039C */
#define FEAT_WEAPON_OF_CHOICE_SHORTSWORD                 925    /* FEAT_039D */
#define FEAT_WEAPON_OF_CHOICE_RAPIER                     926    /* FEAT_039E */
#define FEAT_WEAPON_OF_CHOICE_SCIMITAR                   927    /* FEAT_039F */
#define FEAT_WEAPON_OF_CHOICE_LONGSWORD                  928    /* FEAT_03A0 */
#define FEAT_WEAPON_OF_CHOICE_GREATSWORD                 929    /* FEAT_03A1 */
#define FEAT_WEAPON_OF_CHOICE_HANDAXE                    930    /* FEAT_03A2 */
#define FEAT_WEAPON_OF_CHOICE_BATTLEAXE                  931    /* FEAT_03A3 */
#define FEAT_WEAPON_OF_CHOICE_GREATAXE                   932    /* FEAT_03A4 */
#define FEAT_WEAPON_OF_CHOICE_HALBERD                    933    /* FEAT_03A5 */
#define FEAT_WEAPON_OF_CHOICE_LIGHTHAMMER                934    /* FEAT_03A6 */
#define FEAT_WEAPON_OF_CHOICE_LIGHTFLAIL                 935    /* FEAT_03A7 */
#define FEAT_WEAPON_OF_CHOICE_WARHAMMER                  936    /* FEAT_03A8 */
#define FEAT_WEAPON_OF_CHOICE_HEAVYFLAIL                 937    /* FEAT_03A9 */
#define FEAT_WEAPON_OF_CHOICE_SCYTHE                     938    /* FEAT_03AA */
#define FEAT_WEAPON_OF_CHOICE_KATANA                     939    /* FEAT_03AB */
#define FEAT_WEAPON_OF_CHOICE_BASTARDSWORD               940    /* FEAT_03AC */
#define FEAT_WEAPON_OF_CHOICE_DIREMACE                   941    /* FEAT_03AD */
#define FEAT_WEAPON_OF_CHOICE_DOUBLEAXE                  942    /* FEAT_03AE */
#define FEAT_WEAPON_OF_CHOICE_TWOBLADEDSWORD             943    /* FEAT_03AF */
#define FEAT_BREW_POTION                                 944    /* FEAT_03B0 */
#define FEAT_SCRIBE_SCROLL                               945    /* FEAT_03B1 */
#define FEAT_CRAFT_WAND                                  946    /* FEAT_03B2 */
#define FEAT_DWARVEN_DEFENDER_DEFENSIVE_STANCE           947    /* FEAT_03B3 */
#define FEAT_DAMAGE_REDUCTION_6                          948    /* FEAT_03B4 */
#define FEAT_PRESTIGE_DEFENSIVE_AWARENESS_1              949    /* FEAT_03B5 */
#define FEAT_PRESTIGE_DEFENSIVE_AWARENESS_2              950    /* FEAT_03B6 */
#define FEAT_PRESTIGE_DEFENSIVE_AWARENESS_3              951    /* FEAT_03B7 */
#define FEAT_WEAPON_FOCUS_DWAXE                          952    /* FEAT_03B8 */
#define FEAT_WEAPON_SPECIALIZATION_DWAXE                 953    /* FEAT_03B9 */
#define FEAT_IMPROVED_CRITICAL_DWAXE                     954    /* FEAT_03BA */
#define FEAT_EPIC_DEVASTATING_CRITICAL_DWAXE             955    /* FEAT_03BB */
#define FEAT_EPIC_WEAPON_FOCUS_DWAXE                     956    /* FEAT_03BC */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_DWAXE            957    /* FEAT_03BD */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_DWAXE            958    /* FEAT_03BE */
#define FEAT_WEAPON_OF_CHOICE_DWAXE                      959    /* FEAT_03BF */
#define FEAT_USE_POISON                                  960    /* FEAT_03C0 */
#define FEAT_DRAGON_ARMOR                                961    /* FEAT_03C1 */
#define FEAT_DRAGON_ABILITIES                            962    /* FEAT_03C2 */
#define FEAT_DRAGON_IMMUNE_PARALYSIS                     963    /* FEAT_03C3 */
#define FEAT_DRAGON_IMMUNE_FIRE                          964    /* FEAT_03C4 */
#define FEAT_DRAGON_DIS_BREATH                           965    /* FEAT_03C5 */
#define FEAT_EPIC_FIGHTER                                966    /* FEAT_03C6 */
#define FEAT_EPIC_BARBARIAN                              967    /* FEAT_03C7 */
#define FEAT_EPIC_BARD                                   968    /* FEAT_03C8 */
#define FEAT_EPIC_CLERIC                                 969    /* FEAT_03C9 */
#define FEAT_EPIC_DRUID                                  970    /* FEAT_03CA */
#define FEAT_EPIC_MONK                                   971    /* FEAT_03CB */
#define FEAT_EPIC_PALADIN                                972    /* FEAT_03CC */
#define FEAT_EPIC_RANGER                                 973    /* FEAT_03CD */
#define FEAT_EPIC_ROGUE                                  974    /* FEAT_03CE */
#define FEAT_EPIC_SORCERER                               975    /* FEAT_03CF */
#define FEAT_EPIC_WIZARD                                 976    /* FEAT_03D0 */
#define FEAT_EPIC_ARCANE_ARCHER                          977    /* FEAT_03D1 */
#define FEAT_EPIC_ASSASSIN                               978    /* FEAT_03D2 */
#define FEAT_EPIC_BLACKGUARD                             979    /* FEAT_03D3 */
#define FEAT_EPIC_SHADOWDANCER                           980    /* FEAT_03D4 */
#define FEAT_EPIC_HARPER_SCOUT                           981    /* FEAT_03D5 */
#define FEAT_EPIC_DIVINE_CHAMPION                        982    /* FEAT_03D6 */
#define FEAT_EPIC_WEAPON_MASTER                          983    /* FEAT_03D7 */
#define FEAT_EPIC_PALE_MASTER                            984    /* FEAT_03D8 */
#define FEAT_EPIC_DWARVEN_DEFENDER                       985    /* FEAT_03D9 */
#define FEAT_EPIC_SHIFTER                                986    /* FEAT_03DA */
#define FEAT_EPIC_RED_DRAGON_DISC                        987    /* FEAT_03DB */
#define FEAT_EPIC_THUNDERING_RAGE                        988    /* FEAT_03DC */
#define FEAT_EPIC_TERRIFYING_RAGE                        989    /* FEAT_03DD */
#define FEAT_EPIC_EPIC_WARDING                           990    /* FEAT_03DE */
#define FEAT_PRESTIGE_MASTER_CRAFTER                     991    /* FEAT_03DF */
#define FEAT_PRESTIGE_SCROUNGER                          992    /* FEAT_03E0 */
#define FEAT_WEAPON_FOCUS_WHIP                           993    /* FEAT_03E1 */
#define FEAT_WEAPON_SPECIALIZATION_WHIP                  994    /* FEAT_03E2 */
#define FEAT_IMPROVED_CRITICAL_WHIP                      995    /* FEAT_03E3 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_WHIP              996    /* FEAT_03E4 */
#define FEAT_EPIC_WEAPON_FOCUS_WHIP                      997    /* FEAT_03E5 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_WHIP             998    /* FEAT_03E6 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_WHIP             999    /* FEAT_03E7 */
#define FEAT_WEAPON_OF_CHOICE_WHIP                      1000    /* FEAT_03E8 */
#define FEAT_EPIC_CHARACTER                             1001    /* FEAT_03E9 */
#define FEAT_EPIC_EPIC_SHADOWLORD                       1002    /* FEAT_03EA */
#define FEAT_EPIC_EPIC_FIEND                            1003    /* FEAT_03EB */
#define FEAT_PRESTIGE_DEATH_ATTACK_6                    1004    /* FEAT_03EC */
#define FEAT_PRESTIGE_DEATH_ATTACK_7                    1005    /* FEAT_03ED */
#define FEAT_PRESTIGE_DEATH_ATTACK_8                    1006    /* FEAT_03EE */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_4D6                1007    /* FEAT_03EF */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_5D6                1008    /* FEAT_03F0 */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_6D6                1009    /* FEAT_03F1 */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_7D6                1010    /* FEAT_03F2 */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_8D6                1011    /* FEAT_03F3 */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_9D6                1012    /* FEAT_03F4 */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_10D6               1013    /* FEAT_03F5 */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_11D6               1014    /* FEAT_03F6 */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_12D6               1015    /* FEAT_03F7 */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_13D6               1016    /* FEAT_03F8 */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_14D6               1017    /* FEAT_03F9 */
#define FEAT_BLACKGUARD_SNEAK_ATTACK_15D6               1018    /* FEAT_03FA */
#define FEAT_PRESTIGE_DEATH_ATTACK_9                    1019    /* FEAT_03FB */
#define FEAT_PRESTIGE_DEATH_ATTACK_10                   1020    /* FEAT_03FC */
#define FEAT_PRESTIGE_DEATH_ATTACK_11                   1021    /* FEAT_03FD */
#define FEAT_PRESTIGE_DEATH_ATTACK_12                   1022    /* FEAT_03FE */
#define FEAT_PRESTIGE_DEATH_ATTACK_13                   1023    /* FEAT_03FF */
#define FEAT_PRESTIGE_DEATH_ATTACK_14                   1024    /* FEAT_0400 */
#define FEAT_PRESTIGE_DEATH_ATTACK_15                   1025    /* FEAT_0401 */
#define FEAT_PRESTIGE_DEATH_ATTACK_16                   1026    /* FEAT_0402 */
#define FEAT_PRESTIGE_DEATH_ATTACK_17                   1027    /* FEAT_0403 */
#define FEAT_PRESTIGE_DEATH_ATTACK_18                   1028    /* FEAT_0404 */
#define FEAT_PRESTIGE_DEATH_ATTACK_19                   1029    /* FEAT_0405 */
#define FEAT_PRESTIGE_DEATH_ATTACK_20                   1030    /* FEAT_0406 */
#define FEAT_SNEAK_ATTACK_11                            1032    /* FEAT_0408 */
#define FEAT_SNEAK_ATTACK_12                            1033    /* FEAT_0409 */
#define FEAT_SNEAK_ATTACK_13                            1034    /* FEAT_040A */
#define FEAT_SNEAK_ATTACK_14                            1035    /* FEAT_040B */
#define FEAT_SNEAK_ATTACK_15                            1036    /* FEAT_040C */
#define FEAT_SNEAK_ATTACK_16                            1037    /* FEAT_040D */
#define FEAT_SNEAK_ATTACK_17                            1038    /* FEAT_040E */
#define FEAT_SNEAK_ATTACK_18                            1039    /* FEAT_040F */
#define FEAT_SNEAK_ATTACK_19                            1040    /* FEAT_0410 */
#define FEAT_SNEAK_ATTACK_20                            1041    /* FEAT_0411 */
#define FEAT_DRAGON_HDINCREASE_D6                       1042    /* FEAT_0412 */
#define FEAT_DRAGON_HDINCREASE_D8                       1043    /* FEAT_0413 */
#define FEAT_DRAGON_HDINCREASE_D10                      1044    /* FEAT_0414 */
#define FEAT_PRESTIGE_ENCHANT_ARROW_6                   1045    /* FEAT_0415 */
#define FEAT_PRESTIGE_ENCHANT_ARROW_7                   1046    /* FEAT_0416 */
#define FEAT_PRESTIGE_ENCHANT_ARROW_8                   1047    /* FEAT_0417 */
#define FEAT_PRESTIGE_ENCHANT_ARROW_9                   1048    /* FEAT_0418 */
#define FEAT_PRESTIGE_ENCHANT_ARROW_10                  1049    /* FEAT_0419 */
#define FEAT_PRESTIGE_ENCHANT_ARROW_11                  1050    /* FEAT_041A */
#define FEAT_PRESTIGE_ENCHANT_ARROW_12                  1051    /* FEAT_041B */
#define FEAT_PRESTIGE_ENCHANT_ARROW_13                  1052    /* FEAT_041C */
#define FEAT_PRESTIGE_ENCHANT_ARROW_14                  1053    /* FEAT_041D */
#define FEAT_PRESTIGE_ENCHANT_ARROW_15                  1054    /* FEAT_041E */
#define FEAT_PRESTIGE_ENCHANT_ARROW_16                  1055    /* FEAT_041F */
#define FEAT_PRESTIGE_ENCHANT_ARROW_17                  1056    /* FEAT_0420 */
#define FEAT_PRESTIGE_ENCHANT_ARROW_18                  1057    /* FEAT_0421 */
#define FEAT_PRESTIGE_ENCHANT_ARROW_19                  1058    /* FEAT_0422 */
#define FEAT_PRESTIGE_ENCHANT_ARROW_20                  1059    /* FEAT_0423 */
#define FEAT_EPIC_OUTSIDER_SHAPE                        1060    /* FEAT_0424 */
#define FEAT_EPIC_CONSTRUCT_SHAPE                       1061    /* FEAT_0425 */
#define FEAT_EPIC_SHIFTER_INFINITE_WILDSHAPE_1          1062    /* FEAT_0426 */
#define FEAT_EPIC_SHIFTER_INFINITE_WILDSHAPE_2          1063    /* FEAT_0427 */
#define FEAT_EPIC_SHIFTER_INFINITE_WILDSHAPE_3          1064    /* FEAT_0428 */
#define FEAT_EPIC_SHIFTER_INFINITE_WILDSHAPE_4          1065    /* FEAT_0429 */
#define FEAT_EPIC_SHIFTER_INFINITE_HUMANOID_SHAPE       1066    /* FEAT_042A */
#define FEAT_EPIC_BARBARIAN_DAMAGE_REDUCTION            1067    /* FEAT_042B */
#define FEAT_EPIC_DRUID_INFINITE_WILDSHAPE              1068    /* FEAT_042C */
#define FEAT_EPIC_DRUID_INFINITE_ELEMENTAL_SHAPE        1069    /* FEAT_042D */
#define FEAT_PRESTIGE_POISON_SAVE_EPIC                  1070    /* FEAT_042E */
#define FEAT_EPIC_SUPERIOR_WEAPON_FOCUS                 1071    /* FEAT_042F */
#define FEAT_WEAPON_FOCUS_TRIDENT                       1072    /* FEAT_0430 */
#define FEAT_WEAPON_SPECIALIZATION_TRIDENT              1073    /* FEAT_0431 */
#define FEAT_IMPROVED_CRITICAL_TRIDENT                  1074    /* FEAT_0432 */
#define FEAT_EPIC_DEVASTATING_CRITICAL_TRIDENT          1075    /* FEAT_0433 */
#define FEAT_EPIC_WEAPON_FOCUS_TRIDENT                  1076    /* FEAT_0434 */
#define FEAT_EPIC_WEAPON_SPECIALIZATION_TRIDENT         1077    /* FEAT_0435 */
#define FEAT_EPIC_OVERWHELMING_CRITICAL_TRIDENT         1078    /* FEAT_0436 */
#define FEAT_WEAPON_OF_CHOICE_TRIDENT                   1079    /* FEAT_0437 */
#define FEAT_PDK_RALLY                                  1080    /* FEAT_0438 */
#define FEAT_PDK_SHIELD                                 1081    /* FEAT_0439 */
#define FEAT_PDK_FEAR                                   1082    /* FEAT_043A */
#define FEAT_PDK_WRATH                                  1083    /* FEAT_043B */
#define FEAT_PDK_STAND                                  1084    /* FEAT_043C */
#define FEAT_PDK_INSPIRE_1                              1085    /* FEAT_043D */
#define FEAT_PDK_INSPIRE_2                              1086    /* FEAT_043E */
#define FEAT_MOUNTED_COMBAT                             1087    /* FEAT_043F */
#define FEAT_MOUNTED_ARCHERY                            1088    /* FEAT_0440 */
#define FEAT_HORSE_MENU                                 1089    /* FEAT_0441 */
#define FEAT_HORSE_MOUNT                                1090    /* FEAT_0442 */
#define FEAT_HORSE_DISMOUNT                             1091    /* FEAT_0443 */
#define FEAT_HORSE_PARTY_MOUNT                          1092    /* FEAT_0444 */
#define FEAT_HORSE_GATHER_MOUNTS                        1093    /* FEAT_0445 */
#define FEAT_HORSE_ASSIGN_MOUNT                         1094    /* FEAT_0446 */
#define FEAT_PALADIN_SUMMON_MOUNT                       1095    /* FEAT_0447 */
#define FEAT_DM_TOOL_01                                 1096    /* FEAT_0448 */
#define FEAT_DM_TOOL_02                                 1097    /* FEAT_0449 */
#define FEAT_DM_TOOL_03                                 1098    /* FEAT_044A */
#define FEAT_DM_TOOL_04                                 1099    /* FEAT_044B */
#define FEAT_DM_TOOL_05                                 1100    /* FEAT_044C */
#define FEAT_DM_TOOL_06                                 1101    /* FEAT_044D */
#define FEAT_DM_TOOL_07                                 1102    /* FEAT_044E */
#define FEAT_DM_TOOL_08                                 1103    /* FEAT_044F */
#define FEAT_DM_TOOL_09                                 1104    /* FEAT_0450 */
#define FEAT_DM_TOOL_10                                 1105    /* FEAT_0451 */
#define FEAT_PLAYER_TOOL_01                             1106    /* FEAT_0452 */
#define FEAT_PLAYER_TOOL_02                             1107    /* FEAT_0453 */
#define FEAT_PLAYER_TOOL_03                             1108    /* FEAT_0454 */
#define FEAT_PLAYER_TOOL_04                             1109    /* FEAT_0455 */
#define FEAT_PLAYER_TOOL_05                             1110    /* FEAT_0456 */
#define FEAT_PLAYER_TOOL_06                             1111    /* FEAT_0457 */
#define FEAT_PLAYER_TOOL_07                             1112    /* FEAT_0458 */
#define FEAT_PLAYER_TOOL_08                             1113    /* FEAT_0459 */
#define FEAT_PLAYER_TOOL_09                             1114    /* FEAT_045A */
#define FEAT_PLAYER_TOOL_10                             1115    /* FEAT_045B */


#endif /* _NX_NWN_CONST_FEATS_H_ */

/* vim: set sw=4: */
