#ifndef _CNWSCREATURE_H_
#define _CNWSCREATURE_H_
#include "nwndef.h"
#include "Vector.h"
#include "CExoString.h"
#include "CExoArrayList.h"
#include "CResRef.h"
#include "CNWSObject.h"
#include "CNWSCombatRound.h"
#include "nwnstructs.h"
#include "CNWSCreatureStats.h"

class CNWSCreature
{
public:
	int AIActionAnimalEmpathy(CNWSObjectActionNode *);
	int AIActionAppear(CNWSObjectActionNode *);
	int AIActionAreaWait(CNWSObjectActionNode *);
	int AIActionAttackObject(CNWSObjectActionNode *);
	int AIActionBarter(CNWSObjectActionNode *);
	int AIActionCastSpell(CNWSObjectActionNode *);
	int AIActionChangeFacingObject(CNWSObjectActionNode *);
	int AIActionChangeFacingPoint(CNWSObjectActionNode *);
	int AIActionCheckForceFollowObject(CNWSObjectActionNode *);
	int AIActionCheckInterAreaPathfinding(CNWSObjectActionNode *);
	int AIActionCheckMoveAwayFromLocation(CNWSObjectActionNode *);
	int AIActionCheckMoveAwayFromObject(CNWSObjectActionNode *);
	int AIActionCheckMoveToObjectRadius(CNWSObjectActionNode *);
	int AIActionCheckMoveToObject(CNWSObjectActionNode *);
	int AIActionCheckMoveToPointRadius(CNWSObjectActionNode *);
	int AIActionCheckMoveToPoint(CNWSObjectActionNode *);
	int AIActionCounterSpell(CNWSObjectActionNode *);
	int AIActionDisappear(CNWSObjectActionNode *);
	int AIActionDisarmTrap(CNWSObjectActionNode *);
	int AIActionDrive(CNWSObjectActionNode *);
	int AIActionDropItem(CNWSObjectActionNode *);
	int AIActionEncounterCreatureDestroySelf();
	int AIActionEquipItem(CNWSObjectActionNode *);
	int AIActionExamineTrap(CNWSObjectActionNode *);
	int AIActionExamine(CNWSObjectActionNode *);
	int AIActionFlagTrap(CNWSObjectActionNode *);
	int AIActionForceFollowObject(CNWSObjectActionNode *);
	int AIActionHeal(CNWSObjectActionNode *);
	int AIActionItemCastSpell(CNWSObjectActionNode *);
	int AIActionJumpToObject(CNWSObjectActionNode *);
	int AIActionJumpToPoint(CNWSObjectActionNode *);
	int AIActionMoveToPoint(CNWSObjectActionNode *);
	int AIActionOrientCamera(CNWSObjectActionNode *);
	int AIActionPickPocket(CNWSObjectActionNode *);
	int AIActionPickUpItem(CNWSObjectActionNode *);
	int AIActionRandomWalk(CNWSObjectActionNode *);
	int AIActionRecoverTrap(CNWSObjectActionNode *);
	int AIActionRepositoryMove(CNWSObjectActionNode *);
	int AIActionRest(CNWSObjectActionNode *);
	int AIActionSetTrap(CNWSObjectActionNode *);
	int AIActionSit(CNWSObjectActionNode *);
	int AIActionTaunt(CNWSObjectActionNode *);
	int AIActionUnequipItem(CNWSObjectActionNode *);
	int AIActionWaitForEndOfRound(CNWSObjectActionNode *);
	int AIUpdate();
	int AcquireItem(CNWSItem **, unsigned long, unsigned long, unsigned char, unsigned char, int, int);
	int ActionManager(unsigned long);
	int ActivityManager(unsigned long);
	int AddAnimalEmpathyAction(unsigned long);
	int AddAppearActions(int);
	int AddAreaOfEffect(unsigned long);
	int AddAssociate(unsigned long, unsigned short);
	int AddAttackActions(unsigned long, int, int, int);
	int AddCastSpellActions(unsigned long, int, int, int, int, Vector, unsigned long, int, int, int, unsigned char, int, int, int, unsigned char);
	int AddCounterSpellActions(unsigned long);
	int AddDisappearActions(int, int);
	int AddDriveAction(unsigned short, Vector const &, int, int, int, int);
	int AddDropItemActions(unsigned long, Vector, int);
	int AddEquipItemActions(CNWSItem *, unsigned long, int, int, unsigned long);
	int AddGold(int, int);
	int AddHealActions(unsigned long, unsigned long, int);
	int AddItemCastSpellActions(unsigned long, int, int, Vector, unsigned long, int);
	int AddMoveToPointActionToFront(unsigned short, Vector, unsigned long, unsigned long, int, float, float, int, int, int, int, int, int);
	int AddMoveToPointAction(unsigned short, Vector, unsigned long, unsigned long, int, float, float, int, int, int, int, int, int);
	int AddPathfindingWaitActionToFront(unsigned short);
	int AddPickPocketActions(unsigned long);
	int AddPickUpItemActions(unsigned long, unsigned long, unsigned char, unsigned char);
	int AddRepositoryMoveActions(CNWSItem *, unsigned long, unsigned char, unsigned char);
	int AddSitActions(unsigned long);
	int AddTauntActions(unsigned long);
	int AddToArea(CNWSArea *, float, float, float, int);
	int AddToAssociateList(unsigned long);
	int AddToInvitationsIgnored(unsigned long);
	int AddToInvitationsOffered(unsigned long);
	int AddToPVPList(unsigned long);
	int AddToPersonalReputationList(unsigned long, int, int, float);
	int AddToVisibleList(unsigned long, int, int, unsigned char, int);
	int AddTrapActions(unsigned long, unsigned char, unsigned long, Vector, unsigned long);
	int AddUnequipActions(CNWSItem *, unsigned long, unsigned char, unsigned char, int, int, unsigned long);
	int AddUseTalentAtLocationActions(int, int, Vector, unsigned char, unsigned long, int, unsigned char, unsigned char);
	int AddUseTalentOnObjectActions(int, int, unsigned long, unsigned char, unsigned long, int, unsigned char, unsigned char);
	int AdjustReputation(int, int);
	int ApplyDeathExperience();
	int ApplyDiseasePayload(CGameEffect *, unsigned long, unsigned long);
	int ApplyOnHitAbilityDamage(CNWSObject *, CNWItemProperty *);
	int ApplyOnHitBlindness(CNWSObject *, int);
	int ApplyOnHitCastSpell(CNWSObject *, CNWItemProperty *, CNWSItem *);
	int ApplyOnHitConfusion(CNWSObject *, int);
	int ApplyOnHitDaze(CNWSObject *, int);
	int ApplyOnHitDeafness(CNWSObject *, int);
	int ApplyOnHitDeathAttack(CNWSObject *, int);
	int ApplyOnHitDisease(CNWSObject *, CNWItemProperty *);
	int ApplyOnHitDispelMagic(CNWSObject *, CNWItemProperty *);
	int ApplyOnHitDispelMagic(CNWSObject *, unsigned long);
	int ApplyOnHitDominate(CNWSObject *, int);
	int ApplyOnHitDoom(CNWSObject *, int);
	int ApplyOnHitFear(CNWSObject *, int);
	int ApplyOnHitGreaterDispel(CNWSObject *, unsigned long);
	int ApplyOnHitHold(CNWSObject *, int);
	int ApplyOnHitKnock(CNWSObject *, unsigned long);
	int ApplyOnHitLesserDispel(CNWSObject *, unsigned long);
	int ApplyOnHitLevelDrain(CNWSObject *, CNWItemProperty *);
	int ApplyOnHitMordysDisjunction(CNWSObject *, unsigned long);
	int ApplyOnHitPoison(CNWSObject *, CNWItemProperty *);
	int ApplyOnHitSilence(CNWSObject *, int);
	int ApplyOnHitSlayAlignmentGroup(CNWSObject *, CNWItemProperty *);
	int ApplyOnHitSlayAlignment(CNWSObject *, CNWItemProperty *);
	int ApplyOnHitSlayRacialGroup(CNWSObject *, CNWItemProperty *);
	int ApplyOnHitSleep(CNWSObject *, int);
	int ApplyOnHitSlow(CNWSObject *, int);
	int ApplyOnHitStun(CNWSObject *, int);
	int ApplyOnHitVampiricRegeneration(CNWSObject *, CNWItemProperty *);
	int ApplyOnHitVorpal(CNWSObject *, CNWItemProperty *);
	int ApplyOnHitWounding(CNWSObject *, CNWItemProperty *);
	int ApplyPoisonPayload(CGameEffect *, unsigned long, unsigned long);
	int ApplyWounding(CGameEffect *);
	int AsNWSCreature();
	int AutoCloseGUIPanels(int);
	int BringAssociatesToNewFaction(int);
	int BroadcastAssociateCommand(int);
	int BroadcastAttackDataToParty(CNWCCMessageData *, CNWSCombatAttackData *, CNWSCreature *);
	int BroadcastAttackOfOpportunity(unsigned long, int);
	int BroadcastBattleCry();
	int BroadcastCombatStateToParty();
	int BroadcastDamageDataToParty(CNWCCMessageData *, CNWSCreature *);
	int BroadcastDeathDataToParty(CNWCCMessageData *, CNWSCreature *);
	int BroadcastFloatyData(CNWCCMessageData *);
	int BroadcastSavingThrowData(CNWCCMessageData *);
	int BroadcastSkillData(CNWCCMessageData *);
	int BroadcastSpellCast(unsigned long, unsigned char, unsigned short);
	int BroadcastVoiceChat(unsigned char);
	int BroadcastWhirlwindAttack(int);
	int BumpFriends(CNWSCreature *, Vector const &, Vector const &);
	int CalculateDamagePower(CNWSObject *, int);
	int CalculateDeathExperience(int, int);
	int CalculateMaxElementalDamage(CNWSObject *, int);
	int CalculatePersonalReputationAdjustment(unsigned long);
	int CalculateProjectileTimeToTarget(Vector, int);
	int CalculateSpellSaveDC(int);
	int CanEquipItem(CNWSItem *, unsigned long *, int, int, int, CNWSPlayer *);
	int CanEquipMiscellaneous(CNWSItem *, unsigned long *, int, int);
	int CanEquipShield(CNWSItem *, int, int);
	int CanEquipWeapon(CNWSItem *, unsigned long *, int, int, CNWSPlayer *);
	int CanUnEquipWeapon(CNWSItem *);
	int CanUseItem(CNWSItem *, int);
	int CancelAction(unsigned short, unsigned short);
	int CancelGoldTransfer(unsigned long);
	int CancelRest(unsigned short);
	int CheckInventoryForPlotItems();
	int CheckItemAlignmentRestrictions(CNWSItem *);
	int CheckItemClassRestrictions(CNWSItem *);
	int CheckItemRaceRestrictions(CNWSItem *);
	int CheckMasterIsValid(unsigned long, unsigned long);
	int CheckProficiencies(CNWSItem *, unsigned long);
	int CheckUseMagicDeviceSkill(CNWSItem *, int);
	int CheckVisibleList(unsigned long);
	int CleanInvitationLists(int);
	int CleanOutPersonalReputationList();
	int ClearAction(CNWSObjectActionNode *, int);
	int ClearActivities(int);
	int ClearAutoMapData();
	int ClearHostileActionsVersus(CNWSCreature *);
	int ClearPersonalReputation(unsigned long);
	int ClearVisibleList();
	int ComputeAIStateOnAction(int, unsigned long);
	int ComputeAIState();
	int ComputeArmourClass(CNWSItem *, int, int);
	int ComputeModifiedMovementRate();
	int ComputeSpellRange(CExoString, unsigned long);
	int ComputeTotalEquippedWeight();
	int ComputeTotalWalkDistance();
	int ComputeTotalWeightCarried();
	int ConvertModeToggleQuickButton(CNWSQuickbarButton *);
	int CopyQuickButtonsFromDM(CNWSPlayer *);
	int CreateDefaultQuickButtonsDM();
	int CreateDefaultQuickButtons_AddFeat(unsigned char &, unsigned short, int);
	int CreateDefaultQuickButtons_CheckItem(CNWSItem *, unsigned long &, unsigned long &, unsigned long &, unsigned long &);
	int CreateDefaultQuickButtons();
	int CutWaypointPath();
	int DMClearScripts(int);
	int DMResetClearedScripts(int);
	int DecrementSpellReadyCount(unsigned long, unsigned char, unsigned char, unsigned char, unsigned char);
	int DesiredAttackRange(unsigned long, int);
	int DestroyEquippedItems();
	int DisplayFloatyDataToSelf(unsigned long);
	int DoCombatStep(unsigned char, int, unsigned long);
	int DoDamage(int);
	int DoListenDetection(CNWSCreature *, int);
	int DoPerceptionUpdateOnCreature(CNWSCreature *, int);
	int DoSpotDetection(CNWSCreature *, int);
	int DoStealthDetection(CNWSCreature *, int, int *, int *, int);
	int DriveUpdateLocation(int);
	int DumpToLog();
	int EquipItem(unsigned long, CNWSItem *, int, int);
	int EquipMostDamagingAmmunition(unsigned long, CNWSItem *);
	int EquipMostDamagingMeleeWeapon(unsigned long, int, int);
	int EquipMostDamagingRangedWeapon(unsigned long);
	int EquipMostEffectiveArmor();
	int EvaluateLock(CNWSObject *, int);
	int EventHandler(unsigned long, unsigned long, void *, unsigned long, unsigned long);
	int ExternalResolveAttack(unsigned long, int);
	int FailedOpenInformAssociates();
	int ForceMoveToPoint(CNWSForcedAction *);
	int GetAIStateActee();
	int GetAIStateAction();
	int GetAIStateActivities();
	int GetAIState();
	int GetActionQueueList();
	int GetActivityLocked(unsigned long);
	int GetActivity(int);
	int GetAlreadyRemovedFromEncounter();
	int GetAmbientAnimationState();
	int GetAmmunitionAvailable(int);
	int GetAnimalCompanionCreatureType();
	int GetAnimalCompanionId();
	int GetAnimalCompanionName();
	int GetAppearance();
	int GetAreaOfEffectObjects();
	int GetArmorClass();
	int GetAssociateId(unsigned short, int);
	int GetAssociateList();
	int GetAssociateType();
	int GetAttackResultHit(CNWSCombatAttackData *);
	int GetAttackTarget();
	int GetAttemptedAttackTarget();
	int GetAttemptedSpellTarget();
	int GetAutoMapAreaList();
	int GetAutoMapTileData();
	int GetBarterInfo(int);
	int GetBlind();
	int GetBlindsightDistance();
	int GetBodyBagAppearance();
	int GetBodyBagId();
	int GetBodyBag();
	int GetBroadcastedAOOTo();
	int GetCalculateNPCWeight();
	int GetCanSlayAlignment(CNWSObject *, CNWItemProperty *);
	int GetCombatMode();
	int GetCombatRound();
	int GetCombatStateTimer();
	int GetCombatState();
	int GetCounterSpellTarget();
	int GetCreatureReputation(unsigned long, int, int);
	int GetCreatureSize();
	int GetCreatureState();
	int GetCurrentItemContainer();
	int GetCutsceneCameraMode();
	int GetCutsceneCameraMovementRateFactor();
	int GetCutsceneGhost();
	int GetDMCharacter();
	int GetDamageFlags();
	int GetDecayTime();
	int GetDefensiveCastingMode();
	int GetDesiredAreaId();
	int GetDesiredAreaLocation();
	int GetDesiredAreaUpdateComplete();
	int GetDesiredCombatMode();
	int GetDetectMode();
	int GetDialogInterruptable();
	int GetDialogResref();
	int GetDisarmable();
	int GetDisplayName();
	int GetDominatedCreatureId();
	int GetDriveModeMoveFactor();
	int GetDriveMode();
	int GetDropItemAnimationPlayed();
	int GetEffectIcons();
	int GetEffectSpellId();
	int GetEncounterId();
	int GetEncumbranceState();
	int GetEquipArrayIndex();
	int GetEquippedWeight();
	int GetExternalCombatModeEnabled();
	int GetFacingAndAnimationDone();
	int GetFactionId();
	int GetFaction();
	int GetFamiliarCreatureType();
	int GetFamiliarId();
	int GetFamiliarName();
	int GetFilteredEffectList(unsigned char);
	int GetFirstName();
	int GetFlanked(CNWSCreature *);
	int GetFlatFooted();
	int GetFootstepType();
	int GetForcedWalk();
	int GetFreeWill();
	int GetGender();
	int GetGoingToBeAttackedBy();
	int GetGold();
	int GetHasArms();
	int GetHasInvisbilityEffectApplied();
	int GetHasLegs();
	int GetHasted();
	int GetHealAnimationPlayed();
	int GetHenchmanId(int);
	int GetHenchmanIndex(unsigned long);
	int GetInSubAreasArray();
	int GetInTransit();
	int GetInitiativeExpired();
	int GetInitiativeRoll();
	int GetInventory();
	int GetInvisible(CNWSObject *, int);
	int GetInvitedToPartyBy();
	int GetInvitedToParty();
	int GetIsAbleToPossessFamiliar();
	int GetIsCreatureBumpable(CNWSCreature *);
	int GetIsDiseased();
	int GetIsExcited();
	int GetIsImmortal();
	int GetIsInInvitationsIgnored(unsigned long);
	int GetIsInInvitationsOffered(unsigned long);
	int GetIsInMelee();
	int GetIsInUseRange(unsigned long, float, int);
	int GetIsPoisoned();
	int GetIsPolymorphLocked();
	int GetIsPolymorphed();
	int GetIsPolymorphing();
	int GetIsPossessedFamiliar();
	int GetIsWeaponEffective(unsigned long, int);
	int GetItemCastSpellBroadcastAOO();
	int GetItemContainerArrayIndex();
	int GetItemCount(int);
	int GetItemRepository();
	int GetJournal();
	int GetJumpedRecently();
	int GetLastAmmunitionWarning();
	int GetLastAssociateCommand();
	int GetLastBlockingDoor();
	int GetLastCounterDomainLevel();
	int GetLastCounterMetaType();
	int GetLastCounterSpellClass();
	int GetLastCounterSpellID();
	int GetLastHideRoll();
	int GetLastItemCastSpellLevel();
	int GetLastItemCastSpell();
	int GetLastListenRoll();
	int GetLastMoveSilentlyRoll();
	int GetLastName();
	int GetLastPerceived();
	int GetLastPerceptionHeard();
	int GetLastPerceptionInaudible();
	int GetLastPerceptionSeen();
	int GetLastPerceptionVanished();
	int GetLastPickupFailed();
	int GetLastSpellCastItem();
	int GetLastSpellProjectileTime();
	int GetLastSpellUnReadied();
	int GetLastSpotRoll();
	int GetLastTrapDetected();
	int GetListenCheckDistance();
	int GetLockAnimationPlayed();
	int GetLockOrientationToObject();
	int GetLootable();
	int GetMagicalArrowsEquipped();
	int GetMagicalBoltsEquipped();
	int GetMagicalBulletsEquipped();
	int GetMasterId();
	int GetMaxHitPoints(int);
	int GetMode(unsigned char);
	int GetModelType();
	int GetMovementRateFactor();
	int GetNearestEnemy(float, unsigned long, int, int);
	int GetNoPermDeath();
	int GetNonPolymorphCONBase();
	int GetNonPolymorphDEXBase();
	int GetNonPolymorphSTRBase();
	int GetNumAreas();
	int GetNumAssociatesOfType(unsigned short);
	int GetNumCharSheetViewers();
	int GetNumCounterSpellingCreatures(unsigned long);
	int GetNumInvited();
	int GetOnCreationScriptExecuted();
	int GetOriginalFactionId();
	int GetPVPList();
	int GetPVPPlayerLikesMe(unsigned long);
	int GetPVPReputation(unsigned long);
	int GetPassiveAttackBehaviour();
	int GetPathfindInformation();
	int GetPendingRealization();
	int GetPersonalReputationList();
	int GetPickUpItemAnimationPlayed();
	int GetPlayerCharacter();
	int GetPolymorphSpellId1();
	int GetPolymorphSpellId2();
	int GetPolymorphSpellId3();
	int GetPonyRide();
	int GetPortrait();
	int GetPreDominationFactionId();
	int GetPrePolymorphCON();
	int GetPrePolymorphDEX();
	int GetPrePolymorphSTR();
	int GetPreferredAttackDistance();
	int GetQuickbarButton(unsigned char);
	int GetQuickbarInitialized();
	int GetRangeWeaponEquipped();
	int GetRelativeWeaponSize(CNWSItem *);
	int GetRepositoryArrayIndex();
	int GetReputationList();
	int GetRunRate();
	int GetScriptName(int);
	int GetSilent();
	int GetSittingObject();
	int GetSlowed();
	int GetSoundSet();
	int GetSpellIdentifiedList();
	int GetSpellOrHealActionQueued();
	int GetSpellTarget();
	int GetSpotCheckDistance();
	int GetStandardFactionReputation(int);
	int GetStats();
	int GetStealAnimationPlayed();
	int GetStealAttemptDetected();
	int GetStealthMode();
	int GetSummonedAnimalCompanion();
	int GetSummonedCreatureId();
	int GetSummonedFamiliar();
	int GetTauntAnimationPlayed();
	int GetTaunt();
	int GetTileExplored(unsigned long, int, int);
	int GetTotalEffectBonus(unsigned char, CNWSObject *, int, int, unsigned char, unsigned char, unsigned char, unsigned char, int);
	int GetTotalWeightCarried();
	int GetTrapAnimationPlayed();
	int GetTurnResistanceHD();
	int GetUnarmed();
	int GetUnlockAnimationPlayed();
	int GetUpdateCombatInformation();
	int GetUpdateDisplayName();
	int GetUseMonkAbilities();
	int GetUseRange(unsigned long, Vector &, float &);
	int GetVisibilityList();
	int GetVisibleListElement(unsigned long);
	int GetVisionType();
	int GetWalkAnimation();
	int GetWalkRate();
	int GetWeaponPower(CNWSObject *, int);
	int GetWeaponScale();
	int HandleSubAreaStateChanges(CExoArrayList<unsigned long> *, CExoArrayList<unsigned long> *, int);
	int InitialisePVPList();
	int InitializeQuickbar();
	int IsAIState(unsigned short);
	int IsHelpless();
	int LearnScroll(unsigned long);
	int LoadAssociateList(CResGFF *, CResStruct *);
	int LoadAutoMapData(CResGFF *, CResStruct *);
	int LoadCreature(CResGFF *, CResStruct *, int, int, int, int);
	int LoadFromTemplate(CResRef, CExoString *);
	int LoadPersonalReputationList(CResGFF *, CResStruct *);
	int LoadPolymorphData(CResGFF *, CResStruct *, int);
	int LoadQuickBarHack(CExoString);
	int LoadQuickButtons(CResGFF *, CResStruct *);
	int MaxAttackRange(unsigned long, int, int);
	int MergeItem(CNWSItem *, CNWSItem *);
	int NotifyAssociateActionToggle(int);
	int PacifyCreature();
	int PacifyCreature(unsigned long);
	int PayToIdentifyItem(unsigned long, unsigned long);
	int Polymorph(int, CGameEffect *, int);
	int PossessCreatureDM(unsigned long, unsigned char);
	int PossessCreature(unsigned long);
	int PossessFamiliar();
	int PostProcess();
	int ProcessMasterDeathForAssociates();
	int ProcessPendingCombatActions();
	int QuickbarButton_RemoveItem(unsigned long);
	int QuickbarButton_RemoveSpell(unsigned long);
	int ReadItemsFromGff(CResGFF *, CResStruct *, int, int);
	int ReadScriptsFromGff(CResGFF *, CResStruct *);
	int RealizeAssociateList();
	int ReceiveAssociateCommand(int);
	int RecomputeAmbientAnimationState();
	int RelayQuickChatCommandToAssociates(unsigned short);
	int RemoveAllAssociates();
	int RemoveAreaOfEffect(unsigned long);
	int RemoveAssociate(unsigned long);
	int RemoveBadEffects();
	int RemoveCharmEffectsByFactionID(int, int);
	int RemoveCharmEffectsByOBJECTID(unsigned long, int);
	int RemoveCombatInvisibilityEffects();
	int RemoveDominationEffect();
	int RemoveDomination();
	int RemoveFromArea(int);
	int RemoveFromAssociateList(unsigned long);
	int RemoveFromInvitationsOffered(unsigned long);
	int RemoveFromPVPList(unsigned long);
	int RemoveFromVisibleList(unsigned long);
	int RemoveGold(int, int);
	int RemoveItemFromRepository(CNWSItem *, int);
	int RemoveItem(CNWSItem *, int, int, int, int);
	int RemoveSleepEffects();
	int RemoveSpellActionFromRound();
	int RemoveWoundingEffects();
	int ReplyToInvitation(int, unsigned long);
	int ReprocessAssociateList();
	int RequestBuy(unsigned long, unsigned long, unsigned long);
	int RequestSell(unsigned long, unsigned long);
	int ResetItemPossessor();
	int ResetPCDominatedScripts();
	int ResetUpdateTimes(unsigned long, unsigned long);
	int ResolveAmmunition(unsigned long);
	int ResolveAttackRoll(CNWSObject *);
	int ResolveAttack(unsigned long, int, int);
	int ResolveCachedSpecialAttacks();
	int ResolveDamageShields(CNWSCreature *);
	int ResolveDamage(CNWSObject *);
	int ResolveDeathAttack(CNWSCreature *);
	int ResolveDefensiveEffects(CNWSObject *, int);
	int ResolveElementalDamage(CNWSObject *);
	int ResolveInitiative();
	int ResolveItemCastSpell(CNWSObject *);
	int ResolveMeleeAnimations(int, int, CNWSObject *, int);
	int ResolveMeleeAttack(CNWSObject *, int, int);
	int ResolveMeleeSpecialAttack(int, int, CNWSObject *, int);
	int ResolveOnHitEffect(CNWSObject *, int, int);
	int ResolveOnHitVisuals(CNWSObject *);
	int ResolvePostMeleeDamage(CNWSObject *);
	int ResolvePostRangedDamage(CNWSObject *);
	int ResolveRangedAnimations(CNWSObject *, int);
	int ResolveRangedAttack(CNWSObject *, int, int);
	int ResolveRangedMiss(CNWSObject *);
	int ResolveRangedSpecialAttack(CNWSObject *, int);
	int ResolveSafeProjectile(unsigned long, int);
	int ResolveSituationalModifiers(CNWSObject *);
	int ResolveSneakAttack(CNWSCreature *);
	int Rest(int, int);
	int RestoreCutsceneVars();
	int RestoreItemPropertiesInRepository(CItemRepository *);
	int RestoreItemProperties();
	int RunEquip(unsigned long, unsigned long, unsigned long);
	int RunUnequip(unsigned long, unsigned long, unsigned char, unsigned char, int, unsigned long);
	int SaveAssociateList(CResGFF *, CResStruct *);
	int SaveAutoMapData(CResGFF *, CResStruct *);
	int SaveCreature(CResGFF *, CResStruct *, int, int, int);
	int SavePersonalReputationList(CResGFF *, CResStruct *);
	int SaveQuickBarHack(CExoString);
	int SaveQuickButtons(CResGFF *, CResStruct *);
	int SavingThrowRoll(unsigned char, unsigned short, unsigned char, unsigned long, int, unsigned short, int);
	int SawTrapInformAssociates(unsigned long);
	int SendFeedbackMessage(unsigned short, CNWCCMessageData *, CNWSPlayer *);
	int SendFeedbackString(CExoString, CNWSPlayer *);
	int SetAIStateFlag(unsigned short, int);
	int SetAIState(unsigned short);
	int SetActivityLocked(unsigned long, int);
	int SetActivity(int, int);
	int SetAlive();
	int SetAllTilesExplored(unsigned long, int);
	int SetAlreadyRemovedFromEncounter(int);
	int SetAmbientAnimationState(unsigned char);
	int SetAnimalCompanionCreatureType(int);
	int SetAnimalCompanionName(CExoString);
	int SetAnimation(int);
	int SetAssociateListenPatterns();
	int SetAssociateType(unsigned short);
	int SetAssociatesToForgetAggression(unsigned long);
	int SetAttackTarget(unsigned long);
	int SetAttemptedAttackTarget(unsigned long);
	int SetAttemptedSpellTarget(unsigned long);
	int SetAutoMapData(int, unsigned long *, unsigned char **);
	int SetBlindsightDistance(float);
	int SetBodyBagId(unsigned long);
	int SetBodyBag(unsigned char);
	int SetBroadcastedAOOTo(int);
	int SetCalculateNPCWeight(int);
	int SetCombatMode(unsigned char, int);
	int SetCombatState(int);
	int SetCounterSpellTarget(unsigned long);
	int SetCreatureSize(int);
	int SetCreatureState(unsigned char);
	int SetCurrentItemContainer(unsigned long);
	int SetCutsceneCameraMode(int);
	int SetCutsceneCameraMovementRateFactor(float);
	int SetCutsceneGhost(int);
	int SetDMCharacter(int);
	int SetDead();
	int SetDecayTime(unsigned long);
	int SetDefensiveCastingMode(unsigned char);
	int SetDesiredAreaId(unsigned long);
	int SetDesiredAreaLocation(Vector);
	int SetDesiredAreaUpdateComplete(int);
	int SetDesiredCombatMode(unsigned char);
	int SetDetectMode(unsigned char);
	int SetDisarmable(int);
	int SetDisplayName(CExoString);
	int SetDriveModeMoveFactor(float);
	int SetDriveMode(int);
	int SetDropItemAnimationPlayed(int);
	int SetEffectSpellId(unsigned long);
	int SetEncounterId(unsigned long);
	int SetEncumbranceState(int);
	int SetEquipArrayIndex(unsigned short);
	int SetEquippedWeight(int);
	int SetExcitedState(unsigned char);
	int SetExternalCombatModeEnabled(int);
	int SetFacingAndAnimationDone(int);
	int SetFactionId(int);
	int SetFamiliarCreatureType(int);
	int SetFamiliarName(CExoString);
	int SetFootstepType(int);
	int SetForcedWalk(int);
	int SetGoingToBeAttackedBy(unsigned long);
	int SetGold(int);
	int SetHasArms(int);
	int SetHasLegs(int);
	int SetHasted(int);
	int SetHealAnimationPlayed(int);
	int SetId(unsigned long);
	int SetInTransit(int);
	int SetInitiativeExpired(int);
	int SetInitiativeRoll(unsigned char);
	int SetInvitedToPartyBy(unsigned long);
	int SetInvitedToParty(int);
	int SetIsDiseased(int);
	int SetIsImmortal(int);
	int SetIsPoisoned(int);
	int SetIsPolymorphed(int);
	int SetItemCastSpellBroadcastAOO(int);
	int SetItemContainerArrayIndex(unsigned short);
	int SetJumpedRecently(int);
	int SetLastAmmunitionWarning(int);
	int SetLastAssociateCommand(int);
	int SetLastBlockingDoor(unsigned long);
	int SetLastCounterDomainLevel(unsigned char);
	int SetLastCounterMetaType(unsigned char);
	int SetLastCounterSpellClass(unsigned char);
	int SetLastCounterSpellID(int);
	int SetLastHearbeatTime(unsigned long, unsigned long);
	int SetLastHideRoll(unsigned char);
	int SetLastItemCastSpellLevel(int);
	int SetLastItemCastSpell(int);
	int SetLastListenRoll(unsigned char);
	int SetLastMoveSilentlyRoll(unsigned char);
	int SetLastPerceived(unsigned long);
	int SetLastPerceptionHeard(int);
	int SetLastPerceptionInaudible(int);
	int SetLastPerceptionSeen(int);
	int SetLastPerceptionVanished(int);
	int SetLastPickupFailed(int);
	int SetLastSpellCastItem(unsigned long);
	int SetLastSpellUnReadied(int);
	int SetLastSpotRoll(unsigned char);
	int SetLastTrapDetected(unsigned long);
	int SetListenCheckDistance(float);
	int SetLockAnimationPlayed(int);
	int SetLockOrientationToObject(unsigned long);
	int SetLootable(int);
	int SetMagicalArrowsEquipped(int);
	int SetMagicalBoltsEquipped(int);
	int SetMagicalBulletsEquipped(int);
	int SetMasterId(unsigned long);
	int SetMaxListenCheckDistance(float);
	int SetMaxSpotCheckDistance(float);
	int SetMode(unsigned char, int);
	int SetModelType(CExoString);
	int SetMovementRateFactor(float);
	int SetNoPermDeath(int);
	int SetNumAreas(int);
	int SetNumCharSheetViewers(int);
	int SetOnCreationScriptExecuted(int);
	int SetOriginalFactionId(int);
	int SetPCDominatedScripts();
	int SetPVPPlayerLikesMe(unsigned long, int, int);
	int SetPassiveAttackBehaviour(int);
	int SetPendingRealization(int);
	int SetPersonalReputation(CExoArrayList<CNWSPersonalReputation> *);
	int SetPickUpItemAnimationPlayed(int);
	int SetPlayerCharacter(int);
	int SetPolymorphLocked(int);
	int SetPonyRide(int);
	int SetPortraitId(unsigned short);
	int SetPortrait(CResRef);
	int SetPreDominationFactionId(int);
	int SetPrePolymorphCON(int);
	int SetPrePolymorphDEX(int);
	int SetPrePolymorphSTR(int);
	int SetPreferredAttackDistance(float);
	int SetQuickbarButton_AssociateCommand(unsigned char, int, unsigned short, unsigned long);
	int SetQuickbarButton_CommandLine(unsigned char, CExoString const &, CExoString const &);
	int SetQuickbarButton_DM_General_ResRefParam(unsigned char, unsigned char, CResRef const &);
	int SetQuickbarButton_DungeonMaster_CreateCreature(unsigned char, CResRef const &, CExoString const &);
	int SetQuickbarButton_DungeonMaster_CreateEncounter(unsigned char, CResRef const &, CExoString const &);
	int SetQuickbarButton_DungeonMaster_CreateItem(unsigned char, CResRef const &, CExoString const &);
	int SetQuickbarButton_DungeonMaster_CreatePlaceable(unsigned char, CResRef const &, CExoString const &);
	int SetQuickbarButton_DungeonMaster_CreatePortal(unsigned char, CResRef const &, CExoString const &);
	int SetQuickbarButton_DungeonMaster_CreateTrigger(unsigned char, CResRef const &, CExoString const &);
	int SetQuickbarButton_DungeonMaster_CreateWaypoint(unsigned char, CResRef const &, CExoString const &);
	int SetQuickbarButton_GeneralINTParam(unsigned char, unsigned char, int);
	int SetQuickbarButton_GeneralNoParam(unsigned char, unsigned char);
	int SetQuickbarButton_Item(unsigned char, unsigned long, int, unsigned long);
	int SetQuickbarButton_SpellLikeAbility(unsigned char, unsigned long, unsigned char);
	int SetQuickbarButton_Spell(unsigned char, unsigned char, unsigned long, unsigned char, unsigned char);
	int SetRepositoryArrayIndex(unsigned short);
	int SetReputation(CExoArrayList<int> *);
	int SetScriptName(int, CExoString);
	int SetSilent(int);
	int SetSittingObject(unsigned long);
	int SetSlowed(int);
	int SetSoundSet(unsigned short);
	int SetSpellTarget(unsigned long);
	int SetSpotCheckDistance(float);
	int SetStandardFactionReputation(int, int);
	int SetStealAnimationPlayed(int);
	int SetStealAttemptDetected(int);
	int SetStealthMode(unsigned char);
	int SetSummonedAnimalCompanion(int);
	int SetSummonedFamiliar(int);
	int SetTauntAnimationPlayed(int);
	int SetTaunt(int);
	int SetTileExplored(unsigned long, int, int);
	int SetTrapAnimationPlayed(int);
	int SetUnlockAnimationPlayed(int);
	int SetUpdateCombatInformation(int);
	int SetUpdateDisplayName(int);
	int SetVisionType(unsigned char);
	int SetWalkAnimation(unsigned char);
	int SetWeaponScale(float);
	int SignalMeleeDamage(CNWSObject *, int);
	int SignalRangedDamage(CNWSObject *, int);
	int SpawnInHeartbeatPerception(int);
	int SplitItem(CNWSItem *, int);
	int StartBarter(unsigned long, unsigned long, int);
	int StartGuiTimingBar(unsigned long, unsigned char);
	int StopGuiTimingBar();
	int StoreCutsceneVars();
	int SummonAnimalCompanion();
	int SummonAssociate(CResRef, CExoString, unsigned short);
	int SummonFamiliar();
	int TerminateClientSidePath(int);
	int TestAIStateAsMode(int);
	int ToggleMode(unsigned char);
	int TransferGold(unsigned long, Vector, unsigned long, int, unsigned char, unsigned char);
	int TranslateAddress(unsigned long, int, int, int *, int *);
	int UnPolymorph(CGameEffect *);
	int UnequipItem(CNWSItem *, int);
	int UnpossessCreatureDM();
	int UnpossessCreature();
	int UnpossessFamiliar();
	int UnsummonMyself();
	int UpdateActionQueue();
	int UpdateAppearanceDependantInfo();
	int UpdateAppearanceForEquippedItems();
	int UpdateAttributesOnEffect(CGameEffect *, int);
	int UpdateAutoMap(unsigned long);
	int UpdateCombatRoundTimer();
	int UpdateEffectPtrs();
	int UpdateEncumbranceState(int);
	int UpdateExcitedStateTimer();
	int UpdatePersonalSpace();
	int UpdateSpecialAttacks();
	int UpdateSubareasOnJumpPosition(Vector, unsigned long);
	int UpdateSubareasOnMoveTo(Vector, Vector, int, CExoArrayList<unsigned long> *, int);
	int UpdateTrapCheckDM();
	int UpdateTrapCheck();
	int UpdateVisibleList();
	int UseFeat(unsigned short, unsigned short, unsigned long, unsigned long, Vector *);
	int UseItem(unsigned long, unsigned char, unsigned char, unsigned long, Vector, unsigned long);
	int UseLoreOnItem(unsigned long);
	int UseSkill(unsigned char, unsigned char, unsigned long, Vector, unsigned long, unsigned long, int);
	int ValidateCounterSpellData(unsigned long, unsigned char, unsigned char);
	int WalkUpdateLocationDistance(float, Vector *, Vector *, CExoArrayList<unsigned long> *);
	int WalkUpdateLocationTestDistance(Vector, Vector);
	int WalkUpdateLocation();
	~CNWSCreature();
	CNWSCreature(unsigned long, int, int);

	/* 0x0/0 */ CNWSObject Object;
	/* 0x1C4/452 */ unsigned long field_1C4;
	/* 0x1F8/504 */ char rsvd1[48];
	/* 0x1F8/504 */ CExoString HeartbeatScript;
	/* 0x200/512 */ CExoString PerceptionScript;
	/* 0x208/520 */ CExoString SpellCastAtScript;
	/* 0x210/528 */ CExoString AttackedScript;
	/* 0x218/536 */ CExoString DamagedScript;
	/* 0x220/544 */ CExoString DisturbedScript;
	/* 0x228/552 */ CExoString EndCombatScript;
	/* 0x230/560 */ CExoString ConversationScript;
	/* 0x238/568 */ CExoString SpawnScript;
	/* 0x240/576 */ CExoString RestedScript;
	/* 0x248/584 */ CExoString DeathScript;
	/* 0x250/592 */ CExoString UserDefScript;
	/* 0x258/600 */ CExoString BlockedScript;
	/* 0x260/608 */ CExoString HeartbeatScript_;
	/* 0x268/616 */ CExoString PerceptionScript_;
	/* 0x270/624 */ CExoString SpellCastAtScript_;
	/* 0x278/632 */ CExoString AttackedScript_;
	/* 0x280/640 */ CExoString DamagedScript_;
	/* 0x288/648 */ CExoString EndCombatScript_;
	/* 0x290/656 */ CExoString ConversationScript_;
	/* 0x298/664 */ CExoString SpawnScript_;
	/* 0x2A0/672 */ CExoString RestedScript_;
	/* 0x2A8/680 */ CExoString DeathScript_;
	/* 0x2B0/688 */ CExoString UserDefScript_;
	/* 0x2B8/696 */ CExoString BlockedScript_;
	/* 0x2C0/704 */ unsigned long field_2C0;
	/* 0x2C4/708 */ unsigned long field_2C4;
	/* 0x2C8/712 */ unsigned long Quickbar;
	/* 0x2CC/716 */ unsigned long Lootable;
	/* 0x2D0/720 */ unsigned long DecayTime;
	/* 0x2D4/724 */ unsigned long BodyBagID;
	/* 0x304/772 */ char rsvd2[44];
	/* 0x304/772 */ unsigned long BlockedBy;
	/* 0x308/776 */ unsigned long PositionStruct;
	/* 0x488/1160 */ char rsvd3[380];
	/* 0x488/1160 */ unsigned long LawfulChaotic;
	/* 0x48C/1164 */ unsigned long field_48C;
	/* 0x490/1168 */ void *AreaMiniMaps;
	/* (mtype:CExoArrayList<unsigned long>) */
	/* 0x494/1172 */ CExoArrayList<unsigned long> AreaList;
	/* 0x4A0/1184 */ unsigned long AreaCount;
	/* 0x4A4/1188 */ unsigned long field_4A4;
	/* 0x4B0/1200 */ char rsvd4[8];
	/* 0x4B0/1200 */ unsigned long field_4B0;
	/* 0x4C0/1216 */ char rsvd5[12];
	/* 0x4C0/1216 */ unsigned long InCombat;
	/* 0x4D4/1236 */ char rsvd6[16];
	/* 0x4D4/1236 */ unsigned long Disarmable;
	/* 0x4D8/1240 */ unsigned long CreatureSize;
	/* 0x4E4/1252 */ char rsvd7[8];
	/* 0x4E4/1252 */ unsigned long AttackTarget;
	/* 0x4E8/1256 */ unsigned long AttemptedAttackTarget;
	/* 0x4F8/1272 */ char rsvd8[12];
	/* 0x4F8/1272 */ unsigned long Attacker;
	/* 0x4FC/1276 */ unsigned long SpellTarget;
	/* 0x9E1/2529 */ char rsvd9[1249];
	/* 0x9E1/2529 */ char field_9E1;
	/* 0x9E2/2530 */ char field_9E2;
	/* 0xA18/2584 */ char rsvd10[53];
	/* 0xA18/2584 */ unsigned long PrimaryRange;
	/* 0xA20/2592 */ char rsvd11[4];
	/* 0xA20/2592 */ unsigned long SecondaryRange;
	/* 0xA84/2692 */ char rsvd12[96];
	/* 0xA84/2692 */ unsigned long field_A84;
	/* 0xA88/2696 */ unsigned long Spotted;
	/* 0xA8C/2700 */ unsigned long field_A8C[15];
	/* 0xAC8/2760 */ unsigned long field_AC8;
	/* 0xACC/2764 */ CNWSCombatRound *CombatRound;
	/* 0xAD0/2768 */ unsigned long field_AD0;
	/* 0xAD4/2772 */ void *Barter;
	/* 0xAD8/2776 */ unsigned long Gold;
	/* 0xADC/2780 */ unsigned long IsPC;
	/* 0xAE0/2784 */ unsigned short SoundSetFile;
	/* 0xAE4/2788 */ char rsvd13[2];
	/* 0xAE4/2788 */ unsigned long FootstepType;
	/* 0xAE8/2792 */ unsigned long BodyBag;
	/* 0xAEC/2796 */ unsigned long field_AEC;
	/* 0xAF0/2800 */ unsigned long field_AF0;
	/* 0xAF4/2804 */ unsigned long field_AF4;
	/* 0xAF8/2808 */ unsigned long IsImmortal;
	/* 0xAFC/2812 */ unsigned long field_AFC;
	/* 0xB00/2816 */ CExoString NameOverride;
	/* 0xB08/2824 */ unsigned long field_B08;
	/* 0xB0C/2828 */ unsigned short field_B0C;
	/* 0xB0E/2830 */ char AIState;
	/* 0xB10/2832 */ char rsvd14;
	/* 0xB10/2832 */ unsigned long field_B10;
	/* 0xB34/2868 */ char rsvd15[32];
	/* 0xB34/2868 */ unsigned long MasterID;
	/* (ptr_to:CExoArrayList<int>) */
	/* 0xB38/2872 */ CExoArrayList<int> *field_B38;
	/* 0xB5C/2908 */ char rsvd16[32];
	/* 0xB5C/2908 */ void *ReputationInformation;
	/* 0xB70/2928 */ char rsvd17[16];
	/* 0xB70/2928 */ void *Inventory;
	/* 0xB74/2932 */ void *ItemRepository;
	/* 0xB78/2936 */ unsigned short field_B78;
	/* 0xB7A/2938 */ unsigned short field_B7A;
	/* 0xB7C/2940 */ unsigned long field_B7C;
	/* 0xB80/2944 */ unsigned long field_B80[42];
	/* 0xC28/3112 */ CNWSCreatureAppearanceInfo CreatureAppearanceInfo;
	/* 0xC68/3176 */ CNWSCreatureStats *CreatureStats;
	/* 0xC6C/3180 */ unsigned long field_C6C;
	/* 0xC70/3184 */ unsigned long field_C70;
};
#endif
