#ifndef _CNWSCREATURESTATS_H_
#define _CNWSCREATURESTATS_H_
#include "nwndef.h"
#include "CExoArrayList.h"
#include "CExoString.h"
#include "CExoLocString.h"
#include "CResRef.h"
#include "CNWSCreatureStats_ClassInfo.h"

class CNWSCreatureStats
{
public:
    void AddExperience(unsigned long);
    void AddFeat(unsigned short);
    void AddKnownSpell(unsigned char, unsigned long);
    int AddSpellLikeAbilityToList(unsigned long, int, unsigned char);
    void AdjustAlignment(unsigned char, short, unsigned long);
    void AdjustSpellUsesPerDay();
    int AutoMemorizeSpells(int);
    int CalcLevelUpNumberFeats(unsigned char, unsigned char, unsigned char &, unsigned char &);
    char CalcStatModifier(unsigned char);
    int CanChooseFeat(unsigned short, unsigned char, unsigned char, CExoArrayList<unsigned short> *);
    int CanLevelUp();
    int CheckSpellSuitability(int, CNWSpell *, int, int, int, int, int, int, unsigned char &, int);
    int ClearFeats();
    void ClearMemorizedSpellSlot(unsigned char, unsigned char, unsigned char);
    void ComputeFeatBonuses(CExoArrayList<unsigned short> *, int, int);
    unsigned char ComputeNumberKnownSpellsLeft(unsigned char, unsigned char);
    int ConfirmDomainSpell(unsigned char, unsigned char, unsigned long);
    void DecrementFeatRemainingUses(unsigned short);
    void DecrementSpellsPerDayLeft(unsigned char, unsigned char);
    int FeatAcquired(unsigned short, CExoArrayList<unsigned short> *, int);
    int FeatRequirementsMetAfterLevelUp(unsigned short, CNWLevelStats *, unsigned char);
    int FeatRequirementsMet(unsigned short, CExoArrayList<unsigned short> *);
    char GetACNaturalBase(int);
    int GetAlignmentString();
    short GetArmorClassVersus(CNWSCreature *, int);
    int GetAttackModifierVersus(CNWSCreature *);
    unsigned char GetAttacksPerRound();
    int GetBaseAttackBonus(int);
    char GetBaseFortSavingThrow();
    char GetBaseReflexSavingThrow();
    char GetBaseWillSavingThrow();
    unsigned short GetBonusFeat(unsigned short);
    unsigned char GetCHAStat();
    unsigned char GetCONStat();
    int GetCanUseRelatedCategory(int, int);
    int GetCanUseSkillAfterLevelUp(unsigned short, CNWLevelStats *);
    int GetCanUseSkill(unsigned char);
    int GetCasterLevel(unsigned char);
    CNWSCreatureStats_ClassInfo * GetClassInfo(unsigned char);
    unsigned char GetClassLevel(unsigned char, int);
    unsigned char GetClassNegativeLevels(unsigned char);
    int GetClassString(unsigned char);
    unsigned char GetClass(unsigned char);
    unsigned char GetCreatureDamageDice(unsigned char);
    unsigned char GetCreatureDamageDie(unsigned char);
    int GetCreatureHasTalent(int, int, unsigned char);
    int GetCreatureTalentRandomFeat(int, int, int &, int &, unsigned char &);
    int GetCreatureTalentRandomKnownSpell(int, int, int &, int &, unsigned char &, int);
    int GetCreatureTalentRandomMemorisedSpell(int, int, int &, int &, unsigned char &, int, unsigned char &);
    int GetCreatureTalentRandomSkill(int, int, int &, int &, unsigned char &);
    int GetCreatureTalentRandomSpellFromItem(int, int, int &, int &, unsigned char &, unsigned long &, int &);
    int GetCreatureTalentRandomSpellLikeAbility(int, int, int &, int &, unsigned char &, unsigned char &);
    int GetCreatureTalentRandomSpell(int, int, int &, int &, unsigned char &, unsigned char &);
    int GetCreatureTalentRandom(int, int, int &, int &, unsigned char &, unsigned long &, int &, unsigned char &, unsigned char &);
    int GetCriticalHitMultiplier(int);
    int GetCriticalHitRoll(int);
    char GetDEXMod(int);
    unsigned char GetDEXStat();
    int GetDamageBonus(CNWSCreature *, int);
    int GetDamageRoll(CNWSObject *, int, int, int, int, int);
    unsigned char GetDomain1(unsigned char);
    unsigned char GetDomain2(unsigned char);
    int GetEffectImmunity(unsigned char, CNWSCreature *);
    unsigned char GetEffectiveCRForPotentialLevel();
    int GetEpicWeaponDevastatingCritical(CNWSItem *);
    int GetEpicWeaponFocus(CNWSItem *);
    int GetEpicWeaponOverwhelmingCritical(CNWSItem *);
    int GetEpicWeaponSpecialization(CNWSItem *);
    unsigned long GetExpNeededForLevelUp();
    int GetFavoredEnemyBonus(CNWSCreature *);
    unsigned char GetFeatRemainingUses(unsigned short);
    unsigned char GetFeatSourceClass(unsigned short);
    unsigned char GetFeatTotalUses(unsigned short);
    unsigned short GetFeat(unsigned short);
    char GetFortSavingThrow(int);
    CExoString GetFullName();
    int GetHasLostClassAbilities(unsigned char);
    int GetHasSilencedSpell(unsigned long);
    int GetHasStilledSpell(unsigned long);
    unsigned long GetHighestLevelKnown();
    unsigned short GetHighestLevelOfFeat(unsigned short);
    unsigned char GetHitDie(unsigned char, unsigned char);
    unsigned char GetINTStat();
    int GetIsClassAvailable(unsigned char);
    unsigned char GetIsClass(unsigned char);
    int GetIsDomainSpell(unsigned char, unsigned char, unsigned char);
    int GetIsEpitomeOfAlignment();
    int GetIsInKnownSpellList(unsigned char, unsigned long);
    int GetIsInSpellLikeAbilityList(unsigned long);
    int GetIsWeaponOfChoice(unsigned long);
    unsigned long GetKnownSpell(unsigned char, unsigned char, unsigned char);
    int GetLargePortrait();
    CNWLevelStats * GetLevelStats(unsigned char);
    unsigned char GetLevel(int);
    int GetMeetsPrestigeClassRequirements(CNWClass *);
    int GetMeleeAttackBonus(int, int, int);
    int GetMeleeDamageBonus(int, unsigned char);
    unsigned char GetMemorizedSpellInSlotMetaType(unsigned char, unsigned char, unsigned char);
    unsigned char GetMemorizedSpellInSlotReady(unsigned char, unsigned char, unsigned char);
    unsigned long GetMemorizedSpellInSlot(unsigned char, unsigned char, unsigned char);
    unsigned char GetMemorizedSpellReadyCount(unsigned char, unsigned long, unsigned char *, unsigned char *);
    unsigned char GetMemorizedSpellReadyCount(unsigned char, unsigned long, unsigned char);
    int GetMemorizedSpellReadyCount(unsigned long);
    int GetNumLevelsOfClass(unsigned char);
    int GetNumLevelsOfClass(unsigned char, int);
    unsigned short GetNumberKnownSpells(unsigned char, unsigned char);
    unsigned char GetNumberMemorizedSpellSlots(unsigned char, unsigned char);
    unsigned char GetPotentialLevel();
    unsigned char GetPrimaryMod(unsigned char);
    int GetRaceString();
    int GetRangedAttackBonus(int, int);
    int GetRangedDamageBonus();
    char GetReflexSavingThrow(int);
    unsigned char GetSTRStat();
    unsigned char GetSchool(unsigned char);
    unsigned char GetSimpleAlignmentGoodEvil();
    unsigned char GetSimpleAlignmentLawChaos();
    char GetSkillRank(unsigned char, CNWSObject *, int);
    int GetSmallPortrait();
    unsigned char GetSpellFailure(unsigned char);
    unsigned char GetSpellGainWithBonusAfterLevelUp(unsigned char, unsigned char, CNWLevelStats *, unsigned char, int);
    unsigned char GetSpellGainWithBonus(unsigned char, unsigned char);
    unsigned char GetSpellLikeAbilityCasterLevel(unsigned long);
    int GetSpellMinAbilityMet(unsigned char, unsigned char);
    char GetSpellResistance();
    unsigned char GetSpellUsesLeft(unsigned long, unsigned char, unsigned char, unsigned char);
    unsigned char GetSpellsOfLevelReady(unsigned char, unsigned char);
    unsigned char GetSpellsPerDayLeft(unsigned char, unsigned char);
    void GetStatBonusesFromFeats(CExoArrayList<unsigned short> *, int *, unsigned char);
    float GetStatById(int);
    int GetTag();
    char GetTotalACSkillMod();
    char GetTotalCHABonus();
    char GetTotalCONBonus();
    char GetTotalDEXBonus();
    char GetTotalINTBonus();
    int GetTotalNegativeLevels();
    char GetTotalSTRBonus();
    char GetTotalWISBonus();
    unsigned char GetUnarmedDamageDice();
    unsigned char GetUnarmedDamageDie();
    int GetUnarmedDamageRoll(CNWSObject *);
    int GetUseMonkAttackTables(int);
    unsigned char GetWISStat();
    int GetWeaponFinesse(CNWSItem *);
    int GetWeaponFocus(CNWSItem *);
    int GetWeaponImprovedCritical(CNWSItem *);
    int GetWeaponSpecialization(CNWSItem *);
    char GetWillSavingThrow(int);
    int HasFeat(unsigned short);
    void IncrementFeatRemainingUses(unsigned short);
    int IncrementSpellsPerDayLeft(unsigned char, unsigned char);
    void LevelDown(CNWLevelStats *);
    int LevelUpAutomatic(unsigned char, int, unsigned char);
    void LevelUp(CNWLevelStats *, unsigned char, unsigned char, unsigned char, int);
    int ModifyAlignment(short, short);
    void ReadSpellsFromGff(CResGFF *, CResStruct *, int);
    unsigned long ReadStatsFromGff(CResGFF *, CResStruct *, CNWSCreatureAppearanceInfo *, int, int, int);
    void ReadySpellLevel(unsigned char);
    void RemoveFeat(unsigned short);
    int RemoveKnownSpell(unsigned char, unsigned long);
    void ResetFeatRemainingUses();
    void ResetSpellLikeAbilities();
    int ResetSpellsPerDayLeft(unsigned char, unsigned char);
    int ResolveSpecialAttackAttackBonus(CNWSCreature *);
    int ResolveSpecialAttackDamageBonus(CNWSCreature *);
    void SaveClassInfo(CResGFF *, CResStruct *);
    void SaveStats(CResGFF *, CResStruct *);
    void SetArcaneSpellFailure(char);
    void SetCHABase(unsigned char);
    void SetCONBase(unsigned char, int);
    int SetClassLevel(unsigned char, unsigned char);
    void SetClassNegativeLevels(unsigned char, unsigned char);
    int SetClass(unsigned char, unsigned char);
    void SetDEXBase(unsigned char);
    int SetDomain1(unsigned char, unsigned char);
    int SetDomain2(unsigned char, unsigned char);
    void SetExperience(unsigned long, int);
    void SetFeatRemainingUses(unsigned short, unsigned char);
    int SetHasLostClassAbilities(unsigned char, int);
    void SetINTBase(unsigned char);
    int SetMemorizedSpellInSlotReady(unsigned char, unsigned char, unsigned char, int);
    int SetMemorizedSpellSlot(unsigned char, unsigned char, unsigned long, unsigned char, unsigned char, int);
    void SetMovementRate(int);
    int SetNormalBonusFlags(unsigned short, int &, int &);
    void SetNumberBonusSpells(unsigned char, unsigned char, unsigned char);
    int SetNumberMemorizedSpellSlots(unsigned char, unsigned char, unsigned char);
    void SetSTRBase(unsigned char);
    int SetSchool(unsigned char, unsigned char);
    int SetSkillRank(unsigned char, char);
    void SetSpellFailure(unsigned char, unsigned char);
    int SetSpellLikeAbilityReady(unsigned long, int, unsigned char);
    void SetSpellResistancePenalty(char);
    void SetSpellResistance(char);
    void SetStatById(int, float);
    int SetTag(CExoString const &);
    void SetWISBase(unsigned char);
    int UnReadySpell(unsigned long, unsigned char, unsigned char, unsigned char);
    void UpdateCombatInformation();
    int UpdateLastStatsObject(unsigned long long, CNWCreatureStatsUpdate *);
    void UpdateNumberMemorizedSpellSlots();
    unsigned long ValidateLevelUp(CNWLevelStats *, unsigned char, unsigned char, unsigned char);
    ~CNWSCreatureStats();
    CNWSCreatureStats(CNWSCreature *);

    /* 0x0/0 */ unsigned long field_0;
    /* 0x4/4 */ unsigned long field_4;
    /* 0x8/8 */ unsigned short field_8;
    /* 0xA/10 */ unsigned short field_A;
    /* 0x10/16 */ char rsvd1[4];
    /* 0x10/16 */ unsigned long field_10;
    /* 0x24/36 */ char rsvd2[16];
    /* 0x24/36 */ CNWSCreature *OriginalObject;
    /* 0x34/52 */ char rsvd3[12];
    /* 0x34/52 */ CExoLocString FirstName;
    /* 0x3C/60 */ CExoLocString LastName;
    /* 0x44/68 */ CResRef Conversation;
    /* 0x54/84 */ unsigned long ConvInterruptable;
    /* 0x58/88 */ unsigned long field_58;
    /* 0x60/96 */ char rsvd4[4];
    /* 0x60/96 */ unsigned long field_60;
    /* 0x64/100 */ unsigned long field_64;
    /* 0x68/104 */ unsigned long Age;
    /* 0x6C/108 */ unsigned long Gender;
    /* 0x70/112 */ unsigned long XP;
    /* 0x74/116 */ unsigned long IsPC;
    /* 0x78/120 */ unsigned long IsDM;
    /* 0x7C/124 */ unsigned long field_7C;
    /* 0x80/128 */ unsigned long field_80;
    /* 0x84/132 */ unsigned long AIDisabled;
    /* 0x88/136 */ unsigned long field_88;
    /* 0x8C/140 */ unsigned long field_8C;
    /* 0x90/144 */ unsigned long FactionID;
    /* 0x94/148 */ unsigned long field_94;
    /* 0x98/152 */ unsigned long field_98;
    /* 0x9C/156 */ unsigned long field_9C;
    /* 0xA0/160 */ char StartingPackage;
    /* 0xA1/161 */ char ClassesCount;
    /* 0xA2/162 */ char field_A2;
    /* 0xA3/163 */ char field_A3;
    /* 0xA4/164 */ CNWSCreatureStats_ClassInfo ClassInfo[3];
    /* 0x3F0/1008 */ char rsvd5[4];
    /* 0x3F0/1008 */ CExoString field_3F0;
    /* 0x49A/1178 */ char rsvd6[162];
    /* 0x49A/1178 */ char ArmorPart_RFoot;
    /* 0x49B/1179 */ char BodyPart_LFoot;
    /* 0x49C/1180 */ char BodyPart_RShin;
    /* 0x49D/1181 */ char BodyPart_LShin;
    /* 0x49E/1182 */ char BodyPart_LThigh;
    /* 0x49F/1183 */ char BodyPart_RThigh;
    /* 0x4A0/1184 */ char BodyPart_Pelvis;
    /* 0x4A1/1185 */ char BodyPart_Torso;
    /* 0x4A2/1186 */ char BodyPart_Belt;
    /* 0x4A3/1187 */ char BodyPart_Neck;
    /* 0x4A4/1188 */ char BodyPart_RFArm;
    /* 0x4A5/1189 */ char BodyPart_LFArm;
    /* 0x4A6/1190 */ char BodyPart_RBicep;
    /* 0x4A7/1191 */ char BodyPart_LBicep;
    /* 0x4A8/1192 */ char BodyPart_RShoul;
    /* 0x4A9/1193 */ char BodyPart_LShoul;
    /* 0x4AA/1194 */ char BodyPart_RHand;
    /* 0x4AB/1195 */ char BodyPart_LHand;
    /* 0x4E4/1252 */ char rsvd7[56];
    /* 0x4E4/1252 */ unsigned long field_4E4;
};

static_assert_size(CNWSCreatureStats, 0x4e8);

#endif
