#ifndef _CNWSPLACEABLE_H_
#define _CNWSPLACEABLE_H_
#include "nwndef.h"
#include "CNWSObject.h"
#include "Vector.h"
#include "CExoString.h"
#include "CResRef.h"
#include "CExoLocString.h"

class CNWSPlaceable : public CNWSObject
{
public:
    unsigned long AIActionCastSpell(CNWSObjectActionNode *);
    void AIUpdate();
    int AcquireItem(CNWSItem **, unsigned long, unsigned char, unsigned char, int);
    unsigned long AcquireItemsFromObject(unsigned long, int);
    int AddCastSpellActions(unsigned long, int, Vector, unsigned long, int, unsigned char);
    void AddToArea(CNWSArea *, float, float, float, int);
    CNWSPlaceable * AsNWSPlaceable();
    void CalculateActionPoints();
    void CloseInventory(unsigned long, int);
    void ClosePlaceableForAllPlayers();
    void DoDamage(int);
    int DropItemsIntoArea();
    void EventHandler(unsigned long, unsigned long, void *, unsigned long, unsigned long);
    int GetActive();
    int GetAppearance();
    int GetAutoRemoveKey();
    int GetBaseType();
    int GetBearing();
    unsigned short GetBodyBagAppearance();
    int GetBodyBag();
    int GetCloseLockDC();
    int GetCreatureList();
    int GetCurrentItemContainer();
    CExoString GetDescriptionOverride();
    CExoLocString & GetDescription();
    int GetDetectDC();
    int GetDetectable();
    CResRef GetDialogResref();
    int GetDieWhenEmpty();
    int GetDisarmDC();
    int GetDisarmable();
    CExoString GetDisplayName();
    unsigned long GetEffectSpellId();
    int GetFactionId();
    CExoLocString & GetFirstName();
    int GetFlagged();
    int GetFortSave();
    int GetHardness();
    int GetHasInventory();
    int GetIsBodyBag();
    int GetIsGroundPile();
    int GetItemContainerArrayIndex();
    unsigned long GetItemCount(int);
    int GetItemRepository();
    int GetKeyName();
    CExoString GetKeyRequiredFeedbackMessage();
    int GetKeyRequired();
    int GetLastClosed();
    int GetLastDefaultClickedBy();
    int GetLastDisarmed();
    int GetLastLocked();
    int GetLastOpened();
    int GetLastTriggered();
    int GetLastUnlocked();
    int GetLastUser();
    int GetLightIsOn();
    int GetLightStateChange();
    int GetLockable();
    int GetLocked();
    int GetLootableCreatureId();
    Vector GetNearestActionPoint(Vector const &);
    int GetNeverMakeIntoStaticObject();
    int GetOneShot();
    int GetOpenLockDC();
    int GetPickable();
    CExoString GetPortalInfo();
    int GetRecoverable();
    int GetReflexSave();
    int GetRepositoryArrayIndex();
    int GetScriptName(int);
    int GetSittingCreature();
    int GetStaticObject();
    int GetTemplateResRef();
    int GetTrapCreator();
    int GetTrapFaction();
    int GetTrapped();
    int GetType();
    int GetUpdateDisplayName();
    int GetUseable();
    int GetWillSave();
    int LoadBodyBag(unsigned short);
    int LoadFromTemplate(CResRef, CExoString *);
    int LoadPlaceable(CResGFF *, CResStruct *, CExoString *);
    void OpenInventory(unsigned long);
    void PostProcess();
    void RemoveFromArea();
    int RemoveItem(CNWSItem *, int);
    int SavePlaceable(CResGFF *, CResStruct *);
    int SetActive(int);
    int SetAppearance(unsigned short);
    int SetAutoRemoveKey(int);
    int SetBaseType(unsigned char);
    int SetBearing(float);
    int SetBodyBag(unsigned char);
    int SetCloseLockDC(unsigned char);
    int SetCurrentItemContainer(unsigned long);
    void SetDescriptionOverride(CExoString);
    void SetDescription(CExoLocString);
    int SetDetectDC(unsigned char);
    int SetDetectable(int);
    void SetDialogResref(CResRef);
    int SetDieWhenEmpty(int);
    int SetDisarmDC(unsigned char);
    int SetDisarmable(int);
    void SetDisplayName(CExoString);
    void SetEffectSpellId(unsigned long);
    int SetFactionId(int);
    void SetFirstName(CExoLocString);
    int SetFlagged(unsigned char);
    int SetFortSave(unsigned char);
    int SetHardness(unsigned char);
    int SetHasInventory(int);
    int SetIsBodyBag(int);
    int SetIsGroundPile(int);
    int SetItemContainerArrayIndex(unsigned short);
    int SetKeyName(CExoString const &);
    void SetKeyRequiredFeedbackMessage(CExoString);
    int SetKeyRequired(int);
    int SetLastClosed(unsigned long);
    int SetLastDefaultClickedBy(unsigned long);
    int SetLastDisarmed(unsigned long);
    int SetLastLocked(unsigned long);
    int SetLastOpened(unsigned long);
    int SetLastTriggered(unsigned long);
    int SetLastUnlocked(unsigned long);
    int SetLastUser(unsigned long);
    void SetLightIsOn(int);
    int SetLightStateChange(int);
    int SetLockable(int);
    int SetLocked(int);
    int SetLootableCreatureId(unsigned long);
    int SetNeverMakeIntoStaticObject(int);
    int SetOneShot(int);
    int SetOpenLockDC(unsigned char);
    void SetOrientation(Vector);
    int SetPickable(int);
    void SetPortalInfo(CExoString);
    int SetRecoverable(int);
    int SetReflexSave(unsigned char);
    int SetRepositoryArrayIndex(unsigned short);
    void SetScriptName(int, CExoString);
    int SetSittingCreature(unsigned long);
    int SetStaticObject(int);
    void SetTemplateResRef(CResRef);
    int SetTrapCreator(unsigned long);
    int SetTrapFaction(int);
    int SetTrapped(int);
    int SetType(unsigned char);
    int SetUpdateDisplayName(int);
    int SetUseable(int);
    int SetWillSave(unsigned char);
    ~CNWSPlaceable();
    CNWSPlaceable(unsigned long);

    /* 0x1C4/452 */ CExoLocString Name;
    /* 0x1CC/460 */ unsigned long DisplayName;
    /* 0x1D0/464 */ unsigned long field_1D0;
    /* 0x1D4/468 */ unsigned long field_1D4;
    /* 0x1D8/472 */ unsigned long field_1D8;
    /* 0x1DC/476 */ unsigned long field_1DC;
    /* 0x1E0/480 */ unsigned long field_1E0;
    /* 0x1E4/484 */ unsigned long field_1E4;
    /* 0x1E8/488 */ unsigned long field_1E8;
    /* 0x1EC/492 */ unsigned long field_1EC;
    /* 0x1F0/496 */ unsigned long field_1F0;
    /* 0x1F4/500 */ unsigned long field_1F4;
    /* 0x1F8/504 */ unsigned long field_1F8;
    /* 0x1FC/508 */ unsigned long field_1FC;
    /* 0x264/612 */ char rsvd1[100];
    /* 0x264/612 */ CExoString OnClosed;
    /* 0x26C/620 */ CExoString OnDamaged;
    /* 0x274/628 */ CExoString OnDeath;
    /* 0x27C/636 */ CExoString OnDisarm;
    /* 0x284/644 */ CExoString OnHeartbeat;
    /* 0x28C/652 */ CExoString OnInvDisturbed;
    /* 0x294/660 */ CExoString OnLock;
    /* 0x29C/668 */ CExoString OnMeleeAttacked;
    /* 0x2A4/676 */ CExoString OnOpen;
    /* 0x2AC/684 */ CExoString OnSpellCastAt;
    /* 0x2B4/692 */ CExoString OnUnlock;
    /* 0x2BC/700 */ CExoString OnUsed;
    /* 0x2C4/708 */ CExoString OnUserDefined;
    /* 0x2CC/716 */ CExoString OnDialog;
    /* 0x2D4/724 */ CExoString OnTrapTriggered;
    /* 0x2DC/732 */ CExoString OnClick;
    /* 0x36C/876 */ char rsvd2[136];
    /* 0x36C/876 */ unsigned long field_36C;
    /* 0x370/880 */ unsigned long field_370;
    /* 0x374/884 */ unsigned long field_374;
    /* 0x378/888 */ unsigned long field_378;
    /* 0x37C/892 */ unsigned long field_37C;
    /* 0x380/896 */ unsigned long LightIsOn;
    /* 0x384/900 */ unsigned long LightsUpdate;
    /* 0x388/904 */ unsigned long field_388;
    /* 0x38C/908 */ unsigned long IsStatic;
    /* 0x390/912 */ unsigned long NeverMakeIntoStatic;
};
#endif
