#ifndef _CSERVEREXOAPP_H_
#define _CSERVEREXOAPP_H_
#include "nwndef.h"
#include "CExoString.h"
#include "CExoArrayList.h"
#include "CResRef.h"
#include "nwnstructs.h"
#include "CServerExoAppInternal.h"

class CServerExoApp
{
public:
	int AddCDKeyToBannedList(CExoString);
	int AddCharListRequest(unsigned long);
	int AddIPToBannedList(CExoString);
	int AddPlayerNameToBannedList(CExoString);
	int AddSubNetProfileSendSize(unsigned long, unsigned long);
	int AddToExclusionList(unsigned long, unsigned char);
	int AdmitNetworkAddress(unsigned long, CExoString);
	int AdmitPlayerName(CExoString);
	int ContinueMessageProcessing();
	int ExportAllPlayers();
	int GSClientAddServer(void *, char *, char *, int, int, int, int, char *, int, int, char *, int, int, int, char *, char *, int, int, int, int, int, bool);
	int GSClientChatMessage(int, CExoString, CExoString);
	int GSClientClearServers();
	int GSClientGroupRoomAdded(int, unsigned long);
	int GSClientRemoveServer(void *);
	int GSClientUpdateConnectionPhase(unsigned char, CExoString const &);
	int GSClientUpdateServer(void *, char *, char *, int, int, int, int, char *, int, int, char *, int, int, int, char *, char *, int, int, int, int, int, bool);
	int GetActiveExclusionList();
	int GetActivePauseState();
	int GetActiveTimer(unsigned long);
	int GetApplicationId();
	int GetAreaByGameObjectID(unsigned long);
	int GetAreaOfEffectByGameObjectID(unsigned long);
	int GetAutoSavePending();
	int GetBannedListString();
	int GetCDKeys(CExoArrayList<CExoString> **);
	int GetClientObjectByObjectId(unsigned long);
	int GetClientObjectByPlayerId(unsigned long, unsigned char);
	int GetCodeBase();
	int GetConnectionLib();
	int GetCreatureByGameObjectID(unsigned long);
	int GetCreatureDeathLogging();
	int GetDebugMode();
	int GetDifficultyOption(int);
	int GetDoorByGameObjectID(unsigned long);
	int GetEncounterByGameObjectID(unsigned long);
	int GetExoAppInternal();
	int GetExportCharacterPending();
	int GetExportPlayersCharacter();
	int GetExtendedServerInfo();
	int GetExtendedServerInfo(CExtendedServerInfo *);
	int GetFPS();
	int GetFactionOfObject(unsigned long, int *);
	int GetFirstPCObject();
	int GetGameObject(unsigned long);
	int GetGameSpyEnabled();
	int GetImportingChar();
	int GetIsCDKeyOnBannedList(CExoString);
	int GetIsControlledByPlayer(unsigned long);
	int GetIsIPOnBannedList(CExoString);
	int GetIsMultiPlayer();
	int GetIsPlayerNameOnBannedList(CExoString);
	int GetItemByGameObjectID(unsigned long);
	int GetLoadingModule();
	int GetModuleByGameObjectID(unsigned long);
	int GetModuleDescription();
	int GetModuleLanguage();
	int GetModuleName();
	int GetModule();
	int GetMoveToModulePending();
	int GetMoveToModuleString();
	int GetMultiplayerEnabled();
	int GetNWSMessage();
	int GetNetLayer();
	int GetNextPCObject();
	int GetObjectArray();
	int GetPauseState(unsigned char);
	int GetPauseTimer();
	int GetPlaceMeshManager();
	int GetPlaceableByGameObjectID(unsigned long);
	int GetPlayerAddressData(unsigned long, unsigned long *, unsigned char **, unsigned char **, unsigned long *);
	int GetPlayerIDByGameObjectID(unsigned long);
	int GetPlayerLanguage(unsigned long);
	int GetPlayerListString();
	int GetPlayerList();
	int GetPortalListString();
	int GetReloadModuleWhenEmpty();
	int GetServerAIMaster();
	int GetServerInfo();
	int GetServerMode();
	int GetSoundObjectByGameObjectID(unsigned long);
	int GetStoreByGameObjectID(unsigned long);
	int GetSysAdminList();
	int GetTimestopTimer();
	int GetTriggerByGameObjectID(unsigned long);
	int GetWaypointByGameObjectID(unsigned long);
	int GetWorldTimer();
	int HandleGameSpyToServerMessage(int, void *, int);
	int HandleMessage(unsigned long, unsigned char *, unsigned long, int);
	int Initialize();
	int InitiateModuleForPlayer(void *);
	int IsOnActiveExclusionList(unsigned long);
	int IsOnExclusionList(unsigned long);
	int LoadCharacterFinish(CNWSPlayer *, int, int);
	int LoadCharacterStart(unsigned char, CNWSPlayer *, CResRef, void *, unsigned long);
	int LoadGame(unsigned long, CExoString &, CExoString &, CNWSPlayer *);
	int LoadModule(CExoString, int, CNWSPlayer *);
	int LoadPrimaryPlayer(CNWSPlayer *);
	int MainLoop();
	int MovePlayerToArea(void *);
	int OnCDChange();
	int OnExit();
	int OnGainFocus();
	int OnLostFocus();
	int OnVideoChange();
	int PlayerListChange(unsigned long, int, int);
	int PushMessageOverWall(unsigned char *, unsigned long);
	int RemoveCDKeyFromBannedList(CExoString);
	int RemoveFromExclusionList(unsigned long, unsigned char);
	int RemoveIPFromBannedList(CExoString);
	int RemovePCFromWorld(CNWSPlayer *);
	int RemovePlayerNameFromBannedList(CExoString);
	int ResolvePlayerByFirstName(CExoString const &);
	int RestartNetLayer();
	int RunModule();
	int SaveGame(unsigned long, CExoString &, CExoString &, CNWSPlayer *, int, CExoString &);
	int SendCharacterQuery(CNWSPlayer *);
	int SetApplicationIdsMatch(int);
	int SetAutoSavePending(int);
	int SetDebugMode(int);
	int SetEndGamePending(int);
	int SetEndGameString(CExoString &);
	int SetExportCharacterPending(int);
	int SetExportPlayersCharacter(unsigned long);
	int SetForceUpdate();
	int SetGameSpyEnabled(int);
	int SetGameSpyReporting(int);
	int SetImportingChar(int);
	int SetLoadingModule(int);
	int SetMoveToModulePending(int);
	int SetMoveToModuleString(CExoString &);
	int SetNetworkAddressBan(unsigned long, CExoString, int);
	int SetPauseState(unsigned char, int);
	int SetReloadModuleWhenEmpty(int);
	int SetWeGotDisconnected();
	int ShutDownToMainMenu();
	int ShutdownNetLayer();
	int Shutdown(int, int);
	int StartNewModule(CExoString &);
	int StartServices();
	int StopServices();
	int StripColorTokens(CExoString &);
	int TogglePauseState(unsigned char);
	int Uninitialize();
	int UnloadModule();
	int ValidatePlayerLogin(void *);
	int VomitServerOptionsToLog();
	~CServerExoApp();
	CServerExoApp();

	/* 0x0/0 */ CServerExoApp_vt *vt;
	/* 0x4/4 */ CServerExoAppInternal *Internal;
};
#endif
